Repository ezEngine/ezEngine, pull requests merged in 2021-08, with the labels that each got.

#445 Added a help button for components
  Code/Engine/Foundation/Strings/Implementation/TranslationLookup.cpp
  Code/Engine/Foundation/Strings/TranslationLookup.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/ElementGroupButton.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/ElementGroupButton.moc.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/PropertyBaseWidget.moc.h
  Data/Tools/ezEditor/Localization/en/AssetsPlugin.txt
  Data/Tools/ezEditor/Localization/en/FmodPlugin.txt
  Data/Tools/ezEditor/Localization/en/KrautPlugin.txt
  Data/Tools/ezEditor/Localization/en/ParticlePlugin.txt
  Data/Tools/ezEditor/Localization/en/PhysXPlugin.txt
  Data/Tools/ezEditor/Localization/en/RecastPlugin.txt
  Data/Tools/ezEditor/Localization/en/ScenePlugin.txt
  Data/Tools/ezEditor/Localization/en/TypeScriptPlugin.txt
Labels: enhancement

#447 Create scene thumbnails on demand and skip thumbnail generation in unit tests
  Code/Editor/EditorFramework/Assets/Implementation/AssetCurator.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SceneActions.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Dialogs/ExportAndRunDlg.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Dialogs/ExportAndRunDlg.moc.h
  Code/EditorPlugins/Scene/EditorPluginScene/Dialogs/ExportAndRunDlg.ui
  Code/UnitTests/GameEngineTest/Basics/Basics.cpp
  Data/Tools/ezEditor/InputSlots/Keyboard.txt
  Data/Tools/ezEditor/InputSlots/Mouse.txt
  Data/Tools/ezEditor/InputSlots/XBox.txt
Labels: enhancement

#452 Build system improvements
  Code/BuildSystem/CMake/ezUtils.cmake
  Code/BuildSystem/CMake/ezUtilsCppFlags.cmake
  Code/BuildSystem/CMake/ezUtilsDetect.cmake
  Code/BuildSystem/CMake/ezUtilsTarget.cmake
  Code/BuildSystem/CMake/ezUtilsTargetCS.cmake
  Code/Engine/CMakeLists.txt
  Code/Engine/Core/System/Implementation/Window.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/Archive.cpp
  Code/Engine/Foundation/IO/Implementation/StreamOperationsOther.cpp
  Code/Engine/Foundation/Strings/Implementation/StringUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/String_inl.h
  Code/Engine/Foundation/System/Implementation/Win/EnvironmentVariableUtils_win.h
  Code/Engine/GameEngine/DearImgui/Implementation/DearImguiRenderer.cpp
  Code/Engine/GameEngine/Gameplay/Implementation/GrabbableItemComponent.cpp
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraph.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationClipResource.cpp
  Code/Engine/RendererCore/Decals/Implementation/DecalComponent.cpp
  Code/Engine/RendererCore/Pipeline/Implementation/Extractor.cpp
  Code/Engine/Texture/Image/Formats/TgaFileFormat.cpp
  Code/Engine/ezBuildInfo.h.in
  Code/UnitTests/FoundationTest/Containers/SmallArrayTest.cpp
  Code/UnitTests/FoundationTest/IO/DdlUtilsTest.cpp
  Code/UnitTests/TestFramework/Framework/Qt/qtTestGUI.cpp
  Code/UnitTests/TestFramework/Framework/TestBaseClass.h
  Code/UnitTests/TestFramework/Framework/TestFramework.cpp
  Code/UnitTests/TestFramework/Framework/TestFramework.h
  Code/UnitTests/TestFramework/Framework/TestResults.cpp
Labels: enhancement, code quality

#453 Added a component to simulate simple sheets of cloth
  Code/EditorPlugins/PhysX/EditorPluginPhysX/CollisionMeshAsset/CollisionMeshAsset.cpp
  Code/Engine/GameEngine/Effects/Wind/Implementation/WindVolumeComponent.cpp
  Code/Engine/GameEngine/Effects/Wind/WindVolumeComponent.h
  Code/Engine/GameEngine/Physics/ClothSheetComponent.h
  Code/Engine/GameEngine/Physics/ClothSheetSimulator.h
  Code/Engine/GameEngine/Physics/Implementation/ClothSheetComponent.cpp
  Code/Engine/GameEngine/Physics/Implementation/ClothSheetSimulator.cpp
  Code/Engine/RendererCore/Declarations.h
  Code/Engine/RendererCore/Meshes/DynamicMeshBufferResource.h
  Code/Engine/RendererCore/Meshes/Implementation/DynamicMeshBufferResource.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshBufferResource.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshComponent.cpp
  Code/Engine/RendererCore/Meshes/MeshBufferResource.h
  Code/Engine/RendererCore/RenderContext/Implementation/RenderContext.cpp
  Code/Engine/RendererCore/RenderContext/RenderContext.h
  Code/Engine/RendererDX11/CommandEncoder/Implementation/CommandEncoderImplDX11.cpp
  Code/Engine/RendererFoundation/Device/Device.h
  Code/Engine/RendererFoundation/Device/Implementation/Device.cpp
  Code/EnginePlugins/ParticlePlugin/Behavior/ParticleBehavior_Velocity.cpp
  Code/EnginePlugins/ParticlePlugin/Behavior/ParticleBehavior_Velocity.h
  Code/EnginePlugins/ProcGenPlugin/Tasks/Implementation/VertexColorTask.cpp
  Data/Base/Materials/Common/Reference.ezMaterialAsset
  Data/Samples/Testing Chambers/ParticleFX/Mist.ezParticleEffectAsset
  Data/Samples/Testing Chambers/Prefabs/Player_data/Player.ts
  Data/Samples/Testing Chambers/Scenes/Wind.ezScene
  Data/Samples/Testing Chambers/Scenes/Wind_data/Cone.ezMeshAsset
  Data/Samples/Testing Chambers/Scenes/Wind_data/Cylinder.ezMeshAsset
  Data/Samples/Testing Chambers/Scenes/Wind_data/OrangeTransparent.ezMaterialAsset
  Data/Tools/ezEditor/Localization/en/ScenePlugin.txt
Labels: new feature

#456 Added locking flags to the dynamic PhysX actors
  Code/EnginePlugins/PhysXPlugin/Components/Implementation/PxDynamicActorComponent.cpp
  Code/EnginePlugins/PhysXPlugin/Components/PxDynamicActorComponent.h
  Data/Platform/UWP/package_template.appxManifest
  Data/Tools/ezEditor/Localization/en/PhysXPlugin.txt
  Data/Tools/ezEditor/Localization/en/ScenePlugin.txt
Labels: enhancement, new feature
