Repository ezEngine/ezEngine, pull requests merged in 2021-11, with the labels that each got.

#492 Added a component to render custom geometry
  Code/Engine/GameEngine/Physics/Implementation/ClothSheetComponent.cpp
  Code/Engine/RendererCore/Meshes/CustomMeshComponent.h
  Code/Engine/RendererCore/Meshes/DynamicMeshBufferResource.h
  Code/Engine/RendererCore/Meshes/Implementation/CustomMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/DynamicMeshBufferResource.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshComponentBase.cpp
  Code/Engine/RendererCore/Meshes/MeshBufferResource.h
  Code/Engine/RendererCore/RenderContext/Implementation/RenderContext.cpp
  Code/Engine/RendererCore/RenderContext/RenderContext.h
  Code/Engine/RendererFoundation/Basics.cpp
  Code/Engine/RendererFoundation/Descriptors/Descriptors.h
  Code/Engine/RendererFoundation/RendererFoundationDLL.h
  Code/Engine/RendererFoundation/Resources/ResourceFormats.h
  Data/Base/Shaders/Materials/DefaultMaterial.ezShader
  Data/Tools/ezEditor/Localization/en/ScenePlugin.txt
Labels: new feature

#494 Added a resource for config files
  Code/Engine/RendererCore/Decals/Implementation/DecalAtlasResource.cpp
  Code/Engine/Utilities/Resources/ConfigFileResource.cpp
  Code/Engine/Utilities/Resources/ConfigFileResource.h
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/QtProgressbar.cpp
  Code/Tools/Libs/GuiFoundation/UIServices/QtProgressbar.h
Labels: new feature

#496 Fixed bbox of the heightfield component
  Code/Engine/GameEngine/Terrain/Implementation/HeightfieldComponent.cpp
Labels: bug

#498 Fixed navmesh generation
  Code/EnginePlugins/RecastPlugin/NavMeshBuilder/NavMeshBuilder.cpp
Labels: bug

#501 C++ project generation improvements
  CMakeLists.txt
  Code/BuildSystem/CMake/ezUtils.cmake
  Code/BuildSystem/CMake/ezUtilsExternal.cmake
  Code/BuildSystem/CMake/ezUtilsUnityFiles.cmake
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.cpp
  Code/Editor/EditorFramework/EditorApp/Configuration/EnginePlugins.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CMakeLists.txt
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleBounceComponent.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleBounceComponent.h
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleRenderComponent.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleRenderComponent.h
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/CppProjectPluginDLL.h
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/CppProjectPluginPCH.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/CppProjectPluginPCH.h
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/GameState/CppProjectGameState.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/GameState/CppProjectGameState.h
Labels: enhancement, new feature
