Repository ezEngine/ezEngine, pull requests merged in 2023-11, with the labels that each got.

#1093 Force transforming collection assets is now handled in a more general way
  .editorconfig
  Code/Editor/EditorFramework/Assets/AssetCurator.h
  Code/Editor/EditorFramework/Assets/AssetDocumentManager.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetCurator.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/CollectionAsset/CollectionAssetManager.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/CollectionAsset/CollectionAssetManager.h
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SceneActions.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.h
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltCustomShapeInfo.cpp
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltCustomShapeInfo.h
Labels: improvement

#1102 Re-implemented "Sort by Recently Used" asset browser feature
  Code/Editor/EditorFramework/Assets/AssetBrowserFilter.moc.h
  Code/Editor/EditorFramework/Assets/AssetBrowserModel.moc.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
Labels: improvement

#1103 Fixed #1100: Newly created assets are now functional right away
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Tools/Libs/ToolsFoundation/Document/Implementation/Declarations.h
Labels: bug

#1101 Updated Jolt and enabled shared objects on Linux
  Code/ThirdParty/Jolt/CMakeLists.txt
  Code/ThirdParty/Jolt/Core/Color.h
  Code/ThirdParty/Jolt/Core/Core.h
  Code/ThirdParty/Jolt/Core/Memory.cpp
  Code/ThirdParty/Jolt/Core/Profiler.h
  Code/ThirdParty/Jolt/Core/StreamIn.h
  Code/ThirdParty/Jolt/Core/StreamOut.h
  Code/ThirdParty/Jolt/Geometry/ClosestPoint.h
  Code/ThirdParty/Jolt/Geometry/EPAConvexHullBuilder.h
  Code/ThirdParty/Jolt/Geometry/EPAPenetrationDepth.h
  Code/ThirdParty/Jolt/Geometry/GJKClosestPoint.h
  Code/ThirdParty/Jolt/Geometry/OrientedBox.h
  Code/ThirdParty/Jolt/Math/DVec3.inl
  Code/ThirdParty/Jolt/ObjectStream/ObjectStream.h
  Code/ThirdParty/Jolt/ObjectStream/SerializableObject.h
  Code/ThirdParty/Jolt/Physics/Body/Body.h
  Code/ThirdParty/Jolt/Physics/Character/CharacterBase.h
  Code/ThirdParty/Jolt/Physics/Constraints/ConstraintPart/AxisConstraintPart.h
  Code/ThirdParty/Jolt/Physics/Constraints/ConstraintPart/PointConstraintPart.h
  Code/ThirdParty/Jolt/Physics/Constraints/ConstraintPart/RotationQuatConstraintPart.h
  Code/ThirdParty/Jolt/Physics/Constraints/ContactConstraintManager.cpp
  Code/ThirdParty/Jolt/Physics/Constraints/ContactConstraintManager.h
  Code/ThirdParty/Jolt/Physics/PhysicsSystem.cpp
  Code/ThirdParty/Jolt/Physics/Vehicle/VehicleCollisionTester.h
  Code/ThirdParty/Jolt/Physics/Vehicle/VehicleController.h
  Code/ThirdParty/Jolt/Physics/Vehicle/Wheel.h
  Code/ThirdParty/Jolt/TriangleGrouper/TriangleGrouper.h
  Code/ThirdParty/Jolt/TriangleSplitter/TriangleSplitter.h
Labels: improvement

#1104 Several smaller improvements
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Preferences/EditorPreferences.cpp
  Code/Editor/EditorFramework/Preferences/EditorPreferences.h
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetObjects.cpp
  Code/EditorPlugins/Particle/EditorPluginParticle/ParticleEffectAsset/ParticleEffectAssetWindow.cpp
  Code/EditorPlugins/Particle/EditorPluginParticle/ParticleEffectAsset/ParticleEffectAssetWindow.moc.h
  Code/EditorPlugins/Scene/EditorPluginScene/EditorPluginScene.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/Scene2DocumentWindow.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocumentWindow.cpp
  Code/Engine/Foundation/System/Implementation/Win/StackTracer_win.h
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Tools/Libs/GuiFoundation/DocumentWindow/DocumentWindow.cpp
  Data/Base/Editor/DocumentTemplates/Default.ezParticleEffectAsset
Labels: improvement

#1105 Fixed #1092: Asset browser is now used as regular file picker
  Code/Editor/EditorFramework/Assets/AssetBrowserDlg.moc.h
  Code/Editor/EditorFramework/Assets/AssetBrowserDlg.ui
  Code/Editor/EditorFramework/Assets/AssetBrowserFilter.moc.h
  Code/Editor/EditorFramework/Assets/AssetBrowserModel.moc.h
  Code/Editor/EditorFramework/Assets/AssetBrowserWidget.moc.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserDlg.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFilter.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserView.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocumentGenerator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetImportDlg.cpp
  Code/Editor/EditorFramework/Dialogs/SnapSettingsDlg.cpp
  Code/Editor/EditorFramework/EditorApp/Documents.cpp
  Code/Editor/EditorFramework/EditorApp/EditorApp.moc.h
  Code/Editor/EditorFramework/Panels/AssetBrowserPanel/AssetBrowserPanel.cpp
  Code/Editor/EditorFramework/Panels/AssetBrowserPanel/AssetBrowserPanel.moc.h
  Code/Editor/EditorFramework/Panels/AssetCuratorPanel/Implementation/AssetCuratorPanel.cpp
  Code/Editor/EditorFramework/Panels/CVarPanel/CVarPanel.cpp
  Code/Editor/EditorFramework/Panels/LogPanel/Implementation/LogPanel.cpp
  Code/Editor/EditorFramework/Panels/LongOpsPanel/LongOpsPanel.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/DynamicBitflagsPropertyWidget.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/FileBrowserPropertyWidget.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.h
  Code/Engine/Foundation/Strings/Implementation/TranslationLookup.cpp
  Code/Engine/Foundation/Strings/TranslationLookup.h
  Code/Tools/Libs/GuiFoundation/ActionViews/Implementation/QtProxy.cpp
  Code/Tools/Libs/GuiFoundation/Dialogs/ModifiedDocumentsDlg.cpp
  Code/Tools/Libs/GuiFoundation/Dialogs/ShortcutEditorDlg.cpp
  Code/Tools/Libs/GuiFoundation/DockPanels/ApplicationPanel.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/Node.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/NodeScene.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/Pin.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/AddSubElementButton.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/TypeWidget.cpp
  Code/Tools/Libs/GuiFoundation/Widgets/CollapsibleGroupBox.moc.h
  Code/Tools/Libs/GuiFoundation/Widgets/GroupBoxBase.moc.h
  Code/Tools/Libs/GuiFoundation/Widgets/Implementation/CollapsibleGroupBox.cpp
  Code/Tools/Libs/GuiFoundation/Widgets/Implementation/GroupBoxBase.cpp
  Code/Tools/Libs/GuiFoundation/Widgets/Implementation/InlinedGroupBox.cpp
  Code/Tools/Libs/GuiFoundation/Widgets/Implementation/SearchableMenu.cpp
  Code/Tools/Libs/GuiFoundation/Widgets/InlinedGroupBox.moc.h
  Code/Tools/Libs/GuiFoundation/Widgets/SearchableMenu.moc.h
Labels: improvement

#1108 GUIFoundation: Add Document Close Window Options.
  Code/Tools/Libs/GuiFoundation/Action/DocumentActions.h
  Code/Tools/Libs/GuiFoundation/Action/Implementation/DocumentActions.cpp
  Data/Tools/ezEditor/Localization/en/Editor.txt
Labels: improvement

#1107 Fixed #429: Made it easier to import multiple files as assets
  Code/Editor/EditorFramework/Assets/AssetBrowserWidget.moc.h
  Code/Editor/EditorFramework/Assets/AssetDocumentGenerator.h
  Code/Editor/EditorFramework/Assets/AssetImportDlg.moc.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocumentGenerator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetImportDlg.cpp
  Code/Editor/EditorFramework/EditorApp/Documents.cpp
  Code/Editor/EditorFramework/EditorApp/EditorApp.moc.h
  Code/Editor/EditorFramework/QtResources/Icons/ImportableFile.svg
  Code/Editor/EditorFramework/QtResources/Icons/ImportableFileType.svg
  Code/Editor/EditorFramework/QtResources/Icons/ImportedFile.svg
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/LUTAsset/LUTAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/LUTAsset/LUTAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureAsset/TextureAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureAsset/TextureAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureCubeAsset/TextureCubeAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureCubeAsset/TextureCubeAsset.h
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.h
  Code/EditorPlugins/Kraut/EditorPluginKraut/KrautTreeAsset/KrautTreeAsset.cpp
  Code/EditorPlugins/Kraut/EditorPluginKraut/KrautTreeAsset/KrautTreeAsset.h
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAsset.h
  Code/Engine/Foundation/IO/Implementation/OSFile.cpp
  Code/Engine/Foundation/IO/OSFile.h
  Data/Tools/ezEditor/Localization/en/AnimatedMeshAsset.txt
  Data/Tools/ezEditor/Localization/en/LutAsset.txt
  Data/Tools/ezEditor/Localization/en/MeshAsset.txt
  Data/Tools/ezEditor/Localization/en/SkeletonAsset.txt
  Data/Tools/ezEditor/Localization/en/TextureAsset.txt
Labels: new feature

#1110 Various Fixes
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserDlg.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFilter.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/QtAssetLineEdit.cpp
  Code/Editor/EditorFramework/PropertyGrid/QtAssetLineEdit.moc.h
  Code/EditorPlugins/Assets/EditorPluginAssets/MaterialAsset/MaterialAsset.cpp
  Code/Tools/Libs/GuiFoundation/ContainerWindow/ContainerWindow.cpp
  Code/Tools/Libs/ToolsFoundation/Utilities/Implementation/RecentFilesList.cpp
  Data/Samples/Testing Chambers/FleetOps/Calypso_data/Calypso.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/Cassiopeia_data/Cassiopeia.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/ExcelsiorII_data/Excelsior.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/Generix_data/Generix0.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/Generix_data/Generix1.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/Raptor_data/Raptor.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/Shashura_data/Shashura.ezMaterialAsset
  Data/Samples/Testing Chambers/FleetOps/Sovereign_data/Sovereign.ezMaterialAsset
Labels: improvement

#1113 Several compilation fixes
  Code/Engine/Foundation/Communication/Implementation/DataTransfer.cpp
  Code/Engine/Foundation/Containers/ArrayBase.h
  Code/Engine/Foundation/Containers/HashTable.h
  Code/Engine/Foundation/Containers/Implementation/ArrayBase_inl.h
  Code/Engine/Foundation/Containers/Implementation/ArrayIterator.h
  Code/Engine/Foundation/Containers/Implementation/DynamicArray_inl.h
  Code/Engine/Foundation/Containers/Implementation/Map_inl.h
  Code/Engine/Foundation/Containers/Map.h
  Code/Engine/Foundation/Containers/Set.h
  Code/Engine/Foundation/DataProcessing/Stream/DefaultImplementations/Implementation/ZeroInitializer.cpp
  Code/Engine/Foundation/DataProcessing/Stream/Implementation/ProcessingStreamGroup.cpp
  Code/Engine/Foundation/DataProcessing/Stream/Implementation/ProcessingStreamIterator_inl.h
  Code/Engine/Foundation/IO/Archive/Implementation/ArchiveBuilder.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/ArchiveUtils.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/DataDirTypeArchive.cpp
  Code/Engine/Foundation/IO/FileSystem/Implementation/DataDirTypeFolder.cpp
  Code/Engine/Foundation/IO/Implementation/DependencyFile.cpp
  Code/Engine/Foundation/IO/Implementation/Posix/MemoryMappedFile_posix.h
  Code/Engine/Foundation/IO/Implementation/Win/MemoryMappedFile_win.h
  Code/Engine/Foundation/Logging/Implementation/Log.cpp
  Code/Engine/Foundation/Memory/Implementation/BlockStorage_inl.h
  Code/Engine/Foundation/Memory/Implementation/LargeBlockAllocator_inl.h
  Code/Engine/Foundation/Memory/Implementation/MemoryUtils_inl.h
  Code/Engine/Foundation/Memory/MemoryUtils.h
  Code/Engine/Foundation/Memory/Policies/Win/GuardedAllocation_win.h
  Code/Engine/Foundation/Strings/Implementation/FormatString.cpp
  Code/Engine/Foundation/Strings/Implementation/StringIterator.h
  Code/Engine/Foundation/Strings/Implementation/StringUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/snprintf.cpp
  Code/Engine/Foundation/System/Implementation/NoImpl/StackTracer_NoImpl.h
  Code/Engine/Foundation/System/Implementation/Posix/StackTracer_posix.h
  Code/Engine/Foundation/Threading/AtomicInteger.h
  Code/Engine/Foundation/Threading/AtomicUtils.h
  Code/Engine/Foundation/Threading/Implementation/Posix/AtomicUtils_posix.h
  Code/Engine/Foundation/Threading/Implementation/Posix/ConditionVariable_posix.h
  Code/Engine/Foundation/Threading/Implementation/Win/AtomicUtils_win.h
  Code/Engine/Foundation/Time/Implementation/Posix/Timestamp_posix.h
  Code/Engine/Foundation/Types/Implementation/VariantTypeDeduction_inl.h
  Code/Engine/Foundation/Types/TypeTraits.h
  Code/Engine/Foundation/Types/VariantType.h
  Code/Tools/Inspector/DataTransferWidget.cpp
  Code/UnitTests/FoundationTest/Threading/ThreadTest.cpp
Labels: code quality
