Repository ezEngine/ezEngine, pull requests merged in 2023-12, with the labels that each got.

#1120 Various smaller fixes
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserView.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/NonUniformBoxGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/SnapProvider.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/TranslateGizmo.cpp
  Code/Editor/EditorFramework/InputContexts/Implementation/SelectionContext.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/Util/MeshImportUtils.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.cpp
  Code/Engine/Core/Input/DeviceTypes/DeviceTypes.cpp
  Code/Engine/Foundation/Basics/Platform/Linux/PlatformFeatures_Linux.h
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionVMOperations.h
  Code/Engine/Foundation/CodeUtils/Implementation/Tokenizer.cpp
  Code/Engine/Foundation/IO/Implementation/Posix/DirectoryWatcher_posix.h
  Code/Engine/Foundation/Logging/Implementation/Log.cpp
  Code/Engine/Foundation/Math/Implementation/Quat_inl.h
  Code/Engine/Foundation/Math/Implementation/Transform_inl.h
  Code/Engine/Foundation/Math/Implementation/Vec4_inl.h
  Code/Engine/Foundation/Math/Quat.h
  Code/Engine/Foundation/Math/Vec3.h
  Code/Engine/Foundation/Math/Vec4.h
  Code/Engine/Foundation/Types/Implementation/TagSet_inl.h
  Code/Engine/GameEngine/Animation/Implementation/RotorComponent.cpp
  Code/Engine/RendererCore/Debug/Implementation/DebugRenderer.cpp
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/Implementation/HeadBoneComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Physics/Implementation/ClothSheetComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRopeComponent.cpp
  Code/EnginePlugins/KrautPlugin/Components/KrautTreeComponent.cpp
  Code/EnginePlugins/ParticlePlugin/Components/ParticleComponent.cpp
  Code/EnginePlugins/RecastPlugin/Components/RecastAgentComponent.cpp
  Code/Tools/StaticLinkUtil/StaticLinkUtil.cpp
  Code/UnitTests/FoundationTest/Basics/Types/IdTest.cpp
  Code/UnitTests/FoundationTest/Math/QuatTest.cpp
Labels: code quality

#1126 More fixes
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFilter.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/ExposedParametersPropertyWidget.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/Dialogs/JoltProjectSettingsDlg.cpp
  Code/Engine/GameEngine/Gameplay/GrabbableItemComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/GrabbableItemComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltDynamicActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/JoltDynamicActorComponent.h
  Code/EnginePlugins/JoltPlugin/Constraints/Implementation/JoltConstraintComponent.cpp
  Code/EnginePlugins/JoltPlugin/Constraints/Implementation/JoltGrabObjectComponent.cpp
  Code/EnginePlugins/JoltPlugin/Constraints/JoltGrabObjectComponent.h
  Code/EnginePlugins/RmlUiPlugin/Implementation/RmlUiConversionUtils.cpp
Labels: bug, new feature

#1127 Fixed that GameObject references couldn't be exposed as properties anymore
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.cpp
  Code/UnitTests/GameEngineTest/Basics/Basics.cpp
  Code/UnitTests/GameEngineTest/Basics/Basics.h
  Data/Tools/ezEditor/Localization/ValidateLinks.ps1
  Data/Tools/ezEditor/Localization/en/RecastPlugin.txt
  Data/Tools/ezEditor/Localization/en/SceneAsset.txt
  Data/Tools/ezEditor/Localization/en/StateMachineAsset.txt
  Data/UnitTests/GameEngineTest/Basics/Beam.ezPrefab
  Data/UnitTests/GameEngineTest/Basics/BeamWithBeam.ezPrefab
  Data/UnitTests/GameEngineTest/Basics/Editor/PluginSelection.ddl
  Data/UnitTests/GameEngineTest/Basics/GoReferences.ezScene
  Data/UnitTests/GameEngineTest/Basics/Rope.ezPrefab
  Data/UnitTests/GameEngineTest/Basics/RuntimeConfigs/Plugins.ddl
  Data/UnitTests/GameEngineTest/Images_Reference/Basic_Engine_Tests_GameObject_References_000.png
  Data/UnitTests/GameEngineTest/SharedAssets/Materials/FullbrightWhite.ezMaterialAsset
Labels: bug

#1132 Prevent mouse-wheel from changing property values
  Code/Editor/EditorFramework/PropertyGrid/Implementation/DynamicEnumPropertyWidget.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/DynamicStringEnumPropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
Labels: improvement
