Repository ezEngine/ezEngine, pull requests merged in 2023-06, with the labels that each got.

#972 Improved ragdolls
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAssetWindow.cpp
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/Engine/Foundation/Math/Implementation/Math.cpp
  Code/Engine/Foundation/Math/Math.h
  Code/Engine/GameEngine/Animation/Skeletal/AnimatedMeshComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/AnimationControllerComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AnimatedMeshComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AnimationControllerComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/SimpleAnimationComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/SimpleAnimationComponent.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraph.cpp
  Code/Engine/RendererCore/AnimationSystem/Declarations.h
  Code/Engine/RendererCore/AnimationSystem/EditableSkeleton.h
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationPose.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/EditableSkeleton.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/Skeleton.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonBuilder.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonComponent.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonResource.cpp
  Code/Engine/RendererCore/AnimationSystem/Skeleton.h
  Code/Engine/RendererCore/AnimationSystem/SkeletonBuilder.h
  Code/Engine/RendererCore/AnimationSystem/SkeletonResource.h
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/Implementation/AreaDamageComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltBoneColliderComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRagdollComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/JoltRagdollComponent.h
  Code/EnginePlugins/JoltPlugin/System/JoltQueries.cpp
  Code/EnginePlugins/PhysXPlugin/Components/Implementation/PxBoneColliderComponent.cpp
  Code/EnginePlugins/PhysXPlugin/Components/Implementation/PxRagdollComponent.cpp
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpMeshImport.cpp
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/ImporterAssimp.cpp
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/ImporterAssimp.h
  Data/Samples/Testing Chambers/Animations/Pete/Pete.ezSkeletonAsset
  Data/Samples/Testing Chambers/Animations/Pete/PeteRagdoll.ezPrefab
  Data/Samples/Testing Chambers/Animations/Pete/PeteRunningRagdoll.ezPrefab
  Data/Samples/Testing Chambers/Animations/Pete/Wave.ezAnimationClipAsset
  Data/Samples/Testing Chambers/Animations/ShootingStar2.ts
  Data/Samples/Testing Chambers/Assets/BreakableCube.blend
  Data/Samples/Testing Chambers/Assets/BreakableCube.glb
  Data/Samples/Testing Chambers/Objects/Breakable/BreakableCube.ezAnimatedMeshAsset
  Data/Samples/Testing Chambers/Objects/Breakable/BreakableCube.ezSkeletonAsset
  Data/Samples/Testing Chambers/Prefabs/Player.ezPrefab
  Data/Samples/Testing Chambers/Scenes/Ragdolls.ezScene
  Data/UnitTests/GameEngineTest/Animations/Scenes/AnimController.ezScene
  Data/UnitTests/GameEngineTest/Images_Reference/Animations_Tests_Skeletal_000.png
Labels: new feature, improvement

#996 Added animation controller nodes
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationControllerAsset/AnimationControllerAsset.cpp
  Code/Engine/Foundation/Strings/Implementation/TranslationLookup.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BoneWeightsAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/PlaySequenceAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/BoneWeightsSwitchAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/BoneWeightsSwitchAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/LerpPosesAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/LerpPosesAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/PoseResultAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/PoseResultAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleFrameAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleFrameAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SelectPoseAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SelectPoseAnimNode.h
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/Pin.cpp
  Data/Samples/Testing Chambers/Animations/Pete/test.ezAnimationControllerAsset
  Data/Tools/ezEditor/Localization/en/AnimationControllerAsset.txt
Labels: new feature

#997 Editor fixes
  Code/Editor/EditorFramework/Assets/Implementation/AssetCurator.cpp
  Code/Editor/EditorFramework/Object/Implementation/ObjectPropertyPath.cpp
  Code/Editor/EditorFramework/Object/ObjectPropertyPath.h
  Code/EditorPlugins/Assets/EditorPluginAssets/PropertyAnimAsset/PropertyAnimAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/PropertyAnimAsset/PropertyAnimAsset.h
  Code/Engine/Foundation/ezEngine.natvis
  Code/UnitTests/EditorTest/SceneDocument/SceneDocumentTest.cpp
  Code/UnitTests/EditorTest/SceneDocument/SceneDocumentTest.h
  Code/UnitTests/EditorTest/TestClass/TestClass.cpp
  Code/UnitTests/EditorTest/TestClass/TestClass.h
Labels: improvement

#999 Improvements to how the AnimationGraph is built
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationControllerAsset/AnimationControllerAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationControllerAsset/AnimationControllerAsset.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimGraph.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimGraphNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimGraphPins.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimGraphResource.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/PoseResultAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/PoseResultAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraph.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraphPins.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraphResource.cpp
  Code/Samples/RtsGamePlugin/GameMode/EditLevelMode/EditLevelMode.cpp
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllEnums.ts
Labels: improvement
