Repository ezEngine/ezEngine, pull requests merged in 2023-05, with the labels that each got.

#931 Fixed #845: Improved Jolt rope and Fake rope
  Code/EditorPlugins/Jolt/EditorPluginJolt/EditorPluginJolt.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Patches/GameComponentsPluginPatches.cpp
  Code/Engine/Foundation/Math/Implementation/Quat_inl.h
  Code/Engine/Foundation/Math/Quat.h
  Code/Engine/GameEngine/Physics/Implementation/RopeSimulator.cpp
  Code/Engine/GameEngine/Physics/RopeSimulator.h
  Code/EnginePlugins/GameComponentsPlugin/Physics/FakeRopeComponent.h
  Code/EnginePlugins/GameComponentsPlugin/Physics/Implementation/FakeRopeComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRopeComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/JoltRopeComponent.h
  Code/UnitTests/FoundationTest/Math/QuatTest.cpp
  Data/Samples/Testing Chambers/Objects/Barrel2.ezPrefab
Labels: new feature, improvement

#933 Prevent Jolt crash when a joined physics actor is deleted
  Code/Engine/Core/Messages/SetColorMessage.h
  Code/Engine/Core/Scripting/DuktapeHelper.h
  Code/Engine/Core/World/Declarations.h
  Code/Engine/Foundation/Memory/MemoryTracker.h
  Code/Engine/Foundation/System/Process.h
  Code/Engine/Foundation/Types/Bitflags.h
  Code/Engine/RendererCore/RenderContext/Implementation/RenderContextStructs.h
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltDynamicActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/JoltDynamicActorComponent.h
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRopeComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/JoltRopeComponent.h
  Code/EnginePlugins/JoltPlugin/Constraints/Implementation/JoltConstraintComponent.cpp
  Code/EnginePlugins/JoltPlugin/Constraints/JoltConstraintComponent.h
  Code/EnginePlugins/JoltPlugin/Declarations.h
  Code/Tools/Libs/GuiFoundation/Action/Action.h
  Code/Tools/Libs/GuiFoundation/Action/StandardMenus.h
  Code/UnitTests/FoundationTest/Basics/Types/BitflagsTest.cpp
  Code/UnitTests/FoundationTest/Basics/Types/IdTest.cpp
Labels: improvement

#938 Fixed fallout from prefab improvements
  Code/EditorPlugins/Assets/EditorPluginAssets/CollectionAsset/CollectionAsset.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/Engine/Core/Prefabs/Implementation/PrefabReferenceComponent.cpp
  Code/Engine/Core/Prefabs/Implementation/PrefabResource.cpp
  Code/UnitTests/EditorTest/SceneDocument/SceneDocumentTest.cpp
Labels: bug

#939 Fixes and improvements for the C++ workflow
  Code/Editor/EditorFramework/Actions/Implementation/ProjectActions.cpp
  Code/Editor/EditorFramework/CodeGen/CppProject.cpp
  Code/Editor/EditorFramework/CodeGen/CppProject.h
  Code/Editor/EditorFramework/EditorApp/Configuration/EditorPlugins.cpp
  Code/Editor/EditorFramework/EditorApp/Configuration/EnginePlugins.cpp
  Code/Editor/EditorFramework/EditorApp/EditorApp.moc.h
  Code/Editor/EditorFramework/EditorApp/Projects.cpp
  Code/Engine/Foundation/Application/Config/Implementation/PluginConfig.cpp
  Code/Engine/Foundation/IO/FileSystem/DeferredFileWriter.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/DeferredFileWriter.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/CMakeLists.txt
Labels: improvement

#940 C++ plugin workflow improvements
  Code/Editor/EditorFramework/CodeGen/CppProject.cpp
  Code/Editor/EditorFramework/CodeGen/CppProject.h
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.cpp
  Code/Editor/EditorFramework/Dialogs/ExportProjectDlg.cpp
  Code/Editor/EditorFramework/Dialogs/ExportProjectDlg.ui
  Code/Editor/EditorFramework/EditorApp/Projects.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SceneActions.cpp
  Code/Engine/Foundation/IO/FileSystem/DeferredFileWriter.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/DeferredFileWriter.cpp
  Code/Engine/Foundation/IO/Implementation/Posix/OSFile_posix.h
  Code/Engine/Foundation/IO/Implementation/Win/OSFile_win.h
  Code/Engine/Foundation/IO/OSFile.h
  Code/Engine/Foundation/System/Implementation/Win/StackTracer_win.h
  Code/UnitTests/FoundationTest/IO/OSFileTest.cpp
Labels: improvement

#942 Added unit test for Euler angle conversion
  Code/Engine/Foundation/Math/Implementation/Quat_inl.h
  Code/Engine/Foundation/Math/Quat.h
  Code/UnitTests/FoundationTest/Math/QuatTest.cpp
Labels: code quality

#943 Fix some issues found by PVS-Studio in Foundation and Core
  Code/Engine/Core/Console/ConsoleFunction.h
  Code/Engine/Core/ResourceManager/Implementation/ResourceLoading.cpp
  Code/Engine/Core/System/Implementation/Win/Window_win32.inl
  Code/Engine/Core/World/WorldModule.h
  Code/Engine/Foundation/Basics/Platform/Common.h
  Code/Engine/Foundation/Communication/Implementation/IpcChannelEnet.cpp
  Code/Engine/Foundation/Configuration/CVar.h
  Code/Engine/Foundation/Configuration/Implementation/CVar.cpp
  Code/Engine/Foundation/Containers/Implementation/DynamicArray_inl.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/FileSystem.cpp
  Code/Engine/Foundation/IO/Implementation/OpenDdlWriter.cpp
  Code/Engine/Foundation/IO/OpenDdlWriter.h
  Code/Engine/Foundation/Math/Implementation/BoundingSphere_inl.h
  Code/Engine/Foundation/Math/Implementation/Transform_inl.h
  Code/Engine/Foundation/Memory/Implementation/EndianHelper.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.h
  Code/Engine/Foundation/SimdMath/Implementation/SSE/SSETypes_inl.h
  Code/Engine/Foundation/System/Implementation/Win/Screen_win32.inl
  Code/Engine/Foundation/System/Implementation/Win/StackTracer_win.h
  Code/Engine/Foundation/Threading/Implementation/TaskSystemUtils.cpp
  Code/Engine/Foundation/Threading/Implementation/TaskWorkerThread.h
  Code/Engine/Foundation/Types/Implementation/Tag_inl.h
Labels: code quality

#958 Fixed #946: Release pipeline now deletes "Build" folders
  .github/workflows/build-release-package.yml
  Code/Engine/Core/WorldSerializer/Implementation/WorldReader.cpp
Labels: maintenance

#962 Improvements for animations and physics objects
  Code/Engine/Core/World/GameObject.h
  Code/Engine/Core/World/Implementation/GameObject.cpp
  Code/Engine/Core/World/Implementation/SpatialSystem_RegularGrid.cpp
  Code/Engine/Core/World/SpatialData.h
  Code/Engine/Core/World/SpatialSystem.h
  Code/Engine/Core/World/SpatialSystem_RegularGrid.h
  Code/Engine/Foundation/Strings/Implementation/TranslationLookup.cpp
  Code/Engine/GameEngine/Animation/Skeletal/AnimatedMeshComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AnimatedMeshComponent.cpp
  Code/Engine/RendererCore/Pipeline/Implementation/RenderPipeline.cpp
  Code/EnginePlugins/GameComponentsPlugin/Physics/Implementation/FakeRopeComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltDynamicActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltCollisionFiltering.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltCollisionFiltering.h
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
  Code/UnitTests/CoreTest/World/SpatialSystemTest.cpp
Labels: improvement

#965 More ezStringView usage in core infrastructure
  Code/EditorPlugins/Assets/EditorPluginAssets/VisualShader/VisualShaderTypeRegistry.cpp
  Code/EditorPlugins/Fileserve/EditorPluginFileserve/FileserveUI/FileserveWidget.cpp
  Code/Engine/Core/Scripting/Duktape/DuktapeHelper.cpp
  Code/Engine/Core/Scripting/ScriptClasses/Implementation/ScriptExtensionClass_Log.cpp
  Code/Engine/Foundation/Algorithm/Implementation/HashingUtils_inl.h
  Code/Engine/Foundation/Basics/Assert.cpp
  Code/Engine/Foundation/IO/Implementation/JSONParser.cpp
  Code/Engine/Foundation/IO/Implementation/JSONReader.cpp
  Code/Engine/Foundation/IO/Implementation/JSONWriter.cpp
  Code/Engine/Foundation/IO/Implementation/OpenDdlParser.cpp
  Code/Engine/Foundation/IO/Implementation/OpenDdlReader.cpp
  Code/Engine/Foundation/IO/Implementation/OpenDdlUtils.cpp
  Code/Engine/Foundation/IO/Implementation/OpenDdlWriter.cpp
  Code/Engine/Foundation/IO/Implementation/StandardJSONWriter.cpp
  Code/Engine/Foundation/IO/JSONParser.h
  Code/Engine/Foundation/IO/JSONReader.h
  Code/Engine/Foundation/IO/JSONWriter.h
  Code/Engine/Foundation/IO/OpenDdlParser.h
  Code/Engine/Foundation/IO/OpenDdlReader.h
  Code/Engine/Foundation/IO/OpenDdlUtils.h
  Code/Engine/Foundation/IO/OpenDdlWriter.h
  Code/Engine/Foundation/Logging/Implementation/Log.cpp
  Code/Engine/Foundation/Logging/Log.h
  Code/Engine/Foundation/Reflection/Implementation/RTTI.cpp
  Code/Engine/Foundation/Reflection/Implementation/RTTI.h
  Code/Engine/Foundation/Serialization/AbstractObjectGraph.h
  Code/Engine/Foundation/Serialization/Implementation/AbstractObjectGraph.cpp
  Code/Engine/Foundation/Serialization/Implementation/DdlSerializer.cpp
  Code/Engine/Foundation/Strings/FormatString.h
  Code/Engine/Foundation/Strings/Implementation/FormatString.cpp
  Code/Engine/Foundation/Strings/Implementation/FormatStringImpl.h
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Samples/SampleGamePlugin/Interface/SingletonInterfaceImpl.cpp
  Code/Tools/Libs/GuiFoundation/DocumentWindow/DocumentWindow.cpp
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/MessageBoxes.cpp
  Code/Tools/Libs/GuiFoundation/Widgets/EventTrackEditData.h
  Code/Tools/Libs/GuiFoundation/Widgets/Implementation/EventTrackEditData.cpp
  Code/Tools/Libs/ToolsFoundation/Document/Implementation/Declarations.h
  Code/Tools/Libs/ToolsFoundation/Document/Implementation/Document.cpp
  Code/Tools/Libs/ToolsFoundation/Object/Implementation/ObjectAccessorBase.cpp
  Code/Tools/Libs/ToolsFoundation/Object/Implementation/ObjectCommandAccessor.cpp
  Code/Tools/Libs/ToolsFoundation/Object/Implementation/ObjectProxyAccessor.cpp
  Code/Tools/Libs/ToolsFoundation/Object/ObjectAccessorBase.h
  Code/Tools/Libs/ToolsFoundation/Object/ObjectCommandAccessor.h
  Code/Tools/Libs/ToolsFoundation/Object/ObjectProxyAccessor.h
  Code/UnitTests/FoundationTest/IO/DdlReaderTest.cpp
  Code/UnitTests/FoundationTest/IO/JSONParserTest.cpp
  Code/UnitTests/FoundationTest/IO/JSONReaderTest.cpp
  Code/UnitTests/FoundationTest/Strings/FormatStringTest.cpp
  Code/UnitTests/TestFramework/Framework/TestFramework.cpp
  Code/UnitTests/TestFramework/Framework/TestFramework.h
Labels: code quality
