Repository ezEngine/ezEngine, pull requests merged in 2023-10, with the labels that each got.

#1079 Added support for fetching sample projects from other git repos
  .editorconfig
  Code/Editor/EditorFramework/Dialogs/DashboardDlg.cpp
  Code/Editor/EditorFramework/EditorApp/EditorApp.cpp
  Code/Editor/EditorFramework/EditorApp/EditorApp.moc.h
  Code/Editor/EditorFramework/EditorApp/Projects.cpp
  Code/Editor/EditorFramework/EditorApp/Startup.cpp
  Code/Engine/Foundation/IO/Implementation/OSFile.cpp
  Code/Engine/Foundation/IO/Implementation/Posix/OSFile_posix.h
  Code/Engine/Foundation/IO/Implementation/Win/OSFile_win.h
  Code/Engine/Foundation/IO/OSFile.h
  Code/Tools/Libs/GuiFoundation/UIServices/UIServices.moc.h
  Code/Tools/Libs/ToolsFoundation/Application/ApplicationServices.h
  Code/Tools/Libs/ToolsFoundation/Application/Implementation/ApplicationServices.cpp
  Data/Samples/Monster Attack/Thumbnail.jpg
  Data/Samples/Monster Attack/ezRemoteProject
Labels: new feature

#1086 Fixed #1083: Improve performance of the SVG icon coloring
  .clang-format
  .github/workflows/clang-format.yml
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/EditorApp/Qt.cpp
  Code/Editor/EditorFramework/EditorApp/Startup.cpp
  Code/Editor/EditorFramework/QtResources/Icons/AllAssets.svg
  Code/Editor/EditorFramework/QtResources/resources.qrc
  Code/EditorPlugins/Assets/EditorPluginAssets/QtResources/resources.qrc
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/UIServices.cpp
  Data/Samples/SampleGame/TypeScript/ez.ts
  Data/Samples/SampleGame/TypeScript/ez/AllComponents.ts
  Data/Samples/SampleGame/TypeScript/ez/AllEnums.ts
  Data/Samples/SampleGame/TypeScript/ez/AllMessages.ts
Labels: improvement

#1087 Fixed #1081: Auto transform collection assets
  Code/EditorPlugins/Assets/EditorPluginAssets/CollectionAsset/CollectionAssetManager.cpp
Labels: improvement

#1085 Removed VS2019 support
  Code/BuildSystem/AzurePipelines/Android-x86.yml
  Code/BuildSystem/AzurePipelines/Linux-x64.yml
  Code/BuildSystem/AzurePipelines/Windows-x64.yml
  Code/BuildSystem/AzurePipelines/WindowsUWP-x64.yml
  Code/BuildSystem/CMake/CMakeUtils/ezUtilsTargetCS.cmake
  Code/Editor/EditorFramework/CodeGen/CppProject.cpp
  Code/Editor/EditorFramework/CodeGen/CppSettings.cpp
  Code/Editor/EditorFramework/CodeGen/CppSettings.h
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.cpp
  Code/UnitTests/EditorTest/GenerateCompile/GenerateCompile.cpp
  Code/UnitTests/EditorTest/Project/Project.cpp
  Code/UnitTests/RemoteTestHarness/TestUwp.cs
  GenerateWin64vs2019.bat
  RunCMake.ps1
  Utilities/Scripts/common-functions.ps1
  gitClean.txt
Labels: maintenance

#1088 Fixed #636: Updated Imgui to version 1.89.9
  Code/Engine/GameEngine/DearImgui/Implementation/DearImgui.cpp
  Code/ThirdParty/Imgui/LICENSE.txt
  Code/ThirdParty/Imgui/cgmanifest.json
  Code/ThirdParty/Imgui/imconfig.h
  Code/ThirdParty/Imgui/imgui.cpp
  Code/ThirdParty/Imgui/imgui.h
  Code/ThirdParty/Imgui/imgui_demo.cpp
  Code/ThirdParty/Imgui/imgui_draw.cpp
  Code/ThirdParty/Imgui/imgui_internal.h
  Code/ThirdParty/Imgui/imgui_tables.cpp
  Code/ThirdParty/Imgui/imgui_widgets.cpp
  Code/ThirdParty/Imgui/imstb_rectpack.h
  Code/ThirdParty/Imgui/imstb_textedit.h
  Code/ThirdParty/Imgui/imstb_truetype.h
Labels: maintenance

#1089 Fixed #1084: ezInspector usability issues
  Code/Tools/Inspector/GlobalEventsWidget.cpp
  Code/Tools/Inspector/InputWidget.cpp
  Code/Tools/Inspector/MainWindow.cpp
  Code/Tools/Inspector/PluginsWidget.cpp
  Code/Tools/Inspector/SubsystemsWidget.cpp
  Code/Tools/Inspector/icon1.ico
Labels: bug, improvement

#1090 Various fixes
  Code/Engine/Core/Scripting/Implementation/ScriptClassResource.cpp
  Code/Engine/Core/Scripting/Implementation/ScriptComponent.cpp
  Code/Engine/Core/Scripting/Implementation/ScriptRTTI.cpp
  Code/Engine/Core/Scripting/Implementation/ScriptWorldModule.cpp
  Code/Engine/Core/Scripting/ScriptComponent.h
  Code/Engine/Core/Scripting/ScriptRTTI.h
  Code/Engine/Core/Scripting/ScriptWorldModule.h
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/Core/World/Implementation/WorldData.cpp
  Code/Engine/Core/World/World.h
  Code/Engine/GameEngine/Gameplay/BlackboardComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/BlackboardComponent.cpp
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachineState_Script.cpp
  Code/Engine/RendererCore/GPUResourcePool/Implementation/GPUResourcePool.cpp
  Code/EnginePlugins/RmlUiPlugin/Components/Implementation/RmlUiCanvas2DComponent.cpp
  Code/EnginePlugins/VisualScriptPlugin/Resources/VisualScriptClassResource.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptCoroutine.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptInstance.cpp
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
Labels: improvement
