Repository ezEngine/ezEngine, pull requests merged in 2023-09, with the labels that each got.

#1034 Added dynamic bitflags and improved bitflag UI
  Code/Editor/EditorFramework/PropertyGrid/DynamicBitflagsPropertyWidget.moc.h
  Code/Editor/EditorFramework/PropertyGrid/Implementation/DynamicBitflagsPropertyWidget.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.moc.h
  Code/Tools/Libs/GuiFoundation/UIServices/DynamicBitflags.h
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/DynamicBitflags.cpp
Labels: new feature, improvement

#1036 Added different types of following modes for FollowPathComponent
  Code/Engine/GameEngine/Animation/FollowPathComponent.h
  Code/Engine/GameEngine/Animation/Implementation/FollowPathComponent.cpp
Labels: improvement

#1038 Recast Improvements
  Code/Editor/EditorFramework/PropertyGrid/Implementation/DynamicStringEnumPropertyWidget.cpp
  Code/Engine/Foundation/Math/Angle.h
  Code/Engine/Foundation/Math/Implementation/Rect_inl.h
  Code/Engine/Foundation/Math/Rect.h
  Code/EnginePlugins/RecastPlugin/Components/RecastAgentComponent.cpp
  Code/ThirdParty/Recast/Detour/Include/DetourNavMeshQuery.h
  Code/ThirdParty/Recast/Detour/Source/DetourNavMeshQuery.cpp
  Code/ThirdParty/Recast/DetourCrowd/Include/DetourPathCorridor.h
  Code/ThirdParty/Recast/DetourCrowd/Source/DetourCrowd.cpp
  Code/ThirdParty/Recast/DetourCrowd/Source/DetourPathCorridor.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastContour.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastRegion.cpp
  Code/Tools/Libs/GuiFoundation/UIServices/DynamicEnums.h
  Code/Tools/Libs/GuiFoundation/UIServices/DynamicStringEnum.h
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/DynamicEnums.cpp
Labels: improvement

#1041 Scripting and reflection fixes
  Code/Editor/EditorEngineProcess/EngineProcGameApp.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationGraphAsset/AnimationGraphAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/RenderPipelineAsset/RenderPipelineAsset.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptNodeRegistry.cpp
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/Core/World/World.h
  Code/Engine/Foundation/Communication/Event.h
  Code/Engine/Foundation/Reflection/Implementation/ReflectionUtils.cpp
  Code/Engine/Foundation/Reflection/ReflectionUtils.h
  Code/Engine/Foundation/Time/Clock.h
  Code/Engine/Foundation/Time/Implementation/Clock.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/Connection.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/AddSubElementButton.cpp
  Code/Tools/Libs/ToolsFoundation/Reflection/Implementation/ReflectedType.cpp
Labels: improvement

#1043 Added functionality for runtime navmesh generation
  Code/EditorPlugins/AI/CMakeLists.txt
  Code/EditorPlugins/AI/EditorPluginAi/Actions/AiActions.cpp
  Code/EditorPlugins/AI/EditorPluginAi/Actions/AiActions.h
  Code/EditorPlugins/AI/EditorPluginAi/CMakeLists.txt
  Code/EditorPlugins/AI/EditorPluginAi/Dialogs/AiProjectSettingsDlg.cpp
  Code/EditorPlugins/AI/EditorPluginAi/Dialogs/AiProjectSettingsDlg.moc.h
  Code/EditorPlugins/AI/EditorPluginAi/Dialogs/AiProjectSettingsDlg.ui
  Code/EditorPlugins/AI/EditorPluginAi/EditorPluginAi.cpp
  Code/EditorPlugins/AI/EditorPluginAi/EditorPluginAiDLL.h
  Code/EditorPlugins/AI/EditorPluginAi/EditorPluginAiPCH.cpp
  Code/EditorPlugins/AI/EditorPluginAi/EditorPluginAiPCH.h
  Code/EditorPlugins/AI/EditorPluginAi/QtResources/ezAiNavMeshPathTestComponent.svg
  Code/EditorPlugins/AI/EditorPluginAi/QtResources/ezAiPlugin.svg
  Code/EditorPlugins/AI/EditorPluginAi/QtResources/resources.qrc
  Code/EditorPlugins/AI/EditorPluginAi/finalize.cmake
  Code/EditorPlugins/Jolt/EditorPluginJolt/Actions/JoltActions.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/Dialogs/JoltProjectSettingsDlg.ui
  Code/EditorPlugins/Jolt/EditorPluginJolt/QtResources/JoltPlugin.svg
  Code/EditorPlugins/Jolt/EditorPluginJolt/QtResources/resources.qrc
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/Engine/Core/Physics/Implementation/SurfaceResourceDescriptor.cpp
  Code/Engine/Core/Physics/SurfaceResourceDescriptor.h
  Code/Engine/Foundation/Time/Implementation/Timestamp.cpp
  Code/EnginePlugins/AiPlugin/AI.ezPluginBundle
  Code/EnginePlugins/AiPlugin/AiPluginDLL.h
  Code/EnginePlugins/AiPlugin/AiPluginPCH.cpp
  Code/EnginePlugins/AiPlugin/AiPluginPCH.h
  Code/EnginePlugins/AiPlugin/CMakeLists.txt
  Code/EnginePlugins/AiPlugin/Components/NavMeshPathTestComponent.cpp
  Code/EnginePlugins/AiPlugin/Components/NavMeshPathTestComponent.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/DebugDraw.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMesh.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshGeneration.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshGeneration.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshWorldModule.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/Navigation.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavigationConfig.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/Steering.cpp
  Code/EnginePlugins/AiPlugin/Navigation/NavMesh.h
  Code/EnginePlugins/AiPlugin/Navigation/NavMeshWorldModule.h
  Code/EnginePlugins/AiPlugin/Navigation/Navigation.h
  Code/EnginePlugins/AiPlugin/Navigation/NavigationConfig.h
  Code/EnginePlugins/AiPlugin/Navigation/Steering.h
  Code/EnginePlugins/AiPlugin/Utils/RcMath.cpp
  Code/EnginePlugins/AiPlugin/Utils/RcMath.h
  Code/EnginePlugins/AiPlugin/finalize.cmake
  Code/EnginePlugins/JoltPlugin/System/JoltQueries.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
  Code/EnginePlugins/RecastPlugin/NavMeshBuilder/NavMeshBuilder.cpp
  Code/EnginePlugins/RecastPlugin/NavMeshBuilder/NavMeshBuilder.h
  Data/Base/Editor/ShapeIcons/ezAiNavMeshPathTestComponent.dds
  Data/Base/Editor/ShapeIcons/ezAiNavMeshPathTestComponent.png
  Data/Tools/ezEditor/Localization/en/AiPlugin.txt
  gitClean.txt
Labels: new feature

#1045 Remove a use of regex compare on path in CMake
  Code/BuildSystem/CMake/ezUtils.cmake
Labels: maintenance

#1049 Less regex compares on path in CMake, v2
  Code/BuildSystem/CMake/ezUtils.cmake
Labels: code quality

#1050 Fixed cpp project generation and pacman sample
  Data/Samples/PacMan/CppSource/CMakeLists.txt
  Data/Samples/PacMan/CppSource/PacManPlugin/Components/GhostComponent.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/Components/PacManComponent.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CMakeLists.txt
Labels: maintenance

#1052 Various improvements
  Code/Engine/Core/Collection/CollectionComponent.h
  Code/Engine/Core/Collection/CollectionResource.h
  Code/Engine/Core/Collection/Implementation/CollectionComponent.cpp
  Code/Engine/Core/Collection/Implementation/CollectionResource.cpp
  Code/Engine/GameEngine/Animation/Implementation/ResetTransformComponent.cpp
  Code/Engine/GameEngine/Animation/Implementation/RotorComponent.cpp
  Code/Engine/GameEngine/Animation/Implementation/SliderComponent.cpp
  Code/Engine/GameEngine/Animation/Implementation/TransformComponent.cpp
  Code/Engine/GameEngine/Animation/ResetTransformComponent.h
  Code/Engine/GameEngine/Animation/RotorComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/AnimatedMeshComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AnimatedMeshComponent.cpp
  Code/Engine/GameEngine/Animation/SliderComponent.h
  Code/Engine/GameEngine/Animation/TransformComponent.h
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachine.cpp
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachineBuiltins.cpp
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachineComponent.cpp
  Code/Engine/GameEngine/StateMachine/StateMachine.h
  Code/Engine/GameEngine/StateMachine/StateMachineBuiltins.h
  Code/Engine/GameEngine/StateMachine/StateMachineComponent.h
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/Implementation/ProjectileComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/ProjectileComponent.h
  Data/Tools/ezEditor/Localization/en/StateMachineAsset.txt
Labels: new feature, improvement

#1042 MSFT contributions September 2023
  Code/Engine/Core/System/Implementation/Win/Window_win32.inl
  Code/Engine/Foundation/IO/Implementation/JSONParser.cpp
  Code/Engine/Foundation/IO/Implementation/JSONReader.cpp
  Code/Engine/Foundation/IO/JSONReader.h
  Code/Engine/Foundation/System/Implementation/Win/Process_win.h
  Code/Engine/Foundation/System/Process.h
  Code/Engine/Foundation/Threading/Implementation/TaskSystemTasks.cpp
  Code/UnitTests/CoreTest/TexConv/TexConvTest.cpp
  Code/UnitTests/EditorTest/TestClass/TestClass.cpp
  Code/UnitTests/EditorTest/TestClass/TestClass.h
  Code/UnitTests/FoundationTest/Containers/DynamicArrayTest.cpp
  Code/UnitTests/FoundationTest/Image/ImageConversionTest.cpp
  Code/UnitTests/GameEngineTest/TestClass/TestClass.cpp
  Code/UnitTests/GameEngineTest/TestClass/TestClass.h
  Code/UnitTests/RendererTest/Basics/Readback.cpp
  Code/UnitTests/RendererTest/Basics/Readback.h
  Code/UnitTests/RendererTest/TestClass/TestClass.cpp
  Code/UnitTests/RendererTest/TestClass/TestClass.h
  Code/UnitTests/TestFramework/Framework/Declarations.h
  Code/UnitTests/TestFramework/Framework/Qt/qtTestFramework.cpp
  Code/UnitTests/TestFramework/Framework/Qt/qtTestFramework.h
  Code/UnitTests/TestFramework/Framework/Qt/qtTestGUI.cpp
  Code/UnitTests/TestFramework/Framework/Qt/qtTestModel.cpp
  Code/UnitTests/TestFramework/Framework/Qt/qtTestModel.h
  Code/UnitTests/TestFramework/Framework/TestBaseClass.cpp
  Code/UnitTests/TestFramework/Framework/TestBaseClass.h
  Code/UnitTests/TestFramework/Framework/TestFramework.cpp
  Code/UnitTests/TestFramework/Framework/TestFramework.h
  Code/UnitTests/TestFramework/Framework/TestResults.cpp
  Code/UnitTests/TestFramework/Framework/TestResults.h
Labels: improvement

#1057 Fixed #1055: Prefabs were excluded from exported scenes
  Code/Engine/Core/Prefabs/Implementation/PrefabReferenceComponent.cpp
  Code/Engine/Core/WorldSerializer/Implementation/WorldReader.cpp
Labels: bug

#1056 Bitfield and Math improvements
  Code/BuildSystem/CMake/CMakeUtils/ezUtilsCppFlags.cmake
  Code/BuildSystem/CMake/CMakeUtils/ezUtilsTarget.cmake
  Code/EditorPlugins/Jolt/EditorPluginJolt/Dialogs/JoltProjectSettingsDlg.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/EditorPluginJolt.cpp
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/Engine/Foundation/Containers/Bitfield.h
  Code/Engine/Foundation/Containers/Implementation/Bitfield_inl.h
  Code/Engine/Foundation/IO/JSONReader.h
  Code/Engine/Foundation/Math/Implementation/Math_inl.h
  Code/Engine/Foundation/Math/Math.h
  Code/Engine/GameEngine/Physics/CollisionFilter.h
  Code/Engine/GameEngine/Physics/Implementation/CollisionFilter.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
  Code/UnitTests/FoundationTest/Containers/BitfieldTest.cpp
  Code/UnitTests/FoundationTest/Math/MathTest.cpp
  Code/UnitTests/TestFramework/Utilities/TestOrder.cpp
Labels: improvement

#1063 Fixed #1062: Blackboard interface improvement
  Code/Editor/EditorFramework/Panels/LogPanel/Implementation/LogPanel.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/BlackboardTemplateAsset/BlackboardTemplateAssetWindow.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/BlackboardTemplateAsset/BlackboardTemplateAssetWindow.moc.h
  Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineAsset.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptClassAsset/VisualScriptClassAsset.cpp
  Code/Engine/Core/Utils/Blackboard.h
  Code/Engine/Core/Utils/Implementation/Blackboard.cpp
  Code/Engine/GameEngine/Gameplay/BlackboardComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/BlackboardComponent.cpp
  Code/Engine/GameEngine/Gameplay/Implementation/InputComponent.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BlackboardAnimNodes.cpp
  Code/EnginePlugins/RmlUiPlugin/Implementation/BlackboardDataBinding.cpp
  Code/Samples/RtsGamePlugin/GameMode/EditLevelMode/EditLevelMode.cpp
  Code/UnitTests/GameEngineTest/StateMachineTest/StateMachineBuiltinsTest.cpp
  Data/Base/Editor/ShapeIcons/ezBlackboardComponent.dds
  Data/Base/Editor/ShapeIcons/ezBlackboardComponent.png
  Data/UnitTests/GameEngineTest/StateMachine/Data/TestScript.ezVisualScriptClassAsset
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllEnums.ts
Labels: improvement

#1068 Visual Script fixes and improvements
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptClassAsset/VisualScriptClassAsset.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptCompiler.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptCompiler.h
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptNodeRegistry.cpp
  Code/Engine/Core/Scripting/Implementation/ScriptWorldModule.cpp
  Code/Engine/Core/Scripting/ScriptWorldModule.h
  Code/Engine/Core/Utils/Blackboard.h
  Code/Engine/Core/Utils/Implementation/Blackboard.cpp
  Code/Engine/Core/Utils/Implementation/IntervalScheduler_inl.h
  Code/Engine/Core/Utils/IntervalScheduler.h
  Code/Engine/Foundation/Types/Implementation/Variant.cpp
  Code/Engine/Foundation/Types/Variant.h
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptData_inl.h
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/Connection.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/Node.cpp
  Code/Tools/Libs/ToolsFoundation/NodeObject/Implementation/DocumentNodeManager.cpp
  Code/UnitTests/GameEngineTest/VisualScriptTest/VisualScriptTest.cpp
  Code/UnitTests/GameEngineTest/VisualScriptTest/VisualScriptTest.h
  Data/UnitTests/GameEngineTest/Images_Reference/VisualScript_Tests_Blackboard_000.png
  Data/UnitTests/GameEngineTest/Images_Reference/VisualScript_Tests_Coroutines_003.png
  Data/UnitTests/GameEngineTest/StateMachine/Data/TestScript.ezVisualScriptClassAsset
  Data/UnitTests/GameEngineTest/VisualScript/Data/BlackboardScript.ezVisualScriptClassAsset
  Data/UnitTests/GameEngineTest/VisualScript/Data/BlackboardTemplate.ezBlackboardTemplateAsset
  Data/UnitTests/GameEngineTest/VisualScript/Data/VariablesScript.ezVisualScriptClassAsset
  Data/UnitTests/GameEngineTest/VisualScript/Editor/BlackboardKeysEnum.txt
  Data/UnitTests/GameEngineTest/VisualScript/Scenes/Blackboard.ezScene
Labels: improvement

#1065 Added a "global blackboard" component
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezGlobalBlackboardComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezLocalBlackboardComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/Engine/GameEngine/Gameplay/BlackboardComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/BlackboardComponent.cpp
  Code/UnitTests/GameEngineTest/Basics/Basics.cpp
  Data/Base/Editor/ShapeIcons/ezGlobalBlackboardComponent.dds
  Data/Base/Editor/ShapeIcons/ezGlobalBlackboardComponent.png
  Data/Base/Editor/ShapeIcons/ezLocalBlackboardComponent.dds
  Data/Base/Editor/ShapeIcons/ezLocalBlackboardComponent.png
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllEnums.ts
Labels: new feature, improvement

#1069 Allow empty state-machine states
  Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineAsset.cpp
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachine.cpp
  Code/Engine/GameEngine/StateMachine/StateMachine.h
Labels: improvement

#1070 Added component to spawn prefabs in a box
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezSpawnBoxComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager.cpp
  Code/Engine/Core/ResourceManager/Resource.h
  Code/Engine/Core/Scripting/Implementation/ScriptWorldModule.cpp
  Code/Engine/Core/WorldSerializer/WorldReader.h
  Code/Engine/GameEngine/Gameplay/Implementation/SpawnBoxComponent.cpp
  Code/Engine/GameEngine/Gameplay/SpawnBoxComponent.h
  Code/EnginePlugins/JoltPlugin/System/JoltQueries.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Data/Base/Editor/ShapeIcons/ezSpawnBoxComponent.dds
  Data/Base/Editor/ShapeIcons/ezSpawnBoxComponent.png
Labels: new feature, needs documentation
