Repository ezEngine/ezEngine, pull requests merged in 2023-02, with the labels that each got.

#866 Fix decal asset resource reloading
  Code/Editor/EditorFramework/Assets/AssetDocumentManager.h
  Code/Editor/EditorFramework/Assets/AssetTableWriter.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocumentManager.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetTableWriter.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAssetManager.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAssetManager.h
  Code/Engine/GameEngine/GameApplication/Implementation/GameApplicationInit.cpp
Labels: bug

#868 Limit C++ solution build types to what the editor is built with
  Code/BuildSystem/CMake/ezUtils.cmake
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.cpp
Labels: improvement

#869 Added a component for propagating 'power flow' through cables
  Code/Engine/Core/Interfaces/PhysicsWorldModule.cpp
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/Implementation/PowerConnectorComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/PowerConnectorComponent.h
  Code/EnginePlugins/JoltPlugin/Constraints/Implementation/JoltGrabObjectComponent.cpp
  Code/EnginePlugins/JoltPlugin/Constraints/JoltGrabObjectComponent.h
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
Labels: new feature

#871 Migrated more code to use ezStringView (ezWorld)
  Code/Editor/EditorEngineProcessFramework/SceneExport/SceneExportModifier.cpp
  Code/Editor/EditorFramework/GUI/Implementation/RawDocumentTreeModel.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SceneActions.cpp
  Code/Engine/Core/ActorSystem/Actor.h
  Code/Engine/Core/ActorSystem/Implementation/Actor.cpp
  Code/Engine/Core/Collection/CollectionUtils.h
  Code/Engine/Core/Collection/Implementation/CollectionUtils.cpp
  Code/Engine/Core/Configuration/Implementation/PlatformProfile.cpp
  Code/Engine/Core/Configuration/PlatformProfile.h
  Code/Engine/Core/Scripting/Duktape/DuktapeFunction.cpp
  Code/Engine/Core/Scripting/DuktapeFunction.h
  Code/Engine/Core/System/Implementation/Window.cpp
  Code/Engine/Core/System/Window.h
  Code/Engine/Core/Utils/Blackboard.h
  Code/Engine/Core/Utils/Implementation/Blackboard.cpp
  Code/Engine/Core/World/GameObject.h
  Code/Engine/Core/World/Implementation/GameObject.cpp
  Code/Engine/Core/World/Implementation/GameObject_inl.h
  Code/Engine/Core/World/Implementation/SpatialData.cpp
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/Core/World/Implementation/World_inl.h
  Code/Engine/Core/World/SpatialData.h
  Code/Engine/Core/World/World.h
  Code/Engine/Core/WorldSerializer/Implementation/WorldReader.cpp
  Code/Engine/Core/WorldSerializer/WorldReader.h
  Code/Engine/Foundation/IO/Implementation/JSONWriter.cpp
  Code/Engine/Foundation/IO/Implementation/StandardJSONWriter.cpp
  Code/Engine/Foundation/IO/JSONWriter.h
  Code/Engine/Foundation/Profiling/Implementation/Profiling.cpp
  Code/Engine/Foundation/Profiling/Profiling.h
  Code/Engine/Foundation/System/Implementation/UuidGenerator.cpp
  Code/Engine/Foundation/Types/Uuid.h
  Code/Engine/Foundation/Utilities/Implementation/Progress.cpp
  Code/Engine/Foundation/Utilities/Progress.h
  Code/Engine/RendererCore/Components/Implementation/CameraComponent.cpp
  Code/Engine/RendererCore/Pipeline/Implementation/Extractor.cpp
  Code/Engine/RendererCore/Pipeline/Implementation/View.cpp
  Code/Engine/RendererCore/Pipeline/Implementation/View_inl.h
  Code/Engine/RendererCore/Pipeline/View.h
  Code/Engine/Utilities/DGML/Implementation/DGMLCreator.cpp
  Code/EnginePlugins/TypeScriptPlugin/TsBinding/TsGameObject.cpp
  Code/EnginePlugins/TypeScriptPlugin/TsBinding/TsUtils.cpp
  Code/UnitTests/CoreTest/World/ComponentTest.cpp
  Code/UnitTests/CoreTest/World/WorldTest.cpp
  Code/UnitTests/FoundationTest/Utility/ProgressTest.cpp
Labels: code quality

#873 Added easy way to play a one-shot sound
  Code/Engine/Core/Interfaces/SoundInterface.cpp
  Code/Engine/Core/Interfaces/SoundInterface.h
  Code/Engine/Core/ResourceManager/Implementation/Resource.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceLoading.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager_inl.h
  Code/Engine/Core/ResourceManager/Resource.h
  Code/Engine/Core/ResourceManager/ResourceManager.h
  Code/EnginePlugins/FmodPlugin/Components/FmodEventComponent.cpp
  Code/EnginePlugins/FmodPlugin/FmodSingleton.cpp
  Code/EnginePlugins/FmodPlugin/FmodSingleton.h
  Code/EnginePlugins/FmodPlugin/Resources/FmodSoundEventResource.cpp
  Code/EnginePlugins/FmodPlugin/Resources/FmodSoundEventResource.h
Labels: improvement

#874 Fail prefab export when C++ types are missing
  Code/Editor/EditorEngineProcessFramework/EngineProcess/EngineProcessDocumentContext.h
  Code/Editor/EditorEngineProcessFramework/EngineProcess/EngineProcessMessages.h
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/EngineProcessDocumentContext.cpp
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/EngineProcessMessages.cpp
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/WorldRttiConverterContext.cpp
  Code/Editor/EditorEngineProcessFramework/EngineProcess/WorldRttiConverterContext.h
  Code/Editor/EditorFramework/Assets/AssetCurator.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetCurator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocument.cpp
  Code/Editor/EditorFramework/EditorApp/EditorApp.moc.h
  Code/Editor/EditorFramework/IPC/EngineProcessConnection.cpp
  Code/Editor/EditorProcessor/EditorProcessor.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/LayerContext.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/LayerContext.h
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.h
  Code/Engine/Foundation/Serialization/Implementation/RttiConverterReader.cpp
  Code/Engine/Foundation/Serialization/Implementation/RttiConverterWriter.cpp
  Code/Engine/Foundation/Serialization/RttiConverter.h
Labels: improvement

#878 Improvements for the PacMan sample
  Code/Engine/Core/Prefabs/Implementation/PrefabResource.cpp
  Code/Engine/Core/Prefabs/PrefabResource.h
  Code/Engine/Foundation/Reflection/Implementation/DynamicRTTI.h
  Code/Engine/Foundation/Reflection/Implementation/StaticRTTI.h
  Data/Samples/PacMan/CppSource/PacManPlugin/CMakeLists.txt
  Data/Samples/PacMan/CppSource/PacManPlugin/Components/GhostComponent.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/Components/GhostComponent.h
  Data/Samples/PacMan/CppSource/PacManPlugin/Components/PacManComponent.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/Components/PacManComponent.h
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.h
  Data/Samples/PacMan/CppSource/PacManPlugin/PacManPluginPCH.h
  Data/Samples/PacMan/Prefabs/Ghost.ezPrefab
  Data/Samples/PacMan/Prefabs/WinGame.ezPrefab
  Data/Samples/PacMan/Scenes/Level1.ezScene
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleBounceComponent.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleRenderComponent.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/CppProjectPluginPCH.h
Labels: improvement
