Repository ezEngine/ezEngine, pull requests merged in 2024-04, with the labels that each got.

#1248 ezGeometry now takes a main axis option
  Code/Editor/EditorEngineProcessFramework/Gizmos/Implementation/GizmoHandle.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.cpp
  Code/EditorPlugins/Assets/EnginePluginAssets/DecalAsset/DecalContext.cpp
  Code/EditorPlugins/Assets/EnginePluginAssets/MaterialAsset/MaterialContext.cpp
  Code/EditorPlugins/Assets/EnginePluginAssets/TextureAsset/TextureContext.cpp
  Code/EditorPlugins/Assets/EnginePluginAssets/TextureCubeAsset/TextureCubeContext.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/EditorPluginScene.cpp
  Code/Engine/Core/Graphics/Geometry.h
  Code/Engine/Core/Graphics/Implementation/Geometry.cpp
  Code/Engine/Foundation/Math/Implementation/Math.cpp
  Code/Engine/Foundation/Serialization/AbstractObjectGraph.h
  Code/Engine/GameEngine/Gameplay/GreyBoxComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Engine/RendererCore/BakedProbes/Implementation/BakedProbesComponent.cpp
  Code/Engine/RendererCore/Components/Implementation/SkyBoxComponent.cpp
  Code/Engine/RendererCore/Lights/Implementation/ReflectionPoolData.cpp
  Code/Samples/ComputeShaderHistogram/ComputeShaderHistogram.cpp
  Code/Samples/ShaderExplorer/ShaderExplorer.cpp
  Code/Samples/TextureSample/TextureSample.cpp
  Code/UnitTests/GameEngineTest/Basics/Basics.cpp
  Code/UnitTests/RendererTest/Advanced/AdvancedFeatures.cpp
  Code/UnitTests/RendererTest/Basics/PipelineStates.cpp
  Data/UnitTests/GameEngineTest/Effects/Scenes/Decals.ezScene
  Data/UnitTests/GameEngineTest/Particles/NoPullAlong.ezParticleEffectAsset
  Data/UnitTests/GameEngineTest/Particles/PullAlong.ezScene
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllEnums.ts
  gitClean.txt
Labels: improvement

#1250 FileServe setup for ShaderExplorer sample
  Code/Samples/ShaderExplorer/ShaderExplorer.cpp
  Code/Samples/ShaderExplorer/ShaderExplorer.h
Labels: improvement

#1249 Adjusted modifiers for gizmos to prevent unwanted input
  Code/Editor/EditorFramework/EditTools/Implementation/StandardGizmoEditTools.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/DragToPositionGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/DrawBoxGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/NonUniformBoxGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/RotateGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/ScaleGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/TranslateGizmo.cpp
  Code/Editor/EditorFramework/InputContexts/CameraMoveContext.h
  Code/Editor/EditorFramework/InputContexts/EditorInputContext.h
  Code/Editor/EditorFramework/InputContexts/Implementation/CameraMoveContext.cpp
  Code/Editor/EditorFramework/InputContexts/Implementation/EditorInputContext.cpp
  Code/Editor/EditorFramework/InputContexts/Implementation/OrthoGizmoContext.cpp
  Code/Editor/EditorFramework/InputContexts/Implementation/SelectionContext.cpp
Labels: improvement

#1252 Added components to apply aim IK and two-bone IK to animated meshes
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezAimIKComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezTwoBoneIKComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/Engine/GameEngine/Animation/Skeletal/AimIKComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/AnimationControllerComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AimIKComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AnimationControllerComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/SimpleAnimationComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/TwoBoneIKComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/SimpleAnimationComponent.h
  Code/Engine/GameEngine/Animation/Skeletal/TwoBoneIKComponent.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimController.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimController.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimPoseGenerator.h
  Code/Engine/RendererCore/AnimationSystem/Declarations.h
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimPoseGenerator.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationPose.cpp
  Data/Base/Editor/ShapeIcons/ConvertAll.ps1
  Data/Base/Editor/ShapeIcons/ezAimIKComponent.dds
  Data/Base/Editor/ShapeIcons/ezAimIKComponent.png
  Data/Base/Editor/ShapeIcons/ezTwoBoneIKComponent.dds
  Data/Base/Editor/ShapeIcons/ezTwoBoneIKComponent.png
  Data/Samples/Testing Chambers/Scenes/Animation.ezScene
Labels: new feature, needs documentation

#1258 FileServe tool can now remote compile shaders
  Code/EditorPlugins/Fileserve/EditorPluginFileserve/FileserveUI/FileserveWidget.cpp
  Code/Engine/Core/Interfaces/RemoteToolingInterface.h
  Code/Engine/Foundation/Communication/Implementation/RemoteInterface.cpp
  Code/Engine/Foundation/Communication/RemoteInterface.h
  Code/Engine/Foundation/Containers/Implementation/SmallArray_inl.h
  Code/Engine/Foundation/IO/MemoryStream.h
  Code/Engine/RendererCore/Shader/Implementation/ShaderPermutationResource.cpp
  Code/Engine/RendererCore/Shader/Implementation/ShaderStageBinary.cpp
  Code/Engine/RendererCore/Shader/ShaderStageBinary.h
  Code/Engine/RendererCore/ShaderCompiler/Implementation/ShaderCompiler.cpp
  Code/Engine/RendererCore/ShaderCompiler/Implementation/ShaderManager.cpp
  Code/Engine/RendererCore/ShaderCompiler/ShaderCompiler.h
  Code/EnginePlugins/FileservePlugin/Client/FileserveClient.cpp
  Code/EnginePlugins/FileservePlugin/Client/FileserveClient.h
  Code/EnginePlugins/FileservePlugin/Fileserver/Fileserver.cpp
  Code/EnginePlugins/FileservePlugin/Fileserver/Fileserver.h
  Code/Samples/ShaderExplorer/ShaderExplorer.cpp
  Code/Samples/ShaderExplorer/ShaderExplorer.h
  Code/Tools/Fileserve/App.cpp
  Code/Tools/Fileserve/CMakeLists.txt
  Code/Tools/Fileserve/Fileserve.cpp
  Code/Tools/Fileserve/Fileserve.h
Labels: new feature

#1261 Fixed #1255: assets being created in wrong path
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
Labels: bug

#1260 Fixed ezTypedComponentHandle type safety with TryGetComponent
  Code/Engine/Core/World/World.h
  Code/UnitTests/CoreTest/World/ComponentTest.cpp
Labels: improvement

#1266 Added CreatureCrawlComponent for procedural leg movement
  Code/EnginePlugins/GameComponentsPlugin/Animation/CreatureCrawlComponent.h
  Code/EnginePlugins/GameComponentsPlugin/Animation/Implementation/CreatureCrawlComponent.cpp
  Data/Samples/Testing Chambers/AI/SpotBot.ezPrefab
  Data/Samples/Testing Chambers/AI/SpotBot_data/SpotBot.ezVisualScriptClassAsset
  Data/Samples/Testing Chambers/Scenes/Vegetation.ezScene
Labels: new feature, needs documentation

#1269 ezFoundation improvements
  Code/Engine/Foundation/Basics/IncludeAll.cpp
  Code/Engine/Foundation/Containers/HybridArray.h
  Code/Engine/Foundation/Containers/Implementation/HybridArray_inl.h
  Code/Engine/Foundation/IO/DirectoryWatcher.h
  Code/Engine/Foundation/IO/FileSystem/FileSystem.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/FileReader.cpp
  Code/Engine/Foundation/IO/FileSystem/Implementation/FileSystem.cpp
  Code/Engine/Foundation/IO/Implementation/OSFile.cpp
  Code/Engine/Foundation/Math/Implementation/BoundingBox_inl.h
  Code/Engine/Foundation/Math/Implementation/Rect_inl.h
  Code/Engine/Foundation/Math/Implementation/Transform_inl.h
  Code/Engine/Foundation/Math/Rect.h
  Code/Engine/Foundation/Math/Transform.h
  Code/Engine/Foundation/Memory/FrameAllocator.h
  Code/Engine/Foundation/Memory/Implementation/LinearAllocator_inl.h
  Code/Engine/Foundation/Memory/Implementation/MemoryUtils_inl.h
  Code/Engine/Foundation/Memory/LinearAllocator.h
  Code/Engine/Foundation/Memory/Policies/AllocPolicyLinear.h
  Code/Engine/Foundation/Platform/Win/OSFile_Win.cpp
  Code/Engine/Foundation/Strings/Implementation/PathUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBuilder_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringUtils_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringView.cpp
  Code/Engine/Foundation/Strings/Implementation/StringView_inl.h
  Code/Engine/Foundation/Strings/Implementation/snprintf.cpp
  Code/Engine/Foundation/Strings/StringBuilder.h
  Code/Engine/Foundation/Strings/StringUtils.h
  Code/Engine/Foundation/Strings/StringView.h
  Code/Engine/Foundation/Types/TypeTraits.h
  Code/Engine/Foundation/Types/Types.h
  Code/Engine/Foundation/Utilities/CommandLineUtils.h
  Code/Engine/Foundation/ezEngine.natvis
  Code/UnitTests/TestFramework/Utilities/TestSetup.cpp
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllMessages.ts
Labels: improvement

#1273 AnimGraph: Hold last frame of sampled clips
  Code/Engine/Foundation/Math/Implementation/ColorScheme.cpp
  Code/Engine/Foundation/Reflection/Implementation/RTTI.h
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/MotionMatchingComponent.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/PoseResultAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/PoseResultAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.h
  Code/Tools/Libs/ToolsFoundation/NodeObject/Implementation/DocumentNodeManager.cpp
  Code/UnitTests/TestFramework/Framework/Qt/qtTestGUI.ui
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleBounceComponent.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/Components/SampleRenderComponent.cpp
  Data/UnitTests/GameEngineTest/Animations/Editor/BlackboardKeysEnum.txt
  Data/UnitTests/GameEngineTest/Animations/Pete/Pete.ezAnimationGraphAsset
  Data/UnitTests/GameEngineTest/Animations/Scenes/AnimController.ezScene
  Data/UnitTests/GameEngineTest/Images_Reference/Animations_Tests_Skeletal_000.png
  Data/UnitTests/GameEngineTest/Images_Reference/Animations_Tests_Skeletal_001.png
  Data/UnitTests/GameEngineTest/Images_Reference/Animations_Tests_Skeletal_002.png
  Data/UnitTests/GameEngineTest/TypeScript/TypeScript/ez/AllComponents.ts
Labels: improvement

#1274 Mesh instance custom data
  Code/Engine/Core/Messages/Implementation/SetColorMessage.cpp
  Code/Engine/Core/Messages/SetColorMessage.h
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/LodAnimatedMeshComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/LodAnimatedMeshComponent.h
  Code/Engine/GameEngine/Gameplay/GreyBoxComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Engine/RendererCore/Meshes/CustomMeshComponent.h
  Code/Engine/RendererCore/Meshes/Implementation/CustomMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/InstancedMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/LodMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshComponentBase.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshRendererUtils.h
  Code/Engine/RendererCore/Meshes/LodMeshComponent.h
  Code/Engine/RendererCore/Meshes/MeshComponentBase.h
  Code/EnginePlugins/GameComponentsPlugin/Physics/Implementation/ClothSheetComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltClothSheetComponent.cpp
  Code/EnginePlugins/KrautPlugin/Renderer/KrautRenderer.cpp
  Data/Base/RenderPipelines/MainRenderPipeline.ezRenderPipelineAsset
  Data/Base/Shaders/Common/ObjectConstants.h
  Data/Tools/ezEditor/ShaderTemplates/PBR.ezShaderTemplate
  Data/Tools/ezEditor/VisualShader/Inputs.ddl
Labels: new feature

#1275 Disable Tracy and fix some other issues
  CMakeLists.txt
  Code/Editor/Editor/CMakeLists.txt
  Code/Engine/Foundation/Memory/Implementation/MemoryTracker.cpp
  Code/ThirdParty/tracy/CMakeLists.txt
  Code/ThirdParty/tracy/init.cmake
  Code/Tools/Player/CMakeLists.txt
  Data/Tools/ezEditor/ShaderTemplates/Fullbright.ezShaderTemplate
  Data/Tools/ezEditor/ShaderTemplates/PBR.ezShaderTemplate
  gitClean.txt
Labels: improvement
