Repository ezEngine/ezEngine, pull requests merged in 2024-03, with the labels that each got.

#1225 Added AI navigation component and sample scene
  Code/EditorPlugins/AI/EditorPluginAi/QtResources/ezAiNavigationComponent.svg
  Code/EditorPlugins/AI/EditorPluginAi/QtResources/resources.qrc
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/ezScriptComponent.svg
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/resources.qrc
  Code/Engine/Foundation/Reflection/Implementation/StandardTypes.cpp
  Code/EnginePlugins/AiPlugin/AiPluginPCH.h
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavMeshPathTestComponent.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavMeshPathTestComponent.h
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavigationComponent.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavigationComponent.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/Navigation.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/Steering.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Navigation.h
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltStaticActorComponent.cpp
  Code/UnitTests/FoundationTest/Strings/PathUtilsTest.cpp
  Data/Samples/Testing Chambers/AI/AiWalker.ezPrefab
  Data/Samples/Testing Chambers/AI/AiWalker.ezVisualScriptClassAsset
  Data/Samples/Testing Chambers/Animations/Pete/Pete-Locomotion.ezAnimationGraphAsset
  Data/Samples/Testing Chambers/Animations/Pete/Wave.ezAnimationClipAsset
  Data/Samples/Testing Chambers/Editor/BlackboardKeysEnum.txt
  Data/Samples/Testing Chambers/Editor/PluginSelection.ddl
  Data/Samples/Testing Chambers/Effects/MagicSpawn.ezPrefab
  Data/Samples/Testing Chambers/Materials/cc0Textures.com/Water_Animated.ezMaterialAsset
  Data/Samples/Testing Chambers/RuntimeConfigs/AiPluginConfig.cfg
  Data/Samples/Testing Chambers/RuntimeConfigs/Plugins.ddl
  Data/Samples/Testing Chambers/Scenes/Ai.ezScene
  Data/Samples/Testing Chambers/Scenes/Ai_data/Level Geometry.ezSceneLayer
Labels: new feature

#1227 Various smaller improvements for animation editing
  Code/Editor/EditorFramework/EditorApp/Qt.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/MathAnimNodes.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/MathAnimNodes.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.h
  Code/Tools/Libs/GuiFoundation/Widgets/EventTrackEditorWidget.moc.h
  Code/Tools/Libs/GuiFoundation/Widgets/EventTrackEditorWidget.ui
  Code/Tools/Libs/GuiFoundation/Widgets/EventTrackWidget.moc.h
  Code/Tools/Libs/GuiFoundation/Widgets/Implementation/EventTrackEditorWidget.cpp
  Data/Tools/ezEditor/Localization/en/AnimationGraphAsset.txt
Labels: improvement

#1226 Fixes for scripting error
  Code/Editor/EditorFramework/PropertyGrid/Implementation/AssetBrowserPropertyWidget.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptNodeRegistry.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.h
  gitClean.txt
Labels: bug

#1230 MSFT contributions March 2024
  Code/BuildSystem/CMake/ezPlatform.cmake
  Code/Engine/Core/Interfaces/PhysicsQuery.h
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/Engine/Core/ResourceManager/Implementation/ResourceHandle.cpp
  Code/Engine/Core/WorldSerializer/Implementation/WorldReader.cpp
  Code/Engine/Core/WorldSerializer/WorldReader.h
  Code/Engine/Foundation/Containers/Bitfield.h
  Code/Engine/Foundation/Containers/Blob.h
  Code/Engine/Foundation/Containers/Implementation/Bitfield_inl.h
  Code/Engine/Foundation/Containers/Implementation/Blob.cpp
  Code/Engine/Foundation/IO/Archive/Archive.h
  Code/Engine/Foundation/IO/Archive/ArchiveUtils.h
  Code/Engine/Foundation/IO/Archive/DataDirTypeArchive.h
  Code/Engine/Foundation/IO/Archive/Implementation/Archive.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/ArchiveBuilder.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/ArchiveReader.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/ArchiveUtils.cpp
  Code/Engine/Foundation/IO/Archive/Implementation/DataDirTypeArchive.cpp
  Code/Engine/Foundation/IO/FileSystem/DataDirTypeFolder.h
  Code/Engine/Foundation/IO/FileSystem/FileReader.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/DataDirType.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/DataDirTypeFolder.cpp
  Code/Engine/Foundation/IO/FileSystem/Implementation/FileReader.cpp
  Code/Engine/Foundation/IO/Implementation/CompressedStreamZstd.cpp
  Code/Engine/Foundation/Math/Declarations.h
  Code/Engine/Foundation/Math/Frustum.h
  Code/Engine/Foundation/Math/Implementation/Frustum.cpp
  Code/Engine/Foundation/Math/Implementation/Plane_inl.h
  Code/Engine/Foundation/Platform/OSX/MiniDumpUtils_OSX.cpp
  Code/Engine/Foundation/Platform/Posix/MiniDumpUtils_Posix.h
  Code/Engine/Foundation/Platform/Win/MiniDumpUtils_Win.cpp
  Code/Engine/Foundation/Profiling/Implementation/Profiling.cpp
  Code/Engine/Foundation/Strings/FormatString.h
  Code/Engine/Foundation/System/Implementation/Win/Process_win.h
  Code/Engine/Foundation/System/MiniDumpUtils.h
  Code/Engine/Foundation/Threading/AtomicInteger.h
  Code/Engine/Foundation/Threading/Implementation/ParallelFor.cpp
  Code/Engine/Foundation/Threading/TaskSystem.h
  Code/Engine/Texture/Image/ImageHeader.h
  Code/UnitTests/CoreTest/TexConv/TexConvTest.cpp
  Code/UnitTests/FoundationTest/Communication/IpcChannelTest.cpp
  Code/UnitTests/FoundationTest/Containers/BitfieldTest.cpp
  Code/UnitTests/FoundationTest/Math/FrustumTest.cpp
  Code/UnitTests/FoundationTest/Math/PlaneTest.cpp
  Code/UnitTests/FoundationTest/Threading/ParallelForTest.cpp
  Code/UnitTests/TestFramework/Framework/TestBaseClass.cpp
  Code/UnitTests/TestFramework/Framework/TestBaseClass.h
  Code/UnitTests/TestFramework/Framework/TestFramework.cpp
  Code/UnitTests/TestFramework/Framework/TestResults.h
Labels: improvement

#1228 NavMeshObstacleComponent
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavMeshObstacleComponent.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavMeshObstacleComponent.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMesh.cpp
  Code/EnginePlugins/AiPlugin/Navigation/NavMesh.h
  Code/EnginePlugins/AiPlugin/Navigation/NavMeshWorldModule.h
  Code/EnginePlugins/JoltPlugin/Actors/JoltActorComponent.h
  Code/EnginePlugins/JoltPlugin/Actors/JoltDynamicActorComponent.h
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
Labels: new feature

#1231 Improved selection and copy/paste behavior
  Code/Editor/EditorFramework/EditTools/Implementation/GizmoEditTool.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MaterialAsset/MaterialAsset.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SelectionActions.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Commands/SceneCommands.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Dialogs/DeltaTransformDlg.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/Prefabs.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.h
  Code/Tools/Libs/GuiFoundation/Action/Implementation/EditActions.cpp
  Code/Tools/Libs/ToolsFoundation/Document/Document.h
  Code/Tools/Libs/ToolsFoundation/Document/Implementation/Document.cpp
  Code/Tools/Libs/ToolsFoundation/Document/Implementation/DocumentPrefab.cpp
  Code/Tools/Libs/ToolsFoundation/Selection/Implementation/SelectionManager.cpp
  Code/Tools/Libs/ToolsFoundation/Selection/SelectionManager.h
  Code/UnitTests/EditorTest/SceneDocument/SceneDocumentTest.cpp
Labels: improvement

#1236 Moved the index for array Insert methods to the front
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetProfile.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MaterialAsset/MaterialAsset.cpp
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionASTTransforms.cpp
  Code/Engine/Foundation/Containers/ArrayBase.h
  Code/Engine/Foundation/Containers/Deque.h
  Code/Engine/Foundation/Containers/Implementation/ArrayBase_inl.h
  Code/Engine/Foundation/Containers/Implementation/Deque_inl.h
  Code/Engine/Foundation/Containers/Implementation/SmallArray_inl.h
  Code/Engine/Foundation/Containers/SmallArray.h
  Code/Engine/Foundation/Reflection/Implementation/ArrayProperty.h
  Code/Engine/GameEngine/Animation/Implementation/PathComponent.cpp
  Code/Engine/GameEngine/Effects/PostProcessing/Implementation/PostProcessingComponent.cpp
  Code/Engine/GameEngine/Gameplay/Implementation/BlackboardComponent.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BoneWeightsAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.cpp
  Code/Engine/RendererCore/Decals/Implementation/DecalComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/InstancedMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshComponentBase.cpp
  Code/Engine/RendererVulkan/Device/Implementation/DeviceVulkan.cpp
  Code/Engine/Texture/Image/Implementation/ImageConversion.cpp
  Code/EnginePlugins/ProcGenPlugin/Components/Implementation/ProcPlacementComponent.cpp
  Code/EnginePlugins/ProcGenPlugin/Components/Implementation/ProcVertexColorComponent.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Code/Tools/Libs/GuiFoundation/Action/ActionMap.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
  Code/Tools/Libs/ToolsFoundation/Reflection/Implementation/ReflectedType.cpp
  Code/Tools/Libs/ToolsFoundation/Reflection/Implementation/ReflectedTypeStorageAccessor.cpp
  Code/UnitTests/FoundationTest/Containers/DequeTest.cpp
  Code/UnitTests/FoundationTest/Containers/DynamicArrayTest.cpp
  Code/UnitTests/FoundationTest/Containers/HybridArrayTest.cpp
  Code/UnitTests/FoundationTest/Containers/SmallArrayTest.cpp
  Code/UnitTests/FoundationTest/Containers/StaticArrayTest.cpp
  Code/UnitTests/FoundationTest/Reflection/ReflectionTestClasses.cpp
  Code/UnitTests/ToolsFoundationTest/FileSystem/FileSystemModelTest.cpp
Labels: code quality

#1238 Some Foundation improvements
  Code/Engine/Foundation/Basics/AllDefinesOff.h
  Code/Engine/Foundation/Containers/ArrayBase.h
  Code/Engine/Foundation/Containers/HashTable.h
  Code/Engine/Foundation/Containers/Implementation/HashTable_inl.h
  Code/Engine/Foundation/Containers/Implementation/Map_inl.h
  Code/Engine/Foundation/Containers/Map.h
  Code/Engine/Foundation/IO/Archive/Implementation/ArchiveUtils.cpp
  Code/Engine/Foundation/IO/FileSystem/FileSystem.h
  Code/Engine/Foundation/IO/FileSystem/Implementation/FileSystem.cpp
  Code/Engine/Foundation/IO/Implementation/OSFile.cpp
  Code/Engine/Foundation/IO/OSFile.h
  Code/Engine/Foundation/Platform/Posix/OSFile_Posix.h
  Code/Engine/Foundation/Platform/Win/OSFile_Win.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBase.h
  Code/Engine/Foundation/Strings/Implementation/StringBase_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Engine/Foundation/Strings/Implementation/StringView_inl.h
  Code/Engine/Foundation/Strings/StringBuilder.h
  Code/Engine/Foundation/headerCheckerIgnore.json
  gitClean.txt
Labels: improvement

#1237 Synch MSFT changes
  Code/Engine/Foundation/Math/Frustum.h
  Code/Engine/Foundation/Math/Implementation/Frustum.cpp
  Code/UnitTests/FoundationTest/Math/FrustumTest.cpp
Labels: improvement

#1246 Android Renderer Support
  Code/Editor/EditorEngineProcess/EngineProcGameApp.cpp
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBaseInit.cpp
  Code/Engine/Core/System/Implementation/Window.cpp
  Code/Engine/Core/System/Implementation/android/Window_android.inl
  Code/Engine/Core/System/Implementation/null/InputDevice_null.h
  Code/Engine/Core/System/Implementation/null/InputDevice_null.inl
  Code/Engine/Core/System/Window.h
  Code/Engine/RendererDX11/Device/Implementation/DeviceDX11.cpp
  Code/Engine/RendererFoundation/Device/DeviceCapabilities.h
  Code/Engine/RendererFoundation/Profiling/Implementation/Profiling.cpp
  Code/Engine/RendererVulkan/CMakeLists.txt
  Code/Engine/RendererVulkan/Device/DeviceVulkan.h
  Code/Engine/RendererVulkan/Device/Implementation/DeviceVulkan.cpp
  Code/Engine/RendererVulkan/Device/Implementation/SwapChainVulkan.cpp
  Code/Engine/RendererVulkan/Device/SwapChainVulkan.h
  Code/Engine/RendererVulkan/MemoryAllocator/Implementation/MemoryAllocatorVulkan.cpp
  Code/Engine/RendererVulkan/RendererVulkanDLL.h
  Code/Engine/RendererVulkan/RendererVulkanPCH.cpp
  Code/Engine/RendererVulkan/RendererVulkanPCH.h
  Code/Engine/RendererVulkan/Resources/Implementation/BufferVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/FallbackResourcesVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/QueryVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/RenderTargetViewVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/ResourceViewVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/SharedTextureVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/TextureVulkan.cpp
  Code/Engine/RendererVulkan/Resources/Implementation/UnorderedAccessViewVulkan.cpp
  Code/Engine/RendererVulkan/Shader/Implementation/ShaderVulkan.cpp
  Code/Engine/RendererVulkan/Shader/Implementation/VertexDeclarationVulkan.cpp
  Code/Engine/RendererVulkan/State/Implementation/StateVulkan.cpp
  Code/Engine/RendererVulkan/Utils/Implementation/ConversionUtilsVulkan.inl.h
  Code/Engine/RendererVulkan/Utils/Implementation/ImageCopyVulkan.cpp
  Code/Samples/ShaderExplorer/ShaderExplorer.cpp
  Code/Samples/TextureSample/TextureSample.cpp
  Code/UnitTests/RendererTest/Advanced/AdvancedFeatures.cpp
  Code/UnitTests/RendererTest/Advanced/AdvancedFeatures.h
  Code/UnitTests/RendererTest/Basics/Readback.cpp
  Code/UnitTests/RendererTest/Basics/Textures.cpp
  Code/UnitTests/RendererTest/CMakeLists.txt
  Code/UnitTests/RendererTest/TestClass/TestClass.cpp
  Data/Base/Shaders/Common/LightingSimplified.h
  Data/Base/Shaders/Materials/HitBoxVisualization.ezShader
  Data/Base/Shaders/Materials/LensFlareMaterial.ezShader
  Data/Base/Shaders/Materials/MaterialPixelShaderSimplified.h
  Data/Base/Shaders/Materials/SkeletonVisualization.ezShader
  Data/Base/Shaders/Pipeline/Blur.ezShader
  Data/Base/Shaders/Pipeline/SelectionHighlight.ezShader
  Data/Base/Shaders/Pipeline/SeparatedBilateralBlur.ezShader
Labels: dev work
