Repository ezEngine/ezEngine, pull requests merged in 2024-01, with the labels that each got.

#1140 Added JoltClothSheetComponent
  Code/EditorPlugins/Jolt/EditorPluginJolt/QtResources/ezJoltClothSheetComponent.svg
  Code/EditorPlugins/Jolt/EditorPluginJolt/QtResources/resources.qrc
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/Engine/Core/Interfaces/WindWorldModule.h
  Code/Engine/GameEngine/Gameplay/GreyBoxComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Engine/GameEngine/Volumes/Implementation/VolumeComponent.cpp
  Code/Engine/GameEngine/Volumes/Implementation/VolumeSampler.cpp
  Code/Engine/RendererCore/Pipeline/RenderData.h
  Code/EnginePlugins/JoltPlugin/Character/Implementation/JoltCharacterControllerComponent.cpp
  Code/EnginePlugins/JoltPlugin/Character/JoltCharacterControllerComponent.h
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltClothSheetComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRopeComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/JoltClothSheetComponent.h
  Code/EnginePlugins/JoltPlugin/Declarations.h
  Code/EnginePlugins/JoltPlugin/System/JoltCollisionFiltering.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltCollisionFiltering.h
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/UIServices.cpp
  Data/Samples/Testing Chambers/Materials/cc0Textures.com/Asphalt10.ezMaterialAsset
  Data/Samples/Testing Chambers/Scenes/Physics.ezScene
Labels: new feature

#1142 Enabled Ragdoll <-> Cloth collision
  Code/EnginePlugins/JoltPlugin/System/JoltCollisionFiltering.cpp
  Code/ThirdParty/Jolt/Core/JobSystemThreadPool.cpp
  Code/ThirdParty/Jolt/Jolt.cmake
  Code/ThirdParty/Jolt/Physics/Body/Body.cpp
  Code/ThirdParty/Jolt/Physics/Body/Body.h
  Code/ThirdParty/Jolt/Physics/Body/Body.inl
  Code/ThirdParty/Jolt/Physics/Body/BodyCreationSettings.cpp
  Code/ThirdParty/Jolt/Physics/Body/BodyCreationSettings.h
  Code/ThirdParty/Jolt/Physics/Body/BodyManager.cpp
  Code/ThirdParty/Jolt/Physics/Body/MotionProperties.h
  Code/ThirdParty/Jolt/Physics/Collision/ContactListener.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/CapsuleShape.cpp
  Code/ThirdParty/Jolt/Physics/Constraints/ConstraintPart/AxisConstraintPart.h
  Code/ThirdParty/Jolt/Physics/Constraints/HingeConstraint.cpp
  Code/ThirdParty/Jolt/Physics/Constraints/HingeConstraint.h
  Code/ThirdParty/Jolt/Physics/Constraints/SixDOFConstraint.cpp
  Code/ThirdParty/Jolt/Physics/Constraints/SixDOFConstraint.h
  Code/ThirdParty/Jolt/Physics/PhysicsSystem.cpp
  Code/ThirdParty/Jolt/Physics/PhysicsUpdateContext.h
  Code/ThirdParty/Jolt/Physics/SoftBody/SoftBodyShape.cpp
  Code/ThirdParty/Jolt/Physics/SoftBody/SoftBodyShape.h
  Code/ThirdParty/Jolt/Renderer/DebugRenderer.h
  Code/ThirdParty/Jolt/cgmanifest.json
Labels: improvement

#1141 WIP: DetourCrowdAgentComponent
  Code/Engine/RendererCore/Debug/DebugRenderer.h
  Code/Engine/RendererCore/Debug/Implementation/DebugRenderer.cpp
  Code/EnginePlugins/RecastPlugin/Components/DetourCrowdAgentComponent.cpp
  Code/EnginePlugins/RecastPlugin/Components/DetourCrowdAgentComponent.h
  Code/EnginePlugins/RecastPlugin/WorldModule/DetourCrowdWorldModule.cpp
  Code/EnginePlugins/RecastPlugin/WorldModule/DetourCrowdWorldModule.h
Labels: new feature

#1150 Fixed #1146: Added physics collision geometry visualization
  Code/Engine/RendererCore/Meshes/Implementation/CustomMeshComponent.cpp
  Code/Engine/RendererCore/RenderWorld/RenderWorld.h
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltCustomShapeInfo.cpp
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltCustomShapeInfo.h
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
  Data/Base/Materials/Common/Pattern.ezMaterialAsset
  Data/Base/Materials/Common/PhysicsColliders.ezMaterialAsset
  Data/Base/Materials/Common/PhysicsCollidersSoft.ezMaterialAsset
  Data/Base/Materials/Common/PhysicsCollidersTransparent.ezMaterialAsset
  Data/Samples/Testing Chambers/Prefabs/Player.ezPrefab
  Data/Samples/Testing Chambers/Vegetation/Quaternius/Tree4.ezMeshAsset_data/Tree4.ezJoltCollisionMeshAsset
  Data/Tools/ezEditor/VisualShader/Textures.ddl
Labels: new feature

#1152 Make it possible to manually specify a precompiled tools
  Code/Editor/EditorFramework/EditorApp/ExternalTools.cpp
  Code/Editor/EditorFramework/Preferences/EditorPreferences.cpp
  Code/Editor/EditorFramework/Preferences/EditorPreferences.h
  Code/Engine/Foundation/Platform/Posix/OSFile_Posix.h
  Code/UnitTests/FoundationTest/IO/OSFileTest.cpp
Labels: new feature

#1143 Support Editor Generated C++ Plugins on Linux
  CMakeLists.txt
  Code/BuildSystem/CMake/CMakeUtils/ezUtilsExternal.cmake
  Code/BuildSystem/CMake/CMakeUtils/ezUtilsTarget.cmake
  Code/BuildSystem/CMake/ezUtils.cmake
  Code/Editor/EditorFramework/Actions/Implementation/ProjectActions.cpp
  Code/Editor/EditorFramework/CodeGen/CompilerPreferencesWidget.cpp
  Code/Editor/EditorFramework/CodeGen/CompilerPreferencesWidget.moc.h
  Code/Editor/EditorFramework/CodeGen/CppProject.cpp
  Code/Editor/EditorFramework/CodeGen/CppProject.h
  Code/Editor/EditorFramework/CodeGen/CppSettings.cpp
  Code/Editor/EditorFramework/CodeGen/CppSettings.h
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.cpp
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.moc.h
  Code/Editor/EditorFramework/Dialogs/CppProjectDlg.ui
  Code/Editor/EditorFramework/EditorApp/Projects.cpp
  Code/Editor/EditorFramework/EditorApp/Startup.cpp
  Code/Editor/EditorFramework/IPC/EngineProcessConnection.cpp
  Code/Editor/EditorFramework/Panels/AssetCuratorPanel/Implementation/AssetCuratorPanel.cpp
  Code/Engine/Foundation/IO/Implementation/JSONWriter.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/PropertyBaseWidget.moc.h
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/UIServices.cpp
  Code/UnitTests/EditorTest/GenerateCompile/GenerateCompile.cpp
  Code/UnitTests/EditorTest/Project/Project.cpp
  Data/Samples/PacMan/Editor/CppProject.ddl
  Data/Samples/PacMan/RuntimeConfigs/Plugins.ddl
  Data/Samples/PacMan/RuntimeConfigs/Window.ddl
  Data/Tools/ezEditor/Localization/en/Editor.txt
Labels: new feature

#1154 Fixed #1147: Added Custom Data asset type for configuring game-specific C++ structs
  Code/EditorPlugins/Assets/EditorPluginAssets/CustomDataAsset/CustomDataAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/CustomDataAsset/CustomDataAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/CustomDataAsset/CustomDataAssetManager.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/CustomDataAsset/CustomDataAssetManager.h
  Code/EditorPlugins/Assets/EditorPluginAssets/CustomDataAsset/CustomDataAssetWindow.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/CustomDataAsset/CustomDataAssetWindow.moc.h
  Code/EditorPlugins/Assets/EditorPluginAssets/EditorPluginAssets.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/QtResources/CustomData.svg
  Code/EditorPlugins/Assets/EditorPluginAssets/QtResources/resources.qrc
  Code/Engine/Core/Collection/Implementation/CollectionResource.cpp
  Code/Engine/Core/Curves/Implementation/ColorGradientResource.cpp
  Code/Engine/Core/Curves/Implementation/Curve1DResource.cpp
  Code/Engine/Core/Physics/Implementation/SurfaceResource.cpp
  Code/Engine/Core/Prefabs/Implementation/PrefabResource.cpp
  Code/Engine/Core/ResourceManager/Resource.h
  Code/Engine/Core/Utils/CustomData.h
  Code/Engine/Core/Utils/Implementation/CustomData.cpp
  Code/Engine/Core/Utils/Implementation/CustomData_inl.h
  Code/Engine/GameEngine/Animation/Implementation/PropertyAnimResource.cpp
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachineResource.cpp
  Code/Engine/GameEngine/Utils/Implementation/BlackboardTemplateResource.cpp
  Code/Engine/GameEngine/Utils/Implementation/ImageDataResource.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationClipResource.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonResource.cpp
  Code/Engine/RendererCore/Decals/Implementation/DecalAtlasResource.cpp
  Code/Engine/RendererCore/Material/Implementation/MaterialResource.cpp
  Code/Engine/Utilities/Resources/ConfigFileResource.cpp
  Code/EnginePlugins/FmodPlugin/Components/FmodEventComponent.cpp
  Code/EnginePlugins/FmodPlugin/Resources/FmodSoundBankResource.cpp
  Code/EnginePlugins/FmodPlugin/Resources/FmodSoundEventResource.cpp
  Code/EnginePlugins/JoltPlugin/Resources/JoltMeshResource.cpp
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltShapeConvexHullComponent.cpp
  Code/EnginePlugins/ProcGenPlugin/Resources/Implementation/ProcGenGraphResource.cpp
  Code/EnginePlugins/RecastPlugin/Resources/RecastNavMeshResource.cpp
  Code/Samples/SampleGamePlugin/Components/DebugRenderComponent.cpp
  Code/Samples/SampleGamePlugin/Components/DebugRenderComponent.h
  Code/Samples/SampleGamePlugin/CustomData/SampleCustomData.cpp
  Code/Samples/SampleGamePlugin/CustomData/SampleCustomData.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/AddSubElementButton.cpp
  Data/Samples/SampleGame/CustomGameData.ezCustomDataAsset
  Data/Samples/SampleGame/Scenes/Sample.ezScene
  Data/Samples/SampleGame/TypeScript/ez.ts
  Data/Samples/SampleGame/TypeScript/ez/AllComponents.ts
  Data/Samples/SampleGame/TypeScript/ez/AllMessages.ts
  Data/Tools/ezEditor/Localization/en/JoltPlugin.txt
  Data/Tools/ezEditor/Localization/en/PhysXPlugin.txt
Labels: new feature, needs documentation

#1168 Improvements to ezFoundation
  Code/Engine/Foundation/Basics/AllDefinesOff.h
  Code/Engine/Foundation/Basics/Platform/Common.h
  Code/Engine/Foundation/Math/Frustum.h
  Code/Engine/Foundation/Math/Implementation/BoundingBoxSphere_inl.h
  Code/Engine/Foundation/Math/Implementation/BoundingSphere_inl.h
  Code/Engine/Foundation/Math/Implementation/Color_inl.h
  Code/Engine/Foundation/Math/Implementation/Frustum.cpp
  Code/Engine/Foundation/Math/Implementation/Mat3_inl.h
  Code/Engine/Foundation/Math/Implementation/Mat4_inl.h
  Code/Engine/Foundation/Math/Implementation/Plane_inl.h
  Code/Engine/Foundation/Math/Implementation/Quat_inl.h
  Code/Engine/Foundation/Math/Implementation/Vec2_inl.h
  Code/Engine/Foundation/Math/Implementation/Vec3_inl.h
  Code/Engine/Foundation/Math/Implementation/Vec4_inl.h
  Code/Engine/Foundation/Math/Rect.h
  Code/Engine/Foundation/Platform/Posix/UuidGenerator_Posix.h
  Code/Engine/Foundation/Platform/Win/MessageLoop_Win.cpp
  Code/Engine/Foundation/Platform/Win/PipeChannel_Win.cpp
  Code/Engine/Foundation/Platform/Win/UuidGenerator_Win.cpp
  Code/Engine/Foundation/SimdMath/Implementation/FPU/FPUVec4i_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/FPU/FPUVec4u_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/NEON/NEONFloat_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/NEON/NEONVec4f_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/NEON/NEONVec4i_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/NEON/NEONVec4u_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/SSE/SSEFloat_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/SSE/SSEVec4f_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/SSE/SSEVec4i_inl.h
  Code/Engine/Foundation/SimdMath/Implementation/SSE/SSEVec4u_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringBase.h
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Engine/Foundation/Strings/Implementation/StringView.cpp
  Code/Engine/Foundation/Strings/Implementation/String_inl.h
  Code/Engine/Foundation/Strings/String.h
  Code/Engine/Foundation/Strings/StringBuilder.h
  Code/Engine/Foundation/Strings/StringView.h
  Code/Engine/Foundation/System/Implementation/Posix/Process_posix.h
  Code/Engine/Foundation/Types/Types.h
  Code/Engine/Foundation/UserConfig.h
  Code/Engine/Foundation/headerCheckerIgnore.json
  Code/EnginePlugins/AiPlugin/Utils/RcMath.cpp
  Code/EnginePlugins/RecastPlugin/Utils/RcMath.cpp
  Code/UnitTests/FoundationTest/Image/ImageConversionTest.cpp
  Code/UnitTests/FoundationTest/SimdMath/SimdVec4iTest.cpp
  Code/UnitTests/FoundationTest/SimdMath/SimdVec4uTest.cpp
Labels: code quality

#1170 Bouncing Projectiles
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/Implementation/ProjectileComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/ProjectileComponent.h
Labels: new feature

#1171 Converted ezMemoryUtils to use "if constexpr"
  Code/Engine/Core/Utils/Implementation/CustomData_inl.h
  Code/Engine/Foundation/Containers/Implementation/ArrayBase_inl.h
  Code/Engine/Foundation/Containers/Implementation/Deque_inl.h
  Code/Engine/Foundation/Containers/Implementation/HashTable_inl.h
  Code/Engine/Foundation/Containers/Implementation/List_inl.h
  Code/Engine/Foundation/Containers/Implementation/Map_inl.h
  Code/Engine/Foundation/Containers/Implementation/Set_inl.h
  Code/Engine/Foundation/Containers/Implementation/SmallArray_inl.h
  Code/Engine/Foundation/Memory/Implementation/AllocatorBase_inl.h
  Code/Engine/Foundation/Memory/Implementation/BlockStorage_inl.h
  Code/Engine/Foundation/Memory/Implementation/MemoryUtils_inl.h
  Code/Engine/Foundation/Memory/InstanceDataAllocator.h
  Code/Engine/Foundation/Memory/MemoryUtils.h
  Code/Engine/Foundation/Platform/Win/GuardedAllocation_Win.cpp
  Code/Engine/Foundation/Types/TypeTraits.h
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptData.cpp
  Code/UnitTests/FoundationTest/Memory/MemoryUtilsTest.cpp
  Code/UnitTests/FoundationTest/Reflection/ReflectionTest.cpp
Labels: code quality

#1175 Refactored ezMemoryTrackingFlags
  Code/Engine/Core/Scripting/DuktapeContext.h
  Code/Engine/Foundation/Basics/AllDefinesOff.h
  Code/Engine/Foundation/CodeUtils/Implementation/Tokenizer.cpp
  Code/Engine/Foundation/CodeUtils/Preprocessor.h
  Code/Engine/Foundation/Memory/Allocator.h
  Code/Engine/Foundation/Memory/AllocatorBase.h
  Code/Engine/Foundation/Memory/FrameAllocator.h
  Code/Engine/Foundation/Memory/Implementation/Allocator_inl.h
  Code/Engine/Foundation/Memory/Implementation/LargeBlockAllocator_inl.h
  Code/Engine/Foundation/Memory/Implementation/MemoryTracker.cpp
  Code/Engine/Foundation/Memory/Implementation/PageAllocator.cpp
  Code/Engine/Foundation/Memory/Implementation/StackAllocator_inl.h
  Code/Engine/Foundation/Memory/LargeBlockAllocator.h
  Code/Engine/Foundation/Memory/MemoryTracker.h
  Code/Engine/Foundation/Memory/StackAllocator.h
  Code/Engine/Foundation/Platform/Posix/PageAllocator_Posix.h
  Code/Engine/Foundation/Platform/Win/PageAllocator_Win.cpp
  Code/Engine/Foundation/UserConfig.h
  Code/EnginePlugins/InspectorPlugin/App.cpp
  Code/Tools/HeaderCheck/HeaderCheck.cpp
  Code/UnitTests/FoundationTest/Memory/AllocatorTest.cpp
  gitClean.txt
Labels: code quality

#1178 Removed need for special handling of Statics allocator
  Code/Engine/Foundation/Basics/Basics.cpp
  Code/Engine/Foundation/Memory/Implementation/MemoryTracker.cpp
  Code/Engine/Foundation/Memory/MemoryTracker.h
Labels: code quality

#1177 More Node Graph Improvements
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/NodeScene.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/Implementation/NodeView.cpp
  Code/Tools/Libs/GuiFoundation/NodeEditor/NodeScene.moc.h
Labels: improvement

#1182 Skinning in Visual Materials
  Data/Tools/ezEditor/VisualShader/DefaultMaterial.ddl
Labels: improvement

#1186 Changed slider attribute to display an image to visualize the value range
  Code/Editor/EditorFramework/EditorApp/Startup.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/EditorPluginScene.cpp
  Code/Engine/Foundation/Math/Implementation/Math_inl.h
  Code/Engine/Foundation/Math/Math.h
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.cpp
  Code/Engine/Foundation/Reflection/Implementation/PropertyAttributes.h
  Code/Engine/RendererCore/Lights/Implementation/LightComponent.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.moc.h
  Code/UnitTests/FoundationTest/Math/MathTest.cpp
Labels: improvement

#1187 ezString and ezStringBuilder don't track the character count anymore
  Code/Engine/Foundation/IO/Implementation/Stream.cpp
  Code/Engine/Foundation/Strings/Implementation/AllStrings_inl.h
  Code/Engine/Foundation/Strings/Implementation/PathUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBase_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBuilder_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringIterator.h
  Code/Engine/Foundation/Strings/Implementation/StringUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringUtils_inl.h
  Code/Engine/Foundation/Strings/Implementation/StringView.cpp
  Code/Engine/Foundation/Strings/Implementation/StringView_inl.h
  Code/Engine/Foundation/Strings/Implementation/String_inl.h
  Code/Engine/Foundation/Strings/Implementation/UnicodeUtils_inl.h
  Code/Engine/Foundation/Strings/String.h
  Code/Engine/Foundation/Strings/StringBuilder.h
  Code/Engine/Foundation/Strings/UnicodeUtils.h
  Code/Engine/Foundation/Utilities/Implementation/CommandLineUtils.cpp
  Code/Engine/Foundation/ezEngine.natvis
  Code/UnitTests/FoundationTest/Strings/StringBuilderTest.cpp
  Code/UnitTests/FoundationTest/Strings/StringIteratorTest.cpp
  Code/UnitTests/FoundationTest/Strings/UnicodeUtilsTest.cpp
Labels: code quality

#1190 Implemented codepath for inverted normalmaps
  Code/Engine/Texture/TexConv/Implementation/Processor.cpp
  Code/Engine/Texture/TexConv/Implementation/TextureModifications.cpp
  Code/Engine/Texture/TexConv/TexConvProcessor.h
  gitClean.txt
Labels: bug

#1188 Fixed #1128: Made shadow map settings configurable per platform
  Code/Editor/EditorEngineProcess/EngineProcGameApp.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetProfile.cpp
  Code/Editor/EditorFramework/Dialogs/AssetProfilesDlg.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/EditorPluginScene.cpp
  Code/Engine/Core/Configuration/Implementation/PlatformProfile.cpp
  Code/Engine/Core/Configuration/PlatformProfile.h
  Code/Engine/Core/Console/Implementation/Autocomplete.cpp
  Code/Engine/Core/Console/Implementation/LuaInterpreter.cpp
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBaseInit.cpp
  Code/Engine/Foundation/Configuration/CVar.h
  Code/Engine/Foundation/Configuration/Implementation/CVar.cpp
  Code/Engine/Foundation/Configuration/Implementation/CVar_inl.h
  Code/Engine/GameEngine/GameApplication/Implementation/GameApplicationInit.cpp
  Code/Engine/GameEngine/GameState/Implementation/GameState.cpp
  Code/Engine/RendererCore/Lights/Implementation/ShadowPool.cpp
  Code/Engine/RendererCore/Utils/CoreRenderProfile.h
  Code/Engine/RendererCore/Utils/Implementation/CoreRenderProfile.cpp
  Code/UnitTests/FoundationTest/Configuration/CVarsTest.cpp
  Data/Base/Editor/AssetProfiles.ddl
  Data/Samples/Testing Chambers/Editor/AssetProfiles.ddl
  Data/Tools/ezEditor/Localization/en/Editor.txt
  Data/UnitTests/GameEngineTest/Animations/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/Basics/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/Effects/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/Particles/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/PlatformWin/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/StateMachine/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/TypeScript/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/VisualScript/Editor/AssetProfiles.ddl
  Data/UnitTests/GameEngineTest/XR/Editor/AssetProfiles.ddl
  gitClean.txt
Labels: improvement

#1191 Added soft body thickness option
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltClothSheetComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/JoltClothSheetComponent.h
  Code/ThirdParty/Jolt/Core/Core.h
  Code/ThirdParty/Jolt/Core/TempAllocator.h
  Code/ThirdParty/Jolt/Core/TickCounter.h
  Code/ThirdParty/Jolt/Geometry/AABox4.h
  Code/ThirdParty/Jolt/Geometry/ClosestPoint.h
  Code/ThirdParty/Jolt/Jolt.cmake
  Code/ThirdParty/Jolt/Math/Mat44.h
  Code/ThirdParty/Jolt/Math/Mat44.inl
  Code/ThirdParty/Jolt/Math/Math.h
  Code/ThirdParty/Jolt/Math/MathTypes.h
  Code/ThirdParty/Jolt/Physics/Body/Body.cpp
  Code/ThirdParty/Jolt/Physics/Body/Body.h
  Code/ThirdParty/Jolt/Physics/Body/BodyCreationSettings.cpp
  Code/ThirdParty/Jolt/Physics/Body/BodyCreationSettings.h
  Code/ThirdParty/Jolt/Physics/Body/BodyManager.cpp
  Code/ThirdParty/Jolt/Physics/Body/MotionProperties.h
  Code/ThirdParty/Jolt/Physics/Character/CharacterVirtual.cpp
  Code/ThirdParty/Jolt/Physics/Character/CharacterVirtual.h
  Code/ThirdParty/Jolt/Physics/Collision/BroadPhase/QuadTree.cpp
  Code/ThirdParty/Jolt/Physics/Collision/CastSphereVsTriangles.cpp
  Code/ThirdParty/Jolt/Physics/Collision/CollideConvexVsTriangles.cpp
  Code/ThirdParty/Jolt/Physics/Collision/CollideSoftBodyVerticesVsTriangles.h
  Code/ThirdParty/Jolt/Physics/Collision/CollideSphereVsTriangles.cpp
  Code/ThirdParty/Jolt/Physics/Collision/InternalEdgeRemovingCollector.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/BoxShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/CapsuleShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/CompoundShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/ConvexHullShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/CylinderShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/HeightFieldShape.cpp
  Code/ThirdParty/Jolt/Physics/Collision/Shape/HeightFieldShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/MeshShape.cpp
  Code/ThirdParty/Jolt/Physics/Collision/Shape/MeshShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/RotatedTranslatedShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/ScaledShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/Shape.cpp
  Code/ThirdParty/Jolt/Physics/Collision/Shape/Shape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/SphereShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.cpp
  Code/ThirdParty/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.h
  Code/ThirdParty/Jolt/Physics/Collision/Shape/TriangleShape.cpp
  Code/ThirdParty/Jolt/Physics/Collision/Shape/TriangleShape.h
  Code/ThirdParty/Jolt/Physics/Collision/SortReverseAndStore.h
  Code/ThirdParty/Jolt/Physics/PhysicsSystem.cpp
  Code/ThirdParty/Jolt/Physics/SoftBody/SoftBodyMotionProperties.cpp
  Code/ThirdParty/Jolt/Physics/SoftBody/SoftBodySharedSettings.cpp
  Code/ThirdParty/Jolt/Physics/SoftBody/SoftBodySharedSettings.h
  Code/ThirdParty/Jolt/Physics/Vehicle/TrackedVehicleController.cpp
  Code/ThirdParty/Jolt/Physics/Vehicle/VehicleConstraint.h
  Code/ThirdParty/Jolt/Physics/Vehicle/WheeledVehicleController.cpp
  Code/ThirdParty/Jolt/Physics/Vehicle/WheeledVehicleController.h
  Code/ThirdParty/Jolt/RegisterTypes.cpp
  Code/ThirdParty/Jolt/cgmanifest.json
Labels: improvement

#1192 Fixed #1163: Import all animation clips from one asset as separate documents
  Code/Editor/EditorFramework/Assets/AssetBrowserDlg.moc.h
  Code/Editor/EditorFramework/Assets/AssetDocumentGenerator.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserDlg.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocumentGenerator.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/LUTAsset/LUTAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/LUTAsset/LUTAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureAsset/TextureAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureAsset/TextureAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureCubeAsset/TextureCubeAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureCubeAsset/TextureCubeAsset.h
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.h
  Code/EditorPlugins/Kraut/EditorPluginKraut/KrautTreeAsset/KrautTreeAsset.cpp
  Code/EditorPlugins/Kraut/EditorPluginKraut/KrautTreeAsset/KrautTreeAsset.h
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpAnimationImport.cpp
  Data/Tools/ezEditor/Localization/en/AnimationClipAsset.txt
Labels: improvement
