Repository ezEngine/ezEngine, pull requests merged in 2024-11, with the labels that each got.

#1423 Fix for copying states in state machines
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineAssetManager.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineGraph.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptClassAsset/VisualScriptClassAsset.h
  Code/Tools/Libs/ToolsFoundation/Document/Implementation/DocumentManager.cpp
Labels: fix

#1424 Improvements to virtual thumbsticks
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBase.cpp
  Code/Engine/Core/Input/DeviceTypes/DeviceTypes.cpp
  Code/Engine/Core/Input/Implementation/VirtualThumbStick.cpp
  Code/Engine/Core/Input/VirtualThumbStick.h
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager.cpp
  Code/Engine/Foundation/Time/Clock.h
  Code/Engine/GameEngine/Input/InputDebugVis.cpp
  Code/Engine/GameEngine/Input/InputDebugVis.h
  Code/Engine/GameEngine/Input/XBoxController/InputDeviceXBox.cpp
  Code/Engine/RendererCore/Debug/DebugRenderer.h
  Code/Engine/RendererCore/Debug/DebugRendererContext.h
  Code/Engine/RendererCore/Debug/Implementation/DebugRenderer.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.h
  Data/Samples/PacMan/RuntimeConfigs/InputConfig.ddl
Labels: improvement

#1428 Visual script improvements
  Code/Editor/EditorFramework/PropertyGrid/Implementation/ExposedParametersPropertyWidget.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptClassAsset/VisualScriptClassAsset.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptCompiler.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptNodeRegistry.cpp
  Code/Engine/Core/Scripting/ScriptClasses/Implementation/ScriptExtensionClass_CVar.cpp
  Code/Engine/Core/Scripting/ScriptClasses/ScriptExtensionClass_CVar.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BlackboardAnimNodes.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript.h
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeUserData.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
  Code/Tools/StaticLinkUtil/CMakeLists.txt
Labels: improvement

#1431 Various detail improvements
  Code/BuildSystem/CMake/Platforms/Configure_Web.cmake
  Code/Editor/EditorFramework/Dialogs/SnapSettingsDlg.cpp
  Code/Engine/Foundation/Algorithm/Implementation/HashStream.cpp
  Code/Engine/Foundation/IO/FileSystem/Implementation/DataDirTypeFolder.cpp
  Code/Engine/Foundation/IO/Implementation/OSFile.cpp
  Code/Engine/GameEngine/GameApplication/Implementation/GameApplicationInit.cpp
  Code/Engine/RendererFoundation/CommandEncoder/Implementation/CommandEncoder.cpp
  Code/Samples/TextureSample/TextureSample.cpp
  Data/Base/CommonData.ezExportFilter
  Data/Base/Materials/Common/LoadingMaterial.ezMaterial
  Data/Base/Materials/Common/MissingMaterial.ezMaterial
  Data/Base/Materials/Common/MissingMesh.ezMaterial
  Data/Base/Materials/Common/MissingPrefab.ezMaterial
  Data/Base/Shaders/Common/Platform_Web.h
  Data/Base/Shaders/Materials/FallbackMaterial.ezShader
  Data/Base/Textures/LoadingMaterial_D.dds
  Data/Base/Textures/LoadingTexture_D.dds
  Data/Base/Textures/Loading_D.dds
  Data/Base/Textures/MissingMaterial_D.dds
  Data/Base/Textures/MissingMesh_D.dds
  Data/Base/Textures/MissingPrefab_D.dds
  Data/Base/Textures/MissingResource_D.dds
  Data/Base/Textures/MissingTexture_D.dds
  Data/Base/Textures/Reference_D.dds
  Data/Samples/PacMan/Editor/PluginSelection.ddl
  Data/Samples/PacMan/RuntimeConfigs/Window.ddl
  Data/Samples/PacMan/Scenes/Level1.ezScene
  Data/Tools/ezEditor/Localization/en/Editor.txt
  Data/UnitTests/GameEngineTest/Images_Reference/Basic_Engine_Tests_Many_Meshes_000.png
  Data/UnitTests/GameEngineTest/Images_Reference/Basic_Engine_Tests_Skybox_000.png
  Data/UnitTests/GameEngineTest/Images_Reference/Basic_Engine_Tests_Skybox_001.png
  Data/UnitTests/GameEngineTest/Images_Reference/Basic_Engine_Tests_Skybox_002.png
  Data/UnitTests/GameEngineTest/Images_Reference/Basic_Engine_Tests_Skybox_003.png
  Data/UnitTests/GameEngineTest/Images_Reference/Kraut_Tests_TreeRendering_000.png
  Data/UnitTests/GameEngineTest/Images_Reference/Particle_Tests_Billboards_000.png
  Data/UnitTests/GameEngineTest/Images_Reference/Particle_Tests_Billboards_001.png
  Data/UnitTests/GameEngineTest/Images_Reference/Particle_Tests_Billboards_002.png
  Data/UnitTests/GameEngineTest/Images_Reference/Particle_Tests_Lighting_000.png
  Utilities/RunAllTests.ps1
Labels: improvement

#1432 Fixed world reader to be able to instantiate prefabs from multiple threads
  Code/Editor/EditorFramework/EditorApp/Documents.cpp
  Code/Engine/Core/World/GameObject.h
  Code/Engine/Core/WorldSerializer/Implementation/WorldReader.cpp
  Code/Engine/Core/WorldSerializer/WorldReader.h
  Code/Engine/RendererFoundation/Device/Device.h
  Code/Engine/RendererFoundation/Device/Implementation/Device.cpp
  Code/Engine/RendererFoundation/Shader/Types.h
  Code/Engine/RendererVulkan/Shader/Implementation/VertexDeclarationVulkan.cpp
  Code/EnginePlugins/JoltPlugin/Constraints/Implementation/JoltConstraintComponent.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Code/UnitTests/CoreTest/World/MessageTest.cpp
Labels: fix

#1433 Editor usability fixes
  Code/Editor/EditorEngineProcessFramework/EngineProcess/ViewRenderSettings.h
  Code/Editor/EditorFramework/Assets/AssetBrowserView.moc.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFolderView.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserView.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Preferences/QuadViewPreferences.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneViewWidget.cpp
  Code/Engine/Foundation/IO/Implementation/OSFile.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltDynamicActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltQueryShapeActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltStaticActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltShapeSphereComponent.cpp
Labels: improvement

#1434 Added ezRandomPrefabComponent
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezRandomPrefabComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptNodeRegistry.cpp
  Code/Engine/Core/Collection/Implementation/CollectionResource.cpp
  Code/Engine/Core/Curves/Implementation/ColorGradientResource.cpp
  Code/Engine/Core/Curves/Implementation/Curve1DResource.cpp
  Code/Engine/Core/Physics/Implementation/SurfaceResource.cpp
  Code/Engine/Core/Prefabs/Implementation/PrefabReferenceComponent.cpp
  Code/Engine/Core/Prefabs/Implementation/PrefabResource.cpp
  Code/Engine/Core/Utils/Implementation/CustomData.cpp
  Code/Engine/GameEngine/Animation/Implementation/PropertyAnimResource.cpp
  Code/Engine/GameEngine/StateMachine/Implementation/StateMachineResource.cpp
  Code/Engine/GameEngine/Utils/Implementation/BlackboardTemplateResource.cpp
  Code/Engine/GameEngine/Utils/Implementation/ImageDataResource.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraphResource.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationClipResource.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonResource.cpp
  Code/Engine/RendererCore/BakedProbes/Implementation/ProbeTreeSectorResource.cpp
  Code/Engine/RendererCore/Decals/Implementation/DecalAtlasResource.cpp
  Code/Engine/RendererCore/Meshes/Implementation/CpuMeshResource.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshResource.cpp
  Code/Engine/RendererCore/Shader/Implementation/ShaderResource.cpp
  Code/EnginePlugins/GameComponentsPlugin/Placement/Implementation/RandomPrefabComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Placement/RandomPrefabComponent.h
  Code/EnginePlugins/JoltPlugin/Resources/JoltMeshResource.cpp
  Code/EnginePlugins/KrautPlugin/Resources/KrautGeneratorResource.cpp
  Code/EnginePlugins/KrautPlugin/Resources/KrautTreeResource.cpp
  Code/EnginePlugins/ProcGenPlugin/Resources/Implementation/ProcGenGraphResource.cpp
  Code/EnginePlugins/RecastPlugin/Resources/RecastNavMeshResource.cpp
  Code/EnginePlugins/TypeScriptPlugin/Resources/ScriptCompendiumResource.cpp
  Code/EnginePlugins/TypeScriptPlugin/Resources/TypeScriptResource.cpp
  Code/EnginePlugins/VisualScriptPlugin/Resources/VisualScriptClassResource.cpp
Labels: new feature, needs documentation

#1437 A couple of bug fixes
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Document/Implementation/GameObjectDocument.cpp
  Code/Editor/EditorFramework/DragDrop/ComponentDragDropHandler.cpp
  Code/Editor/EditorFramework/DragDrop/ComponentDragDropHandler.h
  Code/Editor/EditorFramework/GUI/Implementation/RawDocumentTreeWidget.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/BoxGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/CapsuleGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/ConeAngleGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/ConeLengthGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/NonUniformBoxGizmo.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/SphereGizmo.cpp
  Code/Editor/EditorFramework/Project/Implementation/ProjectExport.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAssetWindow.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SceneActions.cpp
  Code/Engine/RendererCore/Lights/FillLightComponent.h
  Code/Engine/RendererCore/Lights/Implementation/ClusteredDataUtils.h
  Code/Engine/RendererCore/Lights/Implementation/FillLightComponent.cpp
  Code/Engine/RendererCore/Pipeline/Implementation/RenderPipeline.cpp
  Code/EnginePlugins/JoltPlugin/Jolt.ezPluginBundle
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltCustomShapeInfo.cpp
  Code/Tools/Libs/GuiFoundation/ContainerWindow/ContainerWindow.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyGridWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.moc.h
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpMaterialImport.cpp
  Code/Tools/Libs/ToolsFoundation/Selection/Implementation/SelectionManager.cpp
  Code/Tools/Libs/ToolsFoundation/Selection/SelectionManager.h
  Code/Tools/Libs/ToolsFoundation/Utilities/Implementation/PathPatternFilter.cpp
  Code/Tools/Libs/ToolsFoundation/Utilities/PathPatternFilter.h
  Data/Tools/ezEditor/Localization/en/TextureAsset.txt
Labels: fix

#1438 Added the 'Store' sample project
  Code/EnginePlugins/JoltPlugin/Resources/JoltMeshResource.cpp
  Data/Samples/Store/Thumbnail.jpg
  Data/Samples/Store/ezRemoteProject
Labels: new feature
