Repository ezEngine/ezEngine, pull requests merged in 2024-05, with the labels that each got.

#1278 Exposed CustomData property on components
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/AnimatedMeshComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/LodAnimatedMeshComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/LodAnimatedMeshComponent.h
  Code/Engine/GameEngine/Gameplay/GreyBoxComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Engine/RendererCore/Meshes/CustomMeshComponent.h
  Code/Engine/RendererCore/Meshes/Implementation/CustomMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/LodMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshComponentBase.cpp
  Code/Engine/RendererCore/Meshes/LodMeshComponent.h
  Code/Engine/RendererCore/Meshes/MeshComponentBase.h
Labels: improvement, needs documentation

#1293 jolt can now be built like other libs of ezengine
  Code/ThirdParty/Jolt/CMakeLists.txt
Labels: improvement

#1312 Improved documentation for ezComponent::OnSimulationStarted()
  Code/Engine/Core/World/Component.h
Labels: documentation

#1313 Added interface to provide custom geometry for runtime navmesh generation
  Code/Engine/Core/Interfaces/NavmeshGeoWorldModule.cpp
  Code/Engine/Core/Interfaces/NavmeshGeoWorldModule.h
  Code/Engine/Core/Interfaces/PhysicsQuery.h
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/Engine/Utilities/DataStructures/GameGrid.h
  Code/Engine/Utilities/DataStructures/Implementation/GameGrid_inl.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshGeneration.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshGeneration.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshWorldModule.cpp
  Code/EnginePlugins/AiPlugin/Navigation/NavMesh.h
  Code/EnginePlugins/FmodPlugin/Components/FmodEventComponent.cpp
  Code/EnginePlugins/FmodPlugin/Components/FmodEventComponent.h
  Code/EnginePlugins/JoltPlugin/System/JoltQueries.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
Labels: new feature
