Repository ezEngine/ezEngine, pull requests merged in 2024-02, with the labels that each got.

#1195 Minor container improvements
  Code/Engine/Foundation/Containers/HashSet.h
  Code/Engine/Foundation/Containers/Implementation/HashSet_inl.h
  Code/Engine/Foundation/Containers/Implementation/List_inl.h
  Code/Engine/Foundation/Containers/Implementation/Map_inl.h
  Code/Engine/Foundation/Containers/Implementation/Set_inl.h
  Code/Engine/Foundation/Containers/List.h
  Code/Engine/Foundation/Containers/Map.h
  Code/Engine/Foundation/Containers/Set.h
  Code/UnitTests/FoundationTest/Containers/HashSetTest.cpp
  Code/UnitTests/FoundationTest/Containers/HashTableTest.cpp
  Code/UnitTests/FoundationTest/Containers/ListTest.cpp
  Code/UnitTests/FoundationTest/Containers/MapTest.cpp
  Code/UnitTests/FoundationTest/Containers/SetTest.cpp
  Code/UnitTests/FoundationTest/Performance/Container.cpp
Labels: code quality

#1197 Added ezTypedComponentHandle
  Code/Engine/Core/World/ComponentManager.h
  Code/Engine/Core/World/Declarations.h
  Code/Engine/Core/World/Implementation/ComponentManager_inl.h
  Code/Engine/Core/World/World.h
  Code/UnitTests/CoreTest/World/ComponentTest.cpp
  Code/UnitTests/CoreTest/World/DerivedComponentTest.cpp
Labels: improvement

#1198 Added an LOD component
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezLodComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/Engine/Foundation/IO/FileSystem/FileReader.h
  Code/Engine/Foundation/IO/FileSystem/FileSystem.h
  Code/Engine/Foundation/IO/OSFile.h
  Code/Engine/Foundation/Platform/Posix/OSFile_Posix.h
  Code/Engine/Foundation/Platform/Win/OSFile_Win.cpp
  Code/Engine/Foundation/Reflection/Implementation/Casts.h
  Code/Engine/Foundation/Types/Implementation/Variant_inl.h
  Code/Engine/Foundation/Utilities/GraphicsUtils.h
  Code/Engine/RendererCore/Components/Implementation/LodComponent.cpp
  Code/Engine/RendererCore/Components/LodComponent.h
  Code/Engine/RendererCore/Components/RenderComponent.h
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltClothSheetComponent.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/AddSubElementButton.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/ExpressionPropertyWidget.cpp
  Data/Base/Editor/ShapeIcons/ezLodComponent.dds
  Data/Base/Editor/ShapeIcons/ezLodComponent.png
  Data/Samples/SampleGame/Editor/AssetProfiles.ddl
  Data/Samples/SampleGame/Meshes/Sphere_LOD0.ezMeshAsset
  Data/Samples/SampleGame/Meshes/Sphere_LOD1.ezMeshAsset
  Data/Samples/SampleGame/Meshes/Sphere_LOD2.ezMeshAsset
  Data/Samples/SampleGame/Meshes/Sphere_LOD3.ezMeshAsset
  Data/Samples/SampleGame/Prefabs/LOD-Sphere.ezPrefab
  Data/Samples/SampleGame/Scenes/Sample.ezScene
  Data/Samples/SampleGame/TypeScript/ez.ts
  Data/Samples/SampleGame/TypeScript/ez/AllComponents.ts
Labels: new feature, needs documentation

#1205 ezStringView property support
  Code/Engine/Foundation/Reflection/Implementation/VariantAdapter.h
  Code/Engine/Foundation/Types/Implementation/Variant_inl.h
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyGridWidget.cpp
  Code/Tools/Libs/ToolsFoundation/Command/Implementation/TreeCommands.cpp
  Code/Tools/Libs/ToolsFoundation/Reflection/Implementation/ReflectedTypeStorageManager.cpp
  Code/Tools/Libs/ToolsFoundation/Reflection/Implementation/ToolsReflectionUtils.cpp
  Code/Tools/Libs/ToolsFoundation/Reflection/ReflectedTypeStorageManager.h
  Code/Tools/Libs/ToolsFoundation/Reflection/ToolsReflectionUtils.h
  Code/UnitTests/FoundationTest/Basics/Types/VariantTest.cpp
  Code/UnitTests/FoundationTest/Reflection/FunctionReflectionTest.cpp
  Code/UnitTests/FoundationTest/Reflection/ReflectionTest.cpp
  Code/UnitTests/FoundationTest/Reflection/ReflectionTestClasses.cpp
  Code/UnitTests/FoundationTest/Reflection/ReflectionTestClasses.h
  Code/UnitTests/FoundationTest/Reflection/ReflectionUtilsTest.cpp
  Code/UnitTests/FoundationTest/Serialization/RttiConverterTest.cpp
  Code/UnitTests/ToolsFoundationTest/Reflection/ReflectionTest.cpp
  Code/UnitTests/ToolsFoundationTest/Reflection/ReflectionTestClasses.cpp
  Code/UnitTests/ToolsFoundationTest/Reflection/ReflectionTestClasses.h
Labels: improvement

#1207 Improvements to path / file extension handling
  Code/Engine/Foundation/Strings/Implementation/PathUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Engine/Foundation/Strings/PathUtils.h
  Code/UnitTests/FoundationTest/Strings/PathUtilsTest.cpp
  Code/UnitTests/FoundationTest/Strings/StringBuilderTest.cpp
  Code/UnitTests/FoundationTest/Strings/StringViewTest.cpp
Labels: improvement

#1208 Added ezLodMeshComponent for mesh-only LOD switching
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezLodMeshComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/Engine/Foundation/Time/Timestamp.h
  Code/Engine/RendererCore/Components/Implementation/LodComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/LodMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/LodMeshComponent.h
  Code/UnitTests/FoundationTest/Time/TimestampTest.cpp
Labels: new feature, needs documentation

#1209 Added MeshAsset option to simplify geometry
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetObjects.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetObjects.h
  Code/EditorPlugins/Assets/EditorPluginAssets/Util/MeshImportUtils.cpp
  Code/EditorPlugins/Assets/EnginePluginAssets/MeshAsset/MeshView.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshBufferResource.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshResourceDescriptor.cpp
  Code/Engine/RendererFoundation/Device/Implementation/Device.cpp
  Code/ThirdParty/meshoptimizer/.clang-format
  Code/ThirdParty/meshoptimizer/.editorconfig
  Code/ThirdParty/meshoptimizer/.gitignore
  Code/ThirdParty/meshoptimizer/CMakeLists.txt
  Code/ThirdParty/meshoptimizer/CONTRIBUTING.md
  Code/ThirdParty/meshoptimizer/LICENSE.md
  Code/ThirdParty/meshoptimizer/README.md
  Code/ThirdParty/meshoptimizer/allocator.cpp
  Code/ThirdParty/meshoptimizer/clusterizer.cpp
  Code/ThirdParty/meshoptimizer/indexcodec.cpp
  Code/ThirdParty/meshoptimizer/indexgenerator.cpp
  Code/ThirdParty/meshoptimizer/meshoptimizer.h
  Code/ThirdParty/meshoptimizer/overdrawanalyzer.cpp
  Code/ThirdParty/meshoptimizer/overdrawoptimizer.cpp
  Code/ThirdParty/meshoptimizer/quantization.cpp
  Code/ThirdParty/meshoptimizer/simplifier.cpp
  Code/ThirdParty/meshoptimizer/spatialorder.cpp
  Code/ThirdParty/meshoptimizer/stripifier.cpp
  Code/ThirdParty/meshoptimizer/vcacheanalyzer.cpp
  Code/ThirdParty/meshoptimizer/vcacheoptimizer.cpp
  Code/ThirdParty/meshoptimizer/vertexcodec.cpp
  Code/ThirdParty/meshoptimizer/vertexfilter.cpp
  Code/ThirdParty/meshoptimizer/vfetchanalyzer.cpp
  Code/ThirdParty/meshoptimizer/vfetchoptimizer.cpp
  Code/Tools/Libs/ModelImporter2/CMakeLists.txt
  Code/Tools/Libs/ModelImporter2/Importer/Importer.h
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpMeshImport.cpp
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/ImporterAssimp.h
Labels: new feature, needs documentation

#1211 Changed ezStringView to work around an MSVC code generation bug
  Code/Engine/Foundation/Strings/Implementation/StringView.cpp
  Code/Engine/Foundation/Strings/Implementation/StringView_inl.h
  Code/Engine/Foundation/Strings/StringView.h
  Code/UnitTests/FoundationTest/Strings/StringBuilderTest.cpp
  Code/UnitTests/FoundationTest/Strings/StringViewTest.cpp
  gitClean.txt
Labels: bug

#1212 LOD support for collision meshes and animated meshes
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAssetObjects.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAssetObjects.h
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetObjects.h
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAssetObjects.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAssetObjects.h
  Code/Engine/Foundation/Math/Implementation/Frustum.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/LodAnimatedMeshComponent.cpp
  Code/Engine/GameEngine/Animation/Skeletal/LodAnimatedMeshComponent.h
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpMeshImport.cpp
  Code/UnitTests/FoundationTest/Math/FrustumTest.cpp
Labels: new feature

#1213 Bit Iterators
  Code/Engine/Foundation/Containers/Bitfield.h
  Code/Engine/Foundation/Containers/Implementation/BitIterator.h
  Code/Engine/Foundation/Containers/Implementation/Bitfield_inl.h
  Code/Engine/Foundation/Containers/IterateBits.h
  Code/Engine/Foundation/Types/Bitflags.h
  Code/Engine/RendererDX11/CommandEncoder/Implementation/CommandEncoderImplDX11.cpp
  Code/UnitTests/FoundationTest/Basics/Types/BitflagsTest.cpp
  Code/UnitTests/FoundationTest/Containers/BitfieldTest.cpp
  Code/UnitTests/FoundationTest/Containers/IterateBitsTest.cpp
Labels: improvement

#1216 Updated Recast
  Code/ThirdParty/Recast/Detour/Include/DetourNavMeshQuery.h
  Code/ThirdParty/Recast/Detour/Source/DetourNavMeshBuilder.cpp
  Code/ThirdParty/Recast/Detour/Source/DetourNavMeshQuery.cpp
  Code/ThirdParty/Recast/DetourCrowd/Include/DetourCrowd.h
  Code/ThirdParty/Recast/DetourCrowd/Source/DetourObstacleAvoidance.cpp
  Code/ThirdParty/Recast/DetourCrowd/Source/DetourPathCorridor.cpp
  Code/ThirdParty/Recast/README.md
  Code/ThirdParty/Recast/Recast/Include/Recast.h
  Code/ThirdParty/Recast/Recast/Include/RecastAlloc.h
  Code/ThirdParty/Recast/Recast/Source/RecastContour.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastFilter.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastMesh.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastMeshDetail.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastRasterization.cpp
  Code/ThirdParty/Recast/Recast/Source/RecastRegion.cpp
  Code/ThirdParty/Recast/cgmanifest.json
Labels: maintenance

#1215 Updated ozz to latest version
  Code/ThirdParty/ozz/CMakeLists.txt
  Code/ThirdParty/ozz/animation/offline/additive_animation_builder.cc
  Code/ThirdParty/ozz/animation/offline/animation_builder.cc
  Code/ThirdParty/ozz/animation/offline/animation_optimizer.cc
  Code/ThirdParty/ozz/animation/offline/decimate.h
  Code/ThirdParty/ozz/animation/offline/raw_animation.cc
  Code/ThirdParty/ozz/animation/offline/raw_animation_archive.cc
  Code/ThirdParty/ozz/animation/offline/raw_animation_utils.cc
  Code/ThirdParty/ozz/animation/offline/raw_skeleton.cc
  Code/ThirdParty/ozz/animation/offline/raw_skeleton_archive.cc
  Code/ThirdParty/ozz/animation/offline/raw_track.cc
  Code/ThirdParty/ozz/animation/offline/skeleton_builder.cc
  Code/ThirdParty/ozz/animation/offline/track_builder.cc
  Code/ThirdParty/ozz/animation/offline/track_optimizer.cc
  Code/ThirdParty/ozz/animation/runtime/animation.cc
  Code/ThirdParty/ozz/animation/runtime/animation_keyframe.h
  Code/ThirdParty/ozz/animation/runtime/animation_utils.cc
  Code/ThirdParty/ozz/animation/runtime/blending_job.cc
  Code/ThirdParty/ozz/animation/runtime/ik_aim_job.cc
  Code/ThirdParty/ozz/animation/runtime/ik_two_bone_job.cc
  Code/ThirdParty/ozz/animation/runtime/local_to_model_job.cc
  Code/ThirdParty/ozz/animation/runtime/sampling_job.cc
  Code/ThirdParty/ozz/animation/runtime/skeleton.cc
  Code/ThirdParty/ozz/animation/runtime/skeleton_utils.cc
  Code/ThirdParty/ozz/animation/runtime/track.cc
  Code/ThirdParty/ozz/animation/runtime/track_sampling_job.cc
  Code/ThirdParty/ozz/animation/runtime/track_triggering_job.cc
  Code/ThirdParty/ozz/base/containers/string_archive.cc
  Code/ThirdParty/ozz/base/endianness.h
  Code/ThirdParty/ozz/base/io/archive.cc
  Code/ThirdParty/ozz/base/io/stream.cc
  Code/ThirdParty/ozz/base/log.cc
  Code/ThirdParty/ozz/base/maths/box.cc
  Code/ThirdParty/ozz/base/maths/gtest_math_helper.h
  Code/ThirdParty/ozz/base/maths/math_archive.cc
  Code/ThirdParty/ozz/base/maths/simd_math.cc
  Code/ThirdParty/ozz/base/maths/simd_math_archive.cc
  Code/ThirdParty/ozz/base/maths/soa_math_archive.cc
  Code/ThirdParty/ozz/base/maths/soa_quaternion.h
  Code/ThirdParty/ozz/base/memory/allocator.cc
  Code/ThirdParty/ozz/base/platform.cc
  Code/ThirdParty/ozz/base/span.h
  Code/ThirdParty/ozz/cgmanifest.json
  Code/ThirdParty/ozz/geometry/runtime/skinning_job.cc
  Code/ThirdParty/ozz/options/options.cc
  Code/ThirdParty/ozz/src_fused/ozz_animation.cc
  Code/ThirdParty/ozz/src_fused/ozz_animation_offline.cc
  Code/ThirdParty/ozz/src_fused/ozz_base.cc
Labels: maintenance

#1214 Minor improvement to ezList
  Code/Engine/Foundation/Containers/Implementation/List_inl.h
  Code/Engine/Foundation/Containers/List.h
  Code/UnitTests/FoundationTest/Containers/ListTest.cpp
Labels: improvement

#1220 Updated static link references
  Code/Editor/EditorFramework/EditorApp/Qt.cpp
  Code/Engine/Core/Console/Implementation/Autocomplete.cpp
  Code/Engine/Core/CorePCH.cpp
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBaseInit.cpp
  Code/Engine/Foundation/Basics/Basics.cpp
  Code/Engine/Foundation/Basics/IncludeAll.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionAST.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionASTTransforms.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionByteCode.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionCompiler.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionDeclarations.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionParser.cpp
  Code/Engine/Foundation/CodeUtils/Expression/Implementation/ExpressionVM.cpp
  Code/Engine/Foundation/FoundationPCH.cpp
  Code/Engine/Foundation/Logging/Implementation/ETWWriter.cpp
  Code/Engine/Foundation/Logging/Implementation/Log.cpp
  Code/Engine/Foundation/Math/Implementation/Color.cpp
  Code/Engine/Foundation/Math/Implementation/Frustum.cpp
  Code/Engine/Foundation/Memory/Implementation/MemoryTracker.cpp
  Code/Engine/Foundation/Platform/Android/PlatformDesc_Android.cpp
  Code/Engine/Foundation/Platform/Linux/MessageLoop_Linux.cpp
  Code/Engine/Foundation/Platform/Linux/PlatformDesc_Linux.cpp
  Code/Engine/Foundation/Platform/OSX/PlatformDesc_OSX.cpp
  Code/Engine/Foundation/Platform/UWP/PlatformDesc_UWP.cpp
  Code/Engine/Foundation/Platform/Win/GuardedAllocation_Win.cpp
  Code/Engine/Foundation/Platform/Win/OSFile_Win.cpp
  Code/Engine/Foundation/Platform/Win/PlatformDesc_Win.cpp
  Code/Engine/Foundation/Strings/Implementation/PathUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringBuilder.cpp
  Code/Engine/Foundation/Strings/Implementation/StringUtils.cpp
  Code/Engine/Foundation/Strings/Implementation/StringView.cpp
  Code/Engine/Foundation/Utilities/Implementation/AssetFileHeader.cpp
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/LodAnimatedMeshComponent.cpp
  Code/Engine/GameEngine/GameEnginePCH.cpp
  Code/Engine/RendererCore/Components/Implementation/LodComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/LodMeshComponent.cpp
  Code/Engine/RendererCore/Meshes/Implementation/MeshResourceDescriptor.cpp
  Code/Engine/RendererCore/RendererCorePCH.cpp
  Code/Engine/RendererCore/Shader/Implementation/ShaderStageBinary.cpp
  Code/Engine/RendererCore/ShaderCompiler/Implementation/ShaderManager.cpp
  Code/Engine/RendererCore/ShaderCompiler/Implementation/ShaderParser.cpp
  Code/Engine/RendererCore/Utils/Implementation/CoreRenderProfile.cpp
  Code/Engine/RendererFoundation/Device/Implementation/Device.cpp
  Code/Engine/RendererFoundation/Device/Implementation/ImmutableSamplers.cpp
  Code/Engine/RendererFoundation/RendererFoundationPCH.cpp
  Code/Engine/RendererFoundation/Shader/Implementation/ShaderByteCode.cpp
  Code/Engine/Texture/Image/Implementation/ImageUtils.cpp
  Code/Engine/Texture/TexConv/Implementation/TexComparer.cpp
  Code/Engine/Texture/TexConv/Implementation/TextureModifications.cpp
Labels: maintenance

#1222 Fixed additive animations
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationClipResource.cpp
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpAnimationImport.cpp
Labels: bug
