Repository ezEngine/ezEngine, pull requests merged in 2024-08, with the labels that each got.

#1362 Refactored ezGameState
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/EngineProcessDocumentContext.cpp
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/EngineProcessViewContext.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.h
  Code/Engine/Core/GameApplication/GameApplicationBase.h
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBase.cpp
  Code/Engine/Core/GameState/GameStateBase.h
  Code/Engine/Core/GameState/Implementation/GameStateBase.cpp
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/GameEngine/GameState/FallbackGameState.h
  Code/Engine/GameEngine/GameState/GameState.h
  Code/Engine/GameEngine/GameState/Implementation/FallbackGameState.cpp
  Code/Engine/GameEngine/GameState/Implementation/GameState.cpp
  Code/Engine/GameEngine/Utils/Implementation/SceneLoadUtil.cpp
  Code/Engine/GameEngine/Utils/SceneLoadUtil.h
  Code/EnginePlugins/GameComponentsPlugin/Physics/Implementation/FakeRopeComponent.cpp
  Code/EnginePlugins/TypeScriptPlugin/Components/TypeScriptComponent.cpp
  Code/EnginePlugins/TypeScriptPlugin/Resources/TypeScriptResource.cpp
  Code/EnginePlugins/TypeScriptPlugin/TsBinding/TsBinding.cpp
  Code/Samples/Asteroids/GameState.cpp
  Code/Samples/Asteroids/GameState.h
  Code/Samples/Asteroids/Level.cpp
  Code/Samples/Asteroids/Level.h
  Code/Samples/RtsGamePlugin/GameState/RtsGameState.cpp
  Code/Samples/RtsGamePlugin/GameState/RtsGameState.h
  Code/Samples/SampleGamePlugin/GameState/SampleGameState.cpp
  Code/Samples/SampleGamePlugin/GameState/SampleGameState.h
  Code/Tools/Player/Player.cpp
  Code/UnitTests/GameEngineTest/StereoTest/StereoTest.cpp
  Code/UnitTests/GameEngineTest/StereoTest/StereoTest.h
  Code/UnitTests/GameEngineTest/TestClass/TestClass.cpp
  Code/UnitTests/GameEngineTest/TestClass/TestClass.h
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.h
  Data/Samples/SampleGame/TypeScript/ez.ts
  Data/Samples/SampleGame/TypeScript/ez/AllComponents.ts
  Data/Samples/SampleGame/TypeScript/ez/AllEnums.ts
  Data/Samples/SampleGame/TypeScript/ez/AllMessages.ts
  Data/Samples/Testing Chambers/Scenes/Ropes.ezScene
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/GameState/CppProjectGameState.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/GameState/CppProjectGameState.h
Labels: improvement

#1363 Added component to trigger scene transitions
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/ezSceneTransitionComponent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.h
  Code/Engine/Core/Collection/Implementation/CollectionResource.cpp
  Code/Engine/Core/GameApplication/GameApplicationBase.h
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBase.cpp
  Code/Engine/Core/GameState/GameStateBase.h
  Code/Engine/GameEngine/GameState/FallbackGameState.h
  Code/Engine/GameEngine/GameState/GameState.h
  Code/Engine/GameEngine/GameState/Implementation/FallbackGameState.cpp
  Code/Engine/GameEngine/GameState/Implementation/GameState.cpp
  Code/Engine/GameEngine/Gameplay/Implementation/SceneTransitionComponent.cpp
  Code/Engine/GameEngine/Gameplay/SceneTransitionComponent.h
  Code/Engine/GameEngine/Utils/Implementation/SceneLoadUtil.cpp
  Code/Engine/GameEngine/Utils/SceneLoadUtil.h
  Code/Engine/RendererFoundation/CommandEncoder/Implementation/CommandEncoder.cpp
  Code/EnginePlugins/TypeScriptPlugin/TypeScriptPluginPCH.cpp
  Code/Samples/Asteroids/GameState.cpp
  Code/Samples/Asteroids/GameState.h
  Code/Samples/RtsGamePlugin/GameState/RtsGameState.cpp
  Code/Samples/RtsGamePlugin/GameState/RtsGameState.h
  Code/Samples/SampleGamePlugin/GameState/SampleGameState.cpp
  Code/Samples/SampleGamePlugin/GameState/SampleGameState.h
  Code/Tools/Player/Player.cpp
  Code/UnitTests/GameEngineTest/TestClass/TestClass.cpp
  Data/Base/Editor/ShapeIcons/ezSceneTransitionComponent.dds
  Data/Base/Editor/ShapeIcons/ezSceneTransitionComponent.png
  Data/Base/Editor/ShapeIcons/ezSceneTransitionComponent.svg
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.cpp
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.h
  Data/Samples/SampleGame/TypeScript/ez.ts
  Data/Samples/SampleGame/TypeScript/ez/AllComponents.ts
  Data/Samples/SampleGame/TypeScript/ez/AllEnums.ts
  Data/Samples/Testing Chambers/Scenes/AiScene.ezCollectionAsset
  Data/Samples/Testing Chambers/Scenes/Animation.ezScene
  Data/Samples/Testing Chambers/Scenes/Corridor.ezScene
  Data/Samples/Testing Chambers/Scenes/CorridorScene.ezCollectionAsset
  Data/Samples/Testing Chambers/Scenes/Physics.ezScene
  Data/Samples/Testing Chambers/Scenes/SceneLoading.ezScene
  Data/Samples/Testing Chambers/Scenes/Surfaces_data/Scene Config.ezSceneLayer
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/GameState/CppProjectGameState.cpp
  Data/Tools/ezEditor/CppProject/CppSource/CppProjectPlugin/GameState/CppProjectGameState.h
Labels: new feature, needs documentation

#1369 Moved XBox controller support into GameEngine
  Code/Engine/GameEngine/CMakeLists.txt
  Code/Engine/GameEngine/Input/XBoxController/InputDeviceXBox.cpp
  Code/Engine/GameEngine/Input/XBoxController/InputDeviceXBox.h
  Code/EnginePlugins/XBoxControllerPlugin/CMakeLists.txt
  Code/EnginePlugins/XBoxControllerPlugin/Startup.cpp
  Code/EnginePlugins/XBoxControllerPlugin/XBoxController.ezPluginBundle
  Code/EnginePlugins/XBoxControllerPlugin/XBoxControllerDLL.h
  Code/EnginePlugins/XBoxControllerPlugin/finalize.cmake
  Data/Base/RuntimeConfigs/Plugins.ddl
  Data/Samples/Asteroids/RuntimeConfigs/Plugins.ddl
  Data/Samples/PacMan/RuntimeConfigs/Plugins.ddl
  Data/Samples/SampleGame/RuntimeConfigs/Plugins.ddl
  Data/Samples/Testing Chambers/RuntimeConfigs/Plugins.ddl
Labels: dev work

#1370 Fixed that particle editor would restart effect all the time
  Code/EnginePlugins/ParticlePlugin/System/ParticleSystemInstance.cpp
Labels: fix

#1372 Asset browser fixes
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFolderView.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserView.cpp
Labels: fix

#1378 Fileserve usability improvement
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/EditorApp/ExternalTools.cpp
  Code/EditorPlugins/Fileserve/EditorPluginFileserve/FileserveUI/FileserveWidget.cpp
  Code/EditorPlugins/Fileserve/EditorPluginFileserve/FileserveUI/FileserveWidget.moc.h
  Code/EditorPlugins/Recast/EditorPluginRecast/Recast.ezPluginBundle
  Code/Tools/Fileserve/Fileserve.cpp
  Code/Tools/Fileserve/Fileserve.h
  Code/UnitTests/RemoteTestHarness/TestUwp.cs
Labels: improvement

#1375 Fixed #1280: Added tracking of missing package dependencies
  Code/Editor/EditorFramework/Assets/AssetCurator.h
  Code/Editor/EditorFramework/Assets/AssetProcessor.h
  Code/Editor/EditorFramework/Assets/AssetProcessorMessages.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserView.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetCurator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocument.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetProcessor.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetProcessorMessages.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetUpdates.cpp
  Code/Editor/EditorFramework/Panels/AssetBrowserPanel/CuratorControl.cpp
  Code/Editor/EditorFramework/Panels/AssetCuratorPanel/Implementation/AssetCuratorPanel.cpp
  Code/Editor/EditorProcessor/EditorProcessor.cpp
  Code/UnitTests/EditorTest/Project/Project.cpp
Labels: improvement, fix

#1379 Minor fixes
  Code/Engine/Foundation/IO/DirectoryWatcher.h
  Code/Engine/Foundation/Platform/Win/DirectoryWatcher_Win.cpp
  Code/Engine/Foundation/Platform/Win/MiniDumpUtils_Win.cpp
  Code/Samples/ComputeShaderHistogram/ComputeShaderHistogram.cpp
  Code/ThirdParty/Jolt/Physics/Body/BodyAccess.h
  Code/ThirdParty/Jolt/Physics/PhysicsLock.h
  Code/UnitTests/FoundationTest/IO/DirectoryWatcherTest.cpp
  Code/UnitTests/ToolsFoundationTest/FileSystem/FileSystemModelTest.cpp
  Data/Samples/TextureSample/Shaders/Common.h
Labels: fix

#1383 Assert fix, icon polishing
  Code/Editor/EditorFramework/Actions/Implementation/GameObjectDocumentActions.cpp
  Code/Editor/EditorFramework/Actions/Implementation/GameObjectSelectionActions.cpp
  Code/Editor/EditorFramework/Actions/Implementation/ProjectActions.cpp
  Code/Editor/EditorFramework/Assets/AssetBrowserWidget.moc.h
  Code/Editor/EditorFramework/Assets/AssetBrowserWidget.ui
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFilter.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Document/Implementation/GameObjectDocument.cpp
  Code/Editor/EditorFramework/Gizmos/Implementation/ScaleGizmo.cpp
  Code/Editor/EditorFramework/QtResources/Icons/MoveCameraHere.svg
  Code/Editor/EditorFramework/QtResources/Icons/ObjectsHidden.svg
  Code/Editor/EditorFramework/QtResources/Icons/ObjectsVisible.svg
  Code/Editor/EditorFramework/QtResources/Icons/id.svg
  Code/Editor/EditorFramework/QtResources/resources.qrc
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/LayerActions.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SelectionActions.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SelectionActions.h
  Code/EditorPlugins/Scene/EditorPluginScene/Panels/LayerPanel/LayerAdapter.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/Icons/LayerUnloaded.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/Icons/SelectParent.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/SceneDocument.h
  Code/Engine/GameEngine/CMakeLists.txt
  Code/Engine/GameEngine/DearImgui/DearImgui.h
  Code/Engine/GameEngine/DearImgui/Implementation/DearImgui.cpp
  Code/Tools/Libs/GuiFoundation/Action/Implementation/EditActions.cpp
  Code/Tools/Libs/ToolsFoundation/Command/Implementation/TreeCommands.cpp
  Code/Tools/Libs/ToolsFoundation/Serialization/Implementation/DocumentObjectConverter.cpp
  Data/Tools/ezEditor/Localization/en/Editor.txt
Labels: improvement, fix
