Repository ezEngine/ezEngine, pull requests merged in 2025-10, with the labels that each got.

#1679 Input system API imrovements
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/EngineProcessApp.cpp
  Code/Engine/Core/Input/DeviceTypes/DeviceTypes.cpp
  Code/Engine/Core/Input/DeviceTypes/MouseKeyboard.h
  Code/Engine/Core/Input/Implementation/InputManager.cpp
  Code/Engine/Core/Input/InputManager.h
  Code/Engine/Core/Platform/Android/InputDevice_Android.cpp
  Code/Engine/Core/Platform/Android/InputDevice_Platform.h
  Code/Engine/Core/Platform/Android/Window_Android.cpp
  Code/Engine/Core/Platform/GLFW/InputDevice_GLFW.cpp
  Code/Engine/Core/Platform/GLFW/InputDevice_GLFW.h
  Code/Engine/Core/Platform/GLFW/Window_GLFW.cpp
  Code/Engine/Core/Platform/NoImpl/InputDevice_NoImpl.h
  Code/Engine/Core/Platform/NoImpl/InputDevice_NoImpl.inl
  Code/Engine/Core/Platform/Win/InputDevice_Platform.h
  Code/Engine/Core/Platform/Win/InputDevice_Win.cpp
  Code/Engine/Core/Platform/Win/Window_Win.cpp
  Code/Engine/Core/System/Implementation/Window.cpp
  Code/Engine/Core/System/Window.h
  Code/Engine/GameEngine/Console/Implementation/ImGuiConsole.cpp
  Code/Engine/GameEngine/GameState/Implementation/GameState.cpp
  Code/Samples/MeshRenderSample/MeshRenderSample.cpp
  Code/Samples/ShaderExplorer/ShaderExplorer.cpp
  Data/Samples/RTS/CppSource/RTSPlugin/GameState/Input.cpp
  Data/Samples/SampleGame/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/SampleGame/Editor/AngelScript/Enums.txt
  Data/Samples/SampleGame/Editor/AngelScript/Methods.txt
  Data/Samples/SampleGame/Editor/AngelScript/Properties.txt
  Data/Samples/SampleGame/Editor/AngelScript/Types.txt
  Data/Samples/SampleGame/as.predefined
Labels: improvement

#1680 Fixed #392: Improved controller mapping options
  Code/Engine/Core/Input/DeviceTypes/Controller.h
  Code/Engine/Core/Input/DeviceTypes/DeviceTypes.cpp
  Code/Engine/Core/Platform/GLFW/ControllerInput_GLFW.cpp
  Code/Engine/Core/System/ControllerInput.h
  Code/Engine/Core/System/Implementation/ControllerInput.cpp
  Code/Engine/GameEngine/Input/XBoxController/InputDeviceXBox.cpp
  Code/Engine/GameEngine/Input/XBoxController/InputDeviceXBox.h
  Data/Samples/Crazy Ball/RuntimeConfigs/InputConfig.ddl
Labels: improvement, needs documentation

#1674 Bind Group Resource
  Code/Engine/RendererCore/Material/Implementation/MaterialManager.cpp
  Code/Engine/RendererCore/Material/MaterialManager.h
  Code/Engine/RendererCore/RenderContext/Implementation/RenderContext.cpp
  Code/Engine/RendererCore/RenderContext/RenderContext.h
  Code/Engine/RendererDX11/CommandEncoder/CommandEncoderImplDX11.h
  Code/Engine/RendererDX11/CommandEncoder/Implementation/CommandEncoderImplDX11.cpp
  Code/Engine/RendererDX11/Device/DeviceDX11.h
  Code/Engine/RendererDX11/Device/Implementation/DeviceDX11.cpp
  Code/Engine/RendererDX11/Shader/BindGroupDX11.h
  Code/Engine/RendererDX11/Shader/Implementation/BindGroupDX11.cpp
  Code/Engine/RendererFoundation/CommandEncoder/CommandEncoder.h
  Code/Engine/RendererFoundation/CommandEncoder/CommandEncoderPlatformInterface.h
  Code/Engine/RendererFoundation/CommandEncoder/Implementation/CommandEncoder.cpp
  Code/Engine/RendererFoundation/Descriptors/Enumerations.h
  Code/Engine/RendererFoundation/Device/Device.h
  Code/Engine/RendererFoundation/Device/Implementation/Device.cpp
  Code/Engine/RendererFoundation/Device/Implementation/Device_inl.h
  Code/Engine/RendererFoundation/RendererFoundationDLL.h
  Code/Engine/RendererFoundation/Shader/BindGroup.h
  Code/Engine/RendererFoundation/Shader/Implementation/BindGroup.cpp
  Code/Engine/RendererFoundation/Shader/Implementation/BindGroup_inl.h
  Code/Engine/RendererFoundation/State/Implementation/State.cpp
  Code/Engine/RendererFoundation/State/State.h
  Code/Engine/RendererFoundation/Utils/DependencyTracker.h
  Code/Engine/RendererFoundation/Utils/Implementation/DependencyTracker_inl.h
  Code/Engine/RendererVulkan/CommandEncoder/CommandEncoderImplVulkan.h
  Code/Engine/RendererVulkan/CommandEncoder/Implementation/CommandEncoderImplVulkan.cpp
  Code/Engine/RendererVulkan/Device/DeclarationsVulkan.h
  Code/Engine/RendererVulkan/Device/DeviceVulkan.h
  Code/Engine/RendererVulkan/Device/Implementation/DeviceVulkan.cpp
  Code/Engine/RendererVulkan/Pools/DescriptorSetPoolVulkan.h
  Code/Engine/RendererVulkan/Pools/DescriptorWritePoolVulkan.h
  Code/Engine/RendererVulkan/Pools/Implementation/DescriptorSetPoolVulkan.cpp
  Code/Engine/RendererVulkan/Pools/Implementation/DescriptorWritePoolVulkan.cpp
  Code/Engine/RendererVulkan/Pools/Implementation/TransientDescriptorSetPoolVulkan.cpp
  Code/Engine/RendererVulkan/Pools/TransientDescriptorSetPoolVulkan.h
  Code/Engine/RendererVulkan/Shader/BindGroupLayoutVulkan.h
  Code/Engine/RendererVulkan/Shader/BindGroupVulkan.h
  Code/Engine/RendererVulkan/Shader/Implementation/BindGroupLayoutVulkan.cpp
  Code/Engine/RendererVulkan/Shader/Implementation/BindGroupVulkan.cpp
  Code/Engine/RendererVulkan/Utils/Implementation/ConversionUtilsVulkan.inl.h
  Code/Engine/RendererVulkan/Utils/Implementation/ImageCopyVulkan.cpp
  gitClean.txt
Labels: dev work
