Repository ezEngine/ezEngine, pull requests merged in 2025-09, with the labels that each got.

#1637 Better foot normal detection
  Code/EnginePlugins/JoltPlugin/Character/Implementation/JoltCharacterControllerComponent.cpp
  Code/EnginePlugins/JoltPlugin/Character/Implementation/JoltDefaultCharacterComponent.cpp
  Code/EnginePlugins/JoltPlugin/Character/JoltCharacterControllerComponent.h
Labels: fix

#1643 Implemented smooth bone weight blending
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/BoneWeightsSwitchAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/BoneWeightsSwitchAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SwitchPoseAnimNode.cpp
Labels: improvement

#1645 Added VSE node documentation comments
  Code/EditorPlugins/Assets/EditorPluginAssets/VisualShader/VisualShaderScene.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/VisualShader/VisualShaderTypeRegistry.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/VisualShader/VisualShaderTypeRegistry.h
  Data/Tools/ezEditor/VisualShader/Constants.ddl
  Data/Tools/ezEditor/VisualShader/Conversions.ddl
  Data/Tools/ezEditor/VisualShader/Inputs.ddl
  Data/Tools/ezEditor/VisualShader/Math.ddl
  Data/Tools/ezEditor/VisualShader/Math_Basic.ddl
  Data/Tools/ezEditor/VisualShader/Math_Clamping.ddl
  Data/Tools/ezEditor/VisualShader/Math_Rounding.ddl
  Data/Tools/ezEditor/VisualShader/Math_Trigonometry.ddl
  Data/Tools/ezEditor/VisualShader/Math_Vector.ddl
  Data/Tools/ezEditor/VisualShader/Matrices.ddl
  Data/Tools/ezEditor/VisualShader/Output_Decal.ddl
  Data/Tools/ezEditor/VisualShader/Output_Material.ddl
  Data/Tools/ezEditor/VisualShader/Parameters.ddl
  Data/Tools/ezEditor/VisualShader/Samplers.ddl
  Data/Tools/ezEditor/VisualShader/Textures.ddl
  Data/Tools/ezEditor/VisualShader/Utils.ddl
Labels: improvement

#1651 A couple of RML UI improvements
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/Actions/RmlUiActions.cpp
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/Actions/RmlUiActions.h
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/EditorPluginRmlUi.cpp
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAsset.cpp
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAsset.h
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAssetObjects.cpp
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAssetWindow.cpp
  Code/EnginePlugins/RmlUiPlugin/Implementation/RmlUiContext.cpp
  Code/EnginePlugins/RmlUiPlugin/Implementation/RmlUiSingleton.cpp
  Code/EnginePlugins/RmlUiPlugin/RmlUiSingleton.h
  Data/Base/Editor/DocumentTemplates/Default.rml
  Data/Samples/RTS/CppSource/RTSPlugin/GameState/Input.cpp
  Data/Samples/RTS/RuntimeConfigs/Window.ddl
  Data/Samples/SampleGame/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/SampleGame/Editor/AngelScript/Enums.txt
  Data/Samples/SampleGame/Editor/AngelScript/Methods.txt
  Data/Samples/SampleGame/Editor/AngelScript/Properties.txt
  Data/Samples/SampleGame/as.predefined
  Data/Tools/ezEditor/Localization/en/RmlUiPlugin.txt
Labels: improvement

#1655 Update RmlUI assets when dependency (CSS file) changes
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAsset.cpp
  Code/EditorPlugins/RmlUi/EditorPluginRmlUi/RmlUiAsset/RmlUiAsset.h
  Data/Samples/RTS/UI/Edit.ezRmlUiAsset
  Data/Samples/RTS/UI/SelectMode.ezRmlUiAsset
Labels: improvement

#1661 Make standard app input configurable through ezGameState
  Code/Editor/EditorEngineProcess/EngineProcGameApp.cpp
  Code/EditorPlugins/Scene/EnginePluginScene/SceneContext/SceneContext.cpp
  Code/Engine/Core/GameApplication/GameApplicationBase.h
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBaseInit.cpp
  Code/Engine/Core/GameState/GameStateBase.h
  Code/Engine/GameEngine/GameApplication/GameApplication.h
  Code/Engine/GameEngine/GameApplication/Implementation/GameApplication.cpp
  Code/Engine/GameEngine/GameState/GameState.h
  Code/Engine/GameEngine/GameState/Implementation/FallbackGameState.cpp
  Code/Engine/GameEngine/GameState/Implementation/GameState.cpp
  Code/Tools/ShaderCompiler/ShaderCompiler.h
  Data/Samples/RTS/CppSource/RTSPlugin/GameState/Input.cpp
  Data/Samples/RTS/CppSource/RTSPlugin/GameState/RTSGameState.cpp
  Data/Samples/RTS/CppSource/RTSPlugin/GameState/RTSGameState.h
Labels: improvement

#1658 Improved visual script variables
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/EditorPluginVisualScriptPCH.h
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/Icons/Coroutine.svg
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/Icons/Loop.svg
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/Icons/VariableCategoryArray.svg
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/Icons/VariableCategoryMap.svg
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/Icons/VariableCategoryMember.svg
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/QtResources/resources.qrc
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptClassAsset/VisualScriptClassAsset.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptCompiler.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptGraph.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptGraph.h
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptGraphQt.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptVariable.cpp
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptGraph/VisualScriptVariable.moc.h
  Code/Engine/Foundation/Reflection/Implementation/ReflectionUtils.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptDataType.cpp
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptDataType.h
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptData_inl.h
  Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScriptNodeFunctions.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyBaseWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/PropertyBaseWidget.moc.h
  Code/Tools/Libs/ToolsFoundation/Reflection/Implementation/ReflectedType.cpp
  Code/Tools/Libs/ToolsFoundation/Serialization/Implementation/DocumentObjectConverter.cpp
  Code/UnitTests/GameEngineTest/VisualScriptTest/VisualScriptTest.cpp
  Code/UnitTests/GameEngineTest/VisualScriptTest/VisualScriptTest.h
  Data/Tools/ezEditor/Localization/en/VisualScriptPlugin.txt
  Data/UnitTests/GameEngineTest/Images_Reference/VisualScript_Tests_Variables2_000.png
  Data/UnitTests/GameEngineTest/VisualScript/Data/Variables2Script.ezVisualScriptClassAsset
  Data/UnitTests/GameEngineTest/VisualScript/Scenes/Variables2.ezScene
  gitClean.txt
Labels: new feature

#1665 Fixed #1639: Kraut trees don't reuse physics materials in scene collider mesh
  Code/EnginePlugins/KrautPlugin/Components/KrautTreeComponent.cpp
Labels: fix

#1670 Removed unused Actor System functionality
  Code/Engine/Core/ActorSystem/Actor.h
  Code/Engine/Core/ActorSystem/ActorApiService.h
  Code/Engine/Core/ActorSystem/ActorManager.h
  Code/Engine/Core/ActorSystem/ActorPluginWindow.h
  Code/Engine/Core/ActorSystem/Implementation/Actor.cpp
  Code/Engine/Core/ActorSystem/Implementation/ActorApiService.cpp
  Code/Engine/Core/ActorSystem/Implementation/ActorManager.cpp
  Code/Engine/Core/ActorSystem/Implementation/ActorPluginWindow.cpp
  Code/Engine/Core/CorePCH.cpp
  Code/Engine/Foundation/FoundationPCH.cpp
  Code/Engine/Foundation/Math/Implementation/Random.cpp
  Code/Engine/Foundation/Reflection/Implementation/AbstractProperty.cpp
  Code/Engine/GameEngine/Console/Implementation/ImGuiConsole.cpp
  Code/Engine/GameEngine/XR/Implementation/XRWindow.cpp
  Code/Engine/GameEngine/XR/XRWindow.h
  Code/Engine/RendererFoundation/RendererFoundationPCH.cpp
  Code/Engine/RendererFoundation/State/Implementation/PipelineCache.cpp
  Code/EnginePlugins/AngelScriptPlugin/AngelScriptPluginPCH.cpp
  Code/EnginePlugins/AngelScriptPlugin/Resources/AngelScriptResource.cpp
  Code/EnginePlugins/AngelScriptPlugin/Runtime/AsEngineSingleton.cpp
  Code/EnginePlugins/AngelScriptPlugin/Runtime/AsFunctionDispatch.cpp
  Code/EnginePlugins/GameComponentsPlugin/Camera/Implementation/ThirdPersonViewComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Effects/Implementation/MeshDecalComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/GameComponentsPCH.cpp
  Code/EnginePlugins/GameComponentsPlugin/Placement/Implementation/RandomPrefabComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltBreakableSlabComponent.cpp
  Code/EnginePlugins/JoltPlugin/JoltPluginPCH.cpp
  Utilities/RunStaticLinkUtil.bat
  gitClean.txt
Labels: code quality
