Repository ezEngine/ezEngine, pull requests merged in 2025-03, with the labels that each got.

#1499 Removed unused "Include in Navmesh" option
  Code/EditorPlugins/Scene/EditorPluginScene/Dialogs/ExtractGeometryDlg.cpp
  Code/Engine/GameEngine/Gameplay/GreyBoxComponent.h
  Code/Engine/GameEngine/Gameplay/Implementation/GreyBoxComponent.cpp
  Code/Engine/RendererCore/Utils/WorldGeoExtractionUtil.h
  Code/EnginePlugins/GameComponentsPlugin/Terrain/HeightfieldComponent.h
  Code/EnginePlugins/GameComponentsPlugin/Terrain/Implementation/HeightfieldComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltStaticActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/JoltStaticActorComponent.h
  Code/EnginePlugins/JoltPlugin/Shapes/Implementation/JoltShapeConvexHullComponent.cpp
Labels: maintenance

#1501 Tesselation and recreate engine view fix
  Code/Editor/EditorFramework/DocumentWindow/EngineViewWidget.moc.h
  Code/Editor/EditorFramework/DocumentWindow/Implementation/EngineViewWidget.cpp
  Code/Engine/RendererDX11/CommandEncoder/Implementation/CommandEncoderImplDX11.cpp
  Code/Engine/RendererVulkan/Device/Implementation/SwapChainVulkan.cpp
  Data/Base/Shaders/Materials/MaterialInterpolator.h
Labels: fix

#1504 Added toolbar menus to select snapping options
  Code/Editor/EditorFramework/Actions/Implementation/TransformGizmoActions.cpp
  Code/Editor/EditorFramework/Actions/TransformGizmoActions.h
  Code/Editor/EditorFramework/Dialogs/SnapSettingsDlg.cpp
  Code/Editor/EditorFramework/QtResources/Icons/Snap0125x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap025x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap05x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap0cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap0deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap0x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap1000cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap100cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap10cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap10deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap15deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap1cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap1deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap1x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap200cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap20cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap22deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap25cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap2x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap30deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap400cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap45deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap4x.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap500cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap50cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap5cm.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap5deg.svg
  Code/Editor/EditorFramework/QtResources/Icons/Snap800cm.svg
  Code/Editor/EditorFramework/QtResources/resources.qrc
  Code/EditorPlugins/AngelScript/EditorPluginAngelScript/Actions/AngelScriptActions.cpp
  Code/EditorPlugins/AngelScript/EditorPluginAngelScript/Actions/AngelScriptActions.h
  Code/EditorPlugins/AngelScript/EditorPluginAngelScript/EditorPluginAngelScript.cpp
  Code/Tools/Libs/GuiFoundation/Action/BaseActions.h
  Code/Tools/Libs/GuiFoundation/Action/Implementation/StandardMenus.cpp
  Code/Tools/Libs/GuiFoundation/Action/StandardMenus.h
  Code/Tools/Libs/GuiFoundation/ActionViews/Implementation/QtProxy.cpp
  Code/Tools/Libs/GuiFoundation/ActionViews/Implementation/ToolBarActionMapView.cpp
  Code/Tools/Libs/GuiFoundation/ActionViews/QtProxy.moc.h
  Data/Tools/ezEditor/Localization/en/Editor.txt
Labels: improvement, needs documentation

#1506 Added ezWorld::SearchForObject()
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/Core/World/World.h
  Code/EnginePlugins/AngelScriptPlugin/TypeRegistration/AsRegisterTypes_World.cpp
  Code/UnitTests/CoreTest/World/WorldTest.cpp
  Data/Samples/Testing Chambers/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Methods.txt
  Data/Samples/Testing Chambers/as.predefined
  Data/UnitTests/GameEngineTest/AngelScript/Editor/AngelScript/AllDeclarations.txt
  Data/UnitTests/GameEngineTest/AngelScript/Editor/AngelScript/Methods.txt
  Data/UnitTests/GameEngineTest/AngelScript/Editor/AngelScript/Properties.txt
  Data/UnitTests/GameEngineTest/AngelScript/Tests/GameObjectTest.as
  Data/UnitTests/GameEngineTest/AngelScript/as.predefined
Labels: new feature, needs documentation

#1508 Added const overloads to some ezGameObject functions
  Code/EditorPlugins/VisualScript/EditorPluginVisualScript/VisualScriptClassAsset/VisualScriptClassAsset.cpp
  Code/Engine/Core/Scripting/ScriptClasses/Implementation/ScriptExtensionClass_CVar.cpp
  Code/Engine/Core/World/GameObject.h
  Code/Engine/Core/World/Implementation/GameObject.cpp
  Code/Engine/Core/World/Implementation/World.cpp
  Code/Engine/Core/World/World.h
  Code/Engine/Foundation/Reflection/Implementation/AbstractProperty.h
  Code/Engine/Foundation/Reflection/Implementation/StandardTypes.cpp
  Code/Engine/GameEngine/Animation/Implementation/PathComponent.cpp
  Code/Engine/GameEngine/Gameplay/Implementation/BlackboardComponent.cpp
  Code/EnginePlugins/AngelScriptPlugin/TypeRegistration/AsRegisterTypes_World.cpp
  Code/EnginePlugins/GameComponentsPlugin/Gameplay/Implementation/RaycastComponent.cpp
  Code/EnginePlugins/JoltPlugin/Character/Implementation/JoltCharacterControllerComponent.cpp
  Code/UnitTests/CoreTest/World/ComponentTest.cpp
  Code/UnitTests/CoreTest/World/WorldTest.cpp
  Code/UnitTests/GameEngineTest/Basics/Basics.cpp
Labels: improvement

#1515 CreateResource is no longer run under the resource manager lock
  Code/Engine/Core/ResourceManager/Implementation/ResourceLoading.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager_inl.h
  Code/Engine/Core/ResourceManager/ResourceManager.h
  Code/Engine/Core/World/Implementation/WorldData.cpp
  Code/Engine/Foundation/Containers/IdTable.h
  Code/Engine/Foundation/Containers/Implementation/IdTable_inl.h
  Code/Engine/Foundation/ezEngine.py
  Code/Engine/RendererCore/Debug/Implementation/DebugRenderer.cpp
  Code/UnitTests/CoreTest/ResourceManager/ResourceManagerTest.cpp
  Code/UnitTests/FoundationTest/Containers/IdTableTest.cpp
  Code/UnitTests/TestFramework/Framework/SimpleTest.cpp
  Code/UnitTests/TestFramework/Framework/SimpleTest.h
  Code/UnitTests/TestFramework/Framework/TestFramework.cpp
Labels: improvement
