Repository ezEngine/ezEngine, pull requests merged in 2025-07, with the labels that each got.

#1594 Enabled auto-hide feature on panels
  Code/ThirdParty/ads/gnu-lgpl-v2.1.md
  Code/ThirdParty/ads/images/maximize-button.svg
  Code/ThirdParty/ads/images/minimize-button.svg
  Code/ThirdParty/ads/images/pin-button.svg
  Code/ThirdParty/ads/images/restore-button.svg
  Code/ThirdParty/ads/images/vs-pin-button-disabled.svg
  Code/ThirdParty/ads/images/vs-pin-button-pinned.svg
  Code/ThirdParty/ads/images/vs-pin-button.svg
  Code/ThirdParty/ads/images/vs-pin-button_45.svg
  Code/Tools/Libs/GuiFoundation/ContainerWindow/ContainerWindow.cpp
  Code/Tools/Libs/GuiFoundation/DocumentWindow/DocumentWindow.cpp
Labels: improvement

#1596 Fixed #1368: Animations stopped when exclusively visualizing Jolt geometry
  Code/Engine/GameEngine/Animation/Skeletal/Implementation/SimpleAnimationComponent.cpp
  Code/EnginePlugins/JoltPlugin/Actors/Implementation/JoltQueryShapeActorComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltBreakableSlabComponent.cpp
Labels: fix

#1597 Added Layer panel toolbar, and option to not automatically switch the layer
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/LayerActions.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/LayerActions.h
  Code/EditorPlugins/Scene/EditorPluginScene/EditorPluginScene.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/InputContexts/SceneSelectionContext.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Panels/LayerPanel/LayerPanel.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/Icons/SelectAllowed.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/Icons/SelectForbidden.svg
  Code/EditorPlugins/Scene/EditorPluginScene/QtResources/resources.qrc
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/Scene2Document.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Scene/Scene2Document.h
  Data/Samples/Testing Chambers/Scenes/Hall_data/Level Geometry.ezSceneLayer
  Data/Samples/Testing Chambers/Scenes/Hall_data/Scene Config.ezSceneLayer
  Data/Tools/ezEditor/Localization/en/SceneAsset.txt
Labels: new feature, needs documentation

#1601 Added navmesh raycast and random point functions to NavigationComponent
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavigationComponent.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavigationComponent.h
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/NavMeshQuery.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Implementation/Navigation.cpp
  Code/EnginePlugins/AiPlugin/Navigation/NavMeshQuery.h
  Data/Samples/Testing Chambers/AI/Al-Bot.as
  Data/Samples/Testing Chambers/AI/Al-Bot.ezPrefab
  Data/Samples/Testing Chambers/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Methods.txt
  Data/Samples/Testing Chambers/Scenes/Hall.ezScene
  Data/Samples/Testing Chambers/Scenes/Hall_data/Level Geometry.ezSceneLayer
  Data/Samples/Testing Chambers/as.predefined
Labels: new feature

#1610 Input fix for PTG regression
  Code/Engine/Core/GameApplication/GameApplicationBase.h
  Code/Engine/Core/GameApplication/Implementation/GameApplicationBase.cpp
  Code/Engine/GameEngine/GameApplication/GameApplication.h
  Code/Engine/GameEngine/GameApplication/Implementation/GameApplication.cpp
Labels: fix

#1612 Update ragdoll poses more efficiently
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.cpp
  Code/Engine/Foundation/Containers/Implementation/ArrayBase_inl.h
  Code/Engine/Foundation/Containers/Implementation/Deque_inl.h
  Code/Engine/Foundation/Containers/Implementation/SmallArray_inl.h
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRagdollComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/JoltRagdollComponent.h
Labels: improvement, needs documentation

#1619 Added Visual Shader nodes: step, smoothstep, modulo
  Data/Samples/Testing Chambers/Materials/Pumping.ezMaterialAsset
  Data/Samples/Testing Chambers/Meshes/Cylinder.ezMeshAsset
  Data/Samples/Testing Chambers/Scenes/Hall.ezScene
  Data/Tools/ezEditor/VisualShader/Math.ddl
  Data/Tools/ezEditor/VisualShader/Math_Basic.ddl
Labels: improvement

#1620 Small fixes: ragdolls, skeleton pose, navigation
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserDlg.cpp
  Code/Engine/Foundation/Math/Implementation/Vec3_inl.h
  Code/Engine/Foundation/Math/Vec3.h
  Code/Engine/GameEngine/AI/Implementation/SensorComponent.cpp
  Code/Engine/GameEngine/AI/SensorComponent.h
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonPoseComponent.cpp
  Code/EnginePlugins/AiPlugin/Navigation/Components/NavigationComponent.cpp
  Code/EnginePlugins/JoltPlugin/Components/Implementation/JoltRagdollComponent.cpp
  Code/UnitTests/FoundationTest/Math/Vec3Test.cpp
  Data/Base/Editor/DocumentTemplates/Default.ezScene
  Data/Samples/Testing Chambers/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Methods.txt
  Data/Samples/Testing Chambers/Scenes/Ai.ezScene
  Data/Samples/Testing Chambers/Scenes/SceneLoading.ezScene
  Data/Samples/Testing Chambers/as.predefined
  gitClean.txt
Labels: improvement, fix
