Repository ezEngine/ezEngine, pull requests merged in 2025-04, with the labels that each got.

#1517 MiniAudio: Added support for sound groups
  Code/EditorPlugins/MiniAudio/EditorPluginMiniAudio/SoundAsset/MiniAudioSoundAsset.cpp
  Code/EditorPlugins/MiniAudio/EditorPluginMiniAudio/SoundAsset/MiniAudioSoundAsset.h
  Code/Engine/Core/Interfaces/SoundInterface.cpp
  Code/Engine/Core/Interfaces/SoundInterface.h
  Code/EnginePlugins/FmodPlugin/Components/FmodEventComponent.cpp
  Code/EnginePlugins/FmodPlugin/Components/FmodEventComponent.h
  Code/EnginePlugins/FmodPlugin/FmodSingleton.cpp
  Code/EnginePlugins/FmodPlugin/FmodSingleton.h
  Code/EnginePlugins/MiniAudioPlugin/Components/MiniAudioSoundComponent.cpp
  Code/EnginePlugins/MiniAudioPlugin/Components/MiniAudioSoundComponent.h
  Code/EnginePlugins/MiniAudioPlugin/MiniAudioSingleton.cpp
  Code/EnginePlugins/MiniAudioPlugin/MiniAudioSingleton.h
  Code/EnginePlugins/MiniAudioPlugin/Resources/MiniAudioSoundResource.cpp
  Code/EnginePlugins/MiniAudioPlugin/Resources/MiniAudioSoundResource.h
  Data/Samples/PacMan/CppSource/PacManPlugin/GameState/PacManGameState.cpp
  Data/Samples/PacMan/Editor/MiniAudioSoundGroups.txt
  Data/Samples/PacMan/Scenes/Main.ezScene
  Data/Samples/PacMan/Sound/MiniAudio/CollectCoin.ezMiniAudioSoundAsset
  Data/Samples/PacMan/Sound/MiniAudio/LoseGame.ezMiniAudioSoundAsset
  Data/Samples/PacMan/Sound/WinGame.ezMiniAudioSoundAsset
  Data/Samples/RTS/CppSource/RTSPlugin/Components/SelectableComponent.cpp
  Data/Samples/Testing Chambers/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Methods.txt
  Data/Samples/Testing Chambers/Prefabs/GasCylinder_data/GasCylinder.as
  Data/Samples/Testing Chambers/as.predefined
  Data/Tools/ezEditor/ProjectTemplates/Basic FPS/Editor/AngelScript/AllDeclarations.txt
  Data/Tools/ezEditor/ProjectTemplates/Basic FPS/Editor/AngelScript/Methods.txt
  Data/Tools/ezEditor/ProjectTemplates/Basic FPS/Editor/AngelScript/Properties.txt
  Data/Tools/ezEditor/ProjectTemplates/Basic FPS/as.predefined
Labels: dev work

#1518 Added option to extract root motion of animation clips from feet joints
  Code/Editor/EditorEngineProcessFramework/EngineProcess/Implementation/EngineProcessDocumentContext.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipActions.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipActions.h
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAssetWindow.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAssetWindow.moc.h
  Code/EditorPlugins/Assets/EditorPluginAssets/EditorPluginAssets.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/QtResources/Foot.svg
  Code/EditorPlugins/Assets/EditorPluginAssets/QtResources/resources.qrc
  Code/EditorPlugins/Assets/EnginePluginAssets/AnimationClipAsset/AnimationClipContext.cpp
  Code/EditorPlugins/Assets/EnginePluginAssets/AnimationClipAsset/AnimationClipContext.h
  Code/Engine/GameEngine/Gameplay/Implementation/BlackboardComponent.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BlackboardAnimNodes.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimationClipResource.h
  Code/Engine/RendererCore/AnimationSystem/EditableSkeleton.h
  Code/Engine/RendererCore/AnimationSystem/Implementation/AnimationClipResource.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/EditableSkeleton.cpp
  Code/Engine/RendererCore/AnimationSystem/Implementation/SkeletonResource.cpp
  Code/Engine/RendererCore/AnimationSystem/SkeletonResource.h
  Code/Tools/Libs/GuiFoundation/Action/ActionMapManager.h
  Code/Tools/Libs/GuiFoundation/Action/Implementation/ActionMapManager.cpp
  Code/Tools/Libs/GuiFoundation/DocumentWindow/DocumentWindow.moc.h
  Data/Tools/ezEditor/Localization/en/AnimationClipAsset.txt
  Data/UnitTests/GameEngineTest/AngelScript/Editor/AngelScript/AllDeclarations.txt
  Data/UnitTests/GameEngineTest/AngelScript/as.predefined
Labels: new feature, improvement, needs documentation

#1519 Animation graph improvements (+ other fixes)
  Code/Editor/EditorFramework/PropertyGrid/Implementation/ExposedBoneWidget.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/FileBrowserPropertyWidget.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimGraphNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BlackboardAnimNodes.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/BlackboardAnimNodes.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/MathAnimNodes.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes/MathAnimNodes.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace1DAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleBlendSpace2DAnimNode.h
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/Implementation/AnimGraphNode.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/PropertyWidget.cpp
  Code/Tools/Libs/GuiFoundation/PropertyGrid/Implementation/VarianceWidget.cpp
  Code/Tools/Libs/ModelImporter2/Importer/Importer.h
  Code/Tools/Libs/ModelImporter2/ImporterAssimp/AssimpAnimationImport.cpp
  Data/Tools/ezEditor/Localization/en/AnimationClipAsset.txt
Labels: improvement, needs documentation, fix

#1521 Rider Cpp support
  Code/Editor/EditorFramework/CodeGen/CppProject.cpp
  Code/Editor/EditorFramework/CodeGen/CppProject.h
  Code/Editor/EditorFramework/Panels/AssetBrowserPanel/AssetBrowserPanel.cpp
  Code/Editor/EditorFramework/PropertyGrid/Implementation/FileBrowserPropertyWidget.cpp
  Code/EditorPlugins/AngelScript/EditorPluginAngelScript/AngelScriptAsset/AngelScriptAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/EditorPluginAssets.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MaterialAsset/MaterialAssetWindow.cpp
  Code/Tools/Libs/GuiFoundation/UIServices/Implementation/UIServices.cpp
  Code/Tools/Libs/GuiFoundation/UIServices/UIServices.moc.h
Labels: improvement

#1522 Improved editor camera speed
  Code/Editor/EditorFramework/InputContexts/CameraMoveContext.h
  Code/Editor/EditorFramework/InputContexts/Implementation/CameraMoveContext.cpp
  Code/Editor/EditorFramework/InputContexts/Implementation/OrbitCameraContext.cpp
  Code/Editor/EditorFramework/Preferences/EditorPreferences.cpp
  Code/Editor/EditorFramework/Preferences/EditorPreferences.h
Labels: improvement, needs documentation

#1532 Added look-at helpers to ezGameObject
  Code/Engine/Core/World/GameObject.h
  Code/Engine/Core/World/Implementation/GameObject.cpp
  Code/Engine/Foundation/Math/Implementation/Vec3_inl.h
  Code/Engine/Foundation/Math/Vec3.h
  Code/EnginePlugins/AngelScriptPlugin/TypeRegistration/AsRegisterTypes_World.cpp
  Code/UnitTests/FoundationTest/Math/Vec3Test.cpp
  gitClean.txt
Labels: improvement

#1533 Added a ThirdPersonView component for camera placement
  Code/Engine/Core/World/Implementation/GameObject.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.cpp
  Code/Engine/RendererCore/AnimationSystem/AnimGraph/AnimNodes2/SampleAnimClipSequenceAnimNode.h
  Code/EnginePlugins/GameComponentsPlugin/Camera/Implementation/ThirdPersonViewComponent.cpp
  Code/EnginePlugins/GameComponentsPlugin/Camera/ThirdPersonViewComponent.h
  Data/Samples/Testing Chambers/Animations/Pete/Pete3rdPersonCtrl.ezPrefab
  Data/Samples/Testing Chambers/Animations/Pete/PeteThirdPerson.ezVisualScriptClassAsset
  Data/Samples/Testing Chambers/Editor/AngelScript/AllDeclarations.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Methods.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Properties.txt
  Data/Samples/Testing Chambers/Editor/AngelScript/Types.txt
  Data/Samples/Testing Chambers/Scenes/Animation.ezScene
  Data/Samples/Testing Chambers/as.predefined
Labels: new feature, needs documentation

#1528 Add box and capsule shape queries
  Code/Engine/Core/Interfaces/PhysicsWorldModule.h
  Code/EnginePlugins/JoltPlugin/System/JoltQueries.cpp
  Code/EnginePlugins/JoltPlugin/System/JoltWorldModule.h
Labels: improvement

#1542 Made it easier to import static and animated meshes
  Code/Editor/EditorFramework/Assets/AssetBrowserWidget.moc.h
  Code/Editor/EditorFramework/Assets/AssetProcessor.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserFilter.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserModel.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetCurator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocumentGenerator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetProcessor.cpp
  Code/Editor/EditorFramework/Preferences/ProjectPreferences.cpp
  Code/Editor/EditorFramework/Preferences/ProjectPreferences.h
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimatedMeshAsset/AnimatedMeshAssetObjects.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/Dialogs/MeshImportDlg.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/Dialogs/MeshImportDlg.moc.h
  Code/EditorPlugins/Assets/EditorPluginAssets/Dialogs/MeshImportDlg.ui
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetImport.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetObjects.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/Util/MeshImportUtils.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/Util/MeshImportUtils.h
  Code/EditorPlugins/Scene/EditorPluginScene/EditorPluginScene.cpp
  Code/Engine/Core/ResourceManager/Implementation/WorkerTasks.cpp
  Code/Engine/Foundation/Types/Implementation/Status.cpp
  Code/Engine/Foundation/Types/Status.h
  Code/Engine/Foundation/Utilities/Implementation/Progress.cpp
  Code/Engine/Foundation/Utilities/Progress.h
  Code/Tools/Libs/ModelImporter2/ModelImporter.cpp
  Code/Tools/Libs/ModelImporter2/ModelImporter.h
  Data/Tools/ezEditor/Localization/en/AnimatedMeshAsset.txt
  Data/Tools/ezEditor/Localization/en/MeshAsset.txt
Labels: improvement, needs documentation

#1543 Asset import improvements
  Code/Editor/EditorFramework/Assets/AssetBrowserWidget.moc.h
  Code/Editor/EditorFramework/Assets/AssetDocumentGenerator.h
  Code/Editor/EditorFramework/Assets/Implementation/AssetBrowserWidget.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetDocumentGenerator.cpp
  Code/Editor/EditorFramework/Assets/Implementation/AssetImportDlg.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/AnimationClipAsset/AnimationClipAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/DecalAsset/DecalAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/LUTAsset/LUTAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/MeshAsset/MeshAssetImport.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/SkeletonAsset/SkeletonAsset.h
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureAsset/TextureAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/TextureCubeAsset/TextureCubeAsset.cpp
  Code/EditorPlugins/Assets/EditorPluginAssets/Util/MeshImportUtils.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.cpp
  Code/EditorPlugins/Jolt/EditorPluginJolt/CollisionMeshAsset/JoltCollisionMeshAsset.h
  Code/EditorPlugins/Kraut/EditorPluginKraut/KrautTreeAsset/KrautTreeAsset.cpp
  Code/EditorPlugins/MiniAudio/EditorPluginMiniAudio/SoundAsset/MiniAudioSoundAsset.cpp
  Code/EditorPlugins/MiniAudio/EditorPluginMiniAudio/SoundAsset/MiniAudioSoundAsset.h
  Data/Samples/Testing Chambers/Thumbnail.jpg
Labels: improvement, needs documentation

#1545 Force Loading of Highest Quality Levels during Tests
  Code/EditorPlugins/Scene/EditorPluginScene/Actions/SceneActions.cpp
  Code/EditorPlugins/Scene/EditorPluginScene/Dialogs/ExportAndRunDlg.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceLoading.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager.cpp
  Code/Engine/Core/ResourceManager/Implementation/ResourceManager_inl.h
  Code/Engine/Core/ResourceManager/ResourceManager.h
  Code/UnitTests/CoreTest/ResourceManager/ResourceManagerTest.cpp
Labels: fix
